'use server';

import { revalidatePath, revalidateTag } from 'next/cache';
import { requirePermission, requireUser } from './auth';
import { aiAvailable, ask, clip } from './ai';
import * as repo from './repo';
import { getSettings } from './queries';
import { addRecord, deleteRecord, findRecord, listRecords, updateRecord } from './records';
import { listContacts } from './repo-extra3';
import { parseLexicon, type MethodSettings } from './method';
import { stripHtml, uid } from './utils';
import type { ActionResult } from './actions';

export async function saveMethodSettingsAction(m: MethodSettings): Promise<ActionResult> { await requirePermission('settings.manage'); const s = await getSettings(); await repo.saveSettingsRow({ ...s, method: { checklists: Object.fromEntries(Object.entries(m.checklists ?? {}).map(([k, v]) => [k, (v ?? '').slice(0, 2000)])), lexicon: (m.lexicon ?? '').slice(0, 10000), twoSources: !!m.twoSources, crossReadKinds: (m.crossReadKinds ?? []).slice(0, 10) } }); revalidateTag('settings', 'max'); revalidatePath('/admin/metodo'); return { ok: true, message: 'Regole della casa salvate.' }; }
/** Quello che serve all'editor: check-list del genere, lessico, nomi della rubrica per le persone citate. */
export async function methodInfoAction(): Promise<{ method: MethodSettings; contacts: { id: string; name: string; role: string; org: string; notes: string; phone: string }[] }> { await requireUser(); const s = await getSettings(); return { method: { ...(s.method ?? {}), lexicon: s.method?.lexicon ?? '' }, contacts: (await listContacts('', 500)).map((c) => ({ id: c.id, name: c.name, role: c.role, org: c.org, notes: c.notes, phone: c.phone })) }; }
export async function lexiconRulesAction(): Promise<ReturnType<typeof parseLexicon>> { await requireUser(); return parseLexicon((await getSettings()).method?.lexicon ?? ''); }
/** Rilettura incrociata: chi rilegge lo dichiara; non può essere l'autore. */
export async function markReviewedAction(articleId: string): Promise<ActionResult & { reviewedBy?: string; reviewedAt?: string }> { const u = await requireUser(); const a = await repo.findArticle(articleId); if (!a) return { ok: false, message: 'Salva prima l\'articolo.' }; if (a.authorId === u.id) return { ok: false, message: 'La rilettura incrociata la fa un collega, non l\'autore.' }; const at = new Date().toISOString(); await repo.patchArticle(articleId, { extra: JSON.stringify({ ...(a.extra ?? {}), reviewedBy: u.id, reviewedAt: at }) }); await repo.insertActivity({ id: uid('ac'), userId: u.id, action: 'ha riletto', target: a.title, createdAt: at }); return { ok: true, message: 'Rilettura registrata.', reviewedBy: u.id, reviewedAt: at }; }
/** Registro delle fonti anonime: identità cifrata, leggibile solo dalle due persone indicate, ogni lettura resta nel registro delle attività. */
export async function anonSourceSaveAction(articleId: string, s: { who: string; how: string; verifiedAt: string; allowed: string[] }): Promise<ActionResult> { const u = await requireUser(); const a = await repo.findArticle(articleId); if (!a) return { ok: false, message: 'Salva prima l\'articolo.' }; if (s.who.trim().length < 3) return { ok: false, message: 'Chi è la fonte?' }; const allowed = [...new Set([u.id, ...s.allowed])].slice(0, 2); const { seal } = await import('./vault'); await addRecord('anon-source', { ref: articleId, owner: u.id, data: { blob: await seal(JSON.stringify({ who: s.who.trim().slice(0, 300), how: s.how.trim().slice(0, 1000), verifiedAt: s.verifiedAt })), allowed, title: a.title, by: u.name } }); await repo.insertActivity({ id: uid('ac'), userId: u.id, action: 'ha registrato una fonte anonima per', target: a.title, createdAt: new Date().toISOString() }); revalidatePath('/admin/metodo'); return { ok: true, message: `Identità cifrata e registrata: possono leggerla ${allowed.length === 2 ? 'due persone' : 'solo tu'}.` }; }
export async function anonSourceRevealAction(id: string): Promise<ActionResult & { who?: string; how?: string; verifiedAt?: string }> { const u = await requireUser(); const r = await findRecord<{ blob: string; allowed: string[]; title: string }>(id); if (!r || r.kind !== 'anon-source') return { ok: false, message: 'Non trovata.' }; if (!r.data.allowed.includes(u.id)) { await repo.insertActivity({ id: uid('ac'), userId: u.id, action: 'ha tentato di leggere una fonte anonima di', target: r.data.title, createdAt: new Date().toISOString() }); return { ok: false, message: 'Non sei tra le persone autorizzate: il tentativo è registrato.' }; } const { open } = await import('./vault'); const d = JSON.parse(await open(r.data.blob)) as { who: string; how: string; verifiedAt: string }; await repo.insertActivity({ id: uid('ac'), userId: u.id, action: 'ha letto l\'identità di una fonte anonima di', target: r.data.title, createdAt: new Date().toISOString() }); return { ok: true, ...d }; }
export async function anonSourceDeleteAction(id: string): Promise<ActionResult> { const u = await requireUser(); const r = await findRecord<{ allowed: string[] }>(id); if (!r || r.kind !== 'anon-source' || !r.data.allowed.includes(u.id)) return { ok: false, message: 'Non consentito.' }; await deleteRecord(id); revalidatePath('/admin/metodo'); return { ok: true, message: 'Registrazione distrutta.' }; }
/** Diritto all'oblio: decisione motivata, applicata (noindex) e registrata in forma anonima. */
export async function oblivionDecideAction(id: string, d: { decision: 'accolta' | 'parziale' | 'respinta'; motivation: string; noindex: boolean; anonymize: boolean }): Promise<ActionResult> {
  const u = await requirePermission('settings.manage'); const r = await findRecord<Record<string, string>>(id); if (!r || r.kind !== 'oblio') return { ok: false, message: 'Richiesta non trovata.' }; if (d.motivation.trim().length < 20) return { ok: false, message: 'Serve una motivazione scritta (almeno 20 caratteri).' };
  let applied = ''; if (d.noindex || d.anonymize) { const slug = r.data.url.split('/').filter(Boolean).pop() ?? ''; const a = slug ? await repo.findArticleBySlug(slug, false) : undefined; if (a) { if (d.noindex) { await repo.upsertArticle({ ...a, seo: { ...a.seo, noIndex: true } }); applied += ' Articolo escluso dai motori di ricerca.'; } if (d.anonymize) { applied += ' Da anonimizzare a mano nel testo (l\'editor non lo fa da solo).'; } } else applied = ' (Articolo non trovato dall\'indirizzo: applica a mano.)'; }
  await updateRecord(id, { status: 'done', data: { reason: r.data.reason, decision: d.decision, motivation: d.motivation.trim().slice(0, 2000), decidedAt: new Date().toISOString(), decidedBy: u.name, noindex: d.noindex ? '1' : '', email: r.data.email, url: r.data.url } });
  const { mailConfigured, sendMail, mailLayout, esc } = await import('./mailer'); if (r.data.email && (await mailConfigured())) await sendMail({ to: r.data.email, subject: 'La decisione sulla tua richiesta', html: mailLayout((await getSettings()).siteName, 'Diritto all\'oblio', `<p>Richiesta <b>${d.decision}</b>.</p><p>${esc(d.motivation)}</p>`) }).catch(() => {});
  revalidatePath('/oblio'); revalidatePath('/admin/metodo'); return { ok: true, message: `Decisione registrata: ${d.decision}.${applied}` };
}
/** Post-mortem: cosa è successo, perché, cosa cambia; con una versione pubblica se la redazione lo decide. */
export async function postmortemSaveAction(id: string, p: { title: string; what: string; why: string; change: string; isPublic: boolean; articleId: string }): Promise<ActionResult> { await requirePermission('article.publish'); if (p.title.trim().length < 5 || p.what.trim().length < 20) return { ok: false, message: 'Servono titolo e racconto dei fatti.' }; await addRecord('postmortem', { id: id || uid('pm'), status: p.isPublic ? 'approved' : 'open', data: { title: p.title.trim().slice(0, 140), what: p.what.trim().slice(0, 4000), why: p.why.trim().slice(0, 4000), change: p.change.trim().slice(0, 4000), articleId: p.articleId.trim().slice(0, 40) } }); revalidatePath('/come-abbiamo-sbagliato'); revalidatePath('/admin/metodo'); return { ok: true, message: p.isPublic ? 'Post-mortem salvato e pubblicato.' : 'Post-mortem salvato (interno).' }; }
export async function postmortemDeleteAction(id: string): Promise<ActionResult> { await requirePermission('article.publish'); const r = await findRecord(id); if (!r || r.kind !== 'postmortem') return { ok: false, message: 'Non trovato.' }; await deleteRecord(id); revalidatePath('/come-abbiamo-sbagliato'); revalidatePath('/admin/metodo'); return { ok: true, message: 'Eliminato.' }; }
/** Turni e reperibilità. */
export async function shiftSaveAction(date: string, userId: string, kind: 'turno' | 'reperibile', note: string): Promise<ActionResult> { await requirePermission('article.assign'); if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !userId) return { ok: false, message: 'Servono data e persona.' }; await addRecord('shift', { id: `shift_${date}_${kind}_${userId}`.slice(0, 120), status: 'approved', data: { date, userId, kind, note: note.slice(0, 120) } }); revalidatePath('/admin/turni'); return { ok: true, message: 'Turno salvato.' }; }
export async function shiftDeleteAction(id: string): Promise<ActionResult> { await requirePermission('article.assign'); await deleteRecord(id); revalidatePath('/admin/turni'); return { ok: true, message: 'Turno tolto.' }; }
export interface Dossier { title: string; slug: string; tagId: string; people: string; timeline: string; docs: string; notes: string; summary?: string; status: 'aperto' | 'fermo' | 'chiuso' }
/** Fascicolo della vicenda: documenti, cronologia, persone, con un riassunto AI quando serve. Solo interno. */
export async function dossierSaveAction(id: string, d: Dossier): Promise<ActionResult> { const u = await requireUser(); if (d.title.trim().length < 3) return { ok: false, message: 'Serve un titolo.' }; const prev = id ? await findRecord<Dossier>(id) : undefined; await addRecord('dossier', { id: id || uid('dos'), owner: prev?.owner ?? u.id, status: 'open', data: { ...d, title: d.title.trim().slice(0, 160), people: d.people.slice(0, 6000), timeline: d.timeline.slice(0, 12000), docs: d.docs.slice(0, 6000), notes: d.notes.slice(0, 12000), summary: prev?.data.summary } }); revalidatePath('/admin/fascicoli'); return { ok: true, message: 'Fascicolo salvato.' }; }
export async function dossierDeleteAction(id: string): Promise<ActionResult> { await requirePermission('article.publish'); const r = await findRecord(id); if (!r || r.kind !== 'dossier') return { ok: false, message: 'Non trovato.' }; await deleteRecord(id); revalidatePath('/admin/fascicoli'); return { ok: true, message: 'Eliminato.' }; }
export async function dossierSummaryAction(id: string): Promise<ActionResult> { await requireUser(); const r = await findRecord<Dossier>(id); if (!r || r.kind !== 'dossier') return { ok: false, message: 'Non trovato.' }; if (!(await aiAvailable())) return { ok: false, message: 'Assistente AI non attivo.' }; const arts = r.data.tagId ? await repo.listArticles({ tagId: r.data.tagId, includeCircles: true }, 'published', 15) : []; try { const text = await ask(`Sei l'archivista di una redazione. Riassumi in 10-15 righe lo stato di questa vicenda per un collega che la prende in mano: cosa è accertato, cosa è aperto, chi sono le persone chiave, quali documenti contano. Non inventare.\n\nTITOLO: ${r.data.title}\nPERSONE:\n${r.data.people}\nCRONOLOGIA:\n${r.data.timeline}\nDOCUMENTI:\n${r.data.docs}\nNOTE:\n${clip(r.data.notes, 6000)}\n\nARTICOLI USCITI:\n${arts.map((a) => `- ${(a.publishedAt ?? '').slice(0, 10)} ${a.title}: ${clip(stripHtml(a.content), 400)}`).join('\n')}`, { maxTokens: 900, action: 'fascicolo' }); await updateRecord(id, { data: { ...r.data, summary: text.trim() } }); revalidatePath('/admin/fascicoli'); return { ok: true, message: 'Riassunto aggiornato.' }; } catch (e) { return { ok: false, message: (e as Error).message }; } }
export async function dossiersAction(): Promise<{ id: string; title: string }[]> { await requireUser(); return (await listRecords<Dossier>('dossier', { limit: 200 })).map((r) => ({ id: r.id, title: r.data.title })); }
