'use server';

import { revalidatePath, revalidateTag } from 'next/cache';
import { requirePermission, requireUser } from './auth';
import * as repo from './repo';
import { getSettings } from './queries';
import { addRecord, deleteRecord, findRecord } from './records';
import { CARD_KINDS, cardId, cardSlug, parsePoints } from './civic';
import { uid } from './utils';
import type { CivicSettings } from './models';
import type { ActionResult } from './actions';

const touch = (kind?: string) => { revalidatePath('/schede', 'layout'); revalidatePath('/citta'); revalidatePath('/consiglio'); revalidatePath('/elezioni'); revalidatePath('/admin/schede'); if (kind) revalidatePath(`/schede/${kind}`, 'layout'); };
export async function saveCardAction(c: { id?: string; kind: string; title: string; slug?: string; fields: Record<string, string>; body: string; tagId: string; image: string }): Promise<ActionResult & { id?: string }> {
  await requirePermission('article.publish'); const def = CARD_KINDS[c.kind]; if (!def) return { ok: false, message: 'Tipo di scheda sconosciuto.' }; const title = c.title.trim(); if (title.length < 2) return { ok: false, message: 'Serve un titolo.' };
  const slug = cardSlug(c.slug || title); if (!slug) return { ok: false, message: 'Titolo non valido.' }; const id = c.id || cardId(c.kind, slug); const fields: Record<string, string> = {};
  for (const f of def.fields) { const v = String(c.fields?.[f.key] ?? '').trim(); if (!v) continue; if (f.type === 'url' && !/^https?:\/\//.test(v)) return { ok: false, message: `${f.label}: serve un indirizzo completo.` }; if (f.type === 'select' && f.options && !f.options.includes(v)) return { ok: false, message: `${f.label}: scegli una voce dell'elenco.` }; fields[f.key] = v.slice(0, f.type === 'textarea' ? 6000 : 300); }
  await addRecord('card', { id, status: 'approved', data: { kind: c.kind, slug, title: title.slice(0, 160), fields, body: (c.body ?? '').slice(0, 20000), tagId: (c.tagId ?? '').slice(0, 60), image: /^https?:\/\//.test(c.image ?? '') ? c.image.slice(0, 400) : '' } }); touch(c.kind); return { ok: true, message: `${def.name} salvata: /schede/${c.kind}/${slug}`, id };
}
export async function deleteCardAction(id: string): Promise<ActionResult> { await requirePermission('article.publish'); const r = await findRecord(id); if (!r || r.kind !== 'card') return { ok: false, message: 'Scheda non trovata.' }; await deleteRecord(id); touch(); return { ok: true, message: 'Scheda eliminata.' }; }
export async function addCardEventAction(cardId_: string, date: string, text: string, image = ''): Promise<ActionResult> { const u = await requireUser(); const r = await findRecord(cardId_); if (!r || r.kind !== 'card' || !date || text.trim().length < 3) return { ok: false, message: 'Serve una data e un testo.' }; await addRecord('card-event', { ref: cardId_, owner: u.id, data: { date: date.slice(0, 10), text: text.trim().slice(0, 600), image: /^https?:\/\//.test(image) ? image : '', by: u.name } }); touch(); return { ok: true, message: 'Voce aggiunta alla linea del tempo.' }; }
/** Impegni della giunta e di un candidato: come le promesse ai lettori, ma riferite alla scheda. */
export async function cardCommitmentAction(cardId_: string, kind: 'promise' | 'prediction', text: string, dueAt: string, who = ''): Promise<ActionResult> { const u = await requireUser(); const r = await findRecord<{ title: string }>(cardId_); if (!r || r.kind !== 'card') return { ok: false, message: 'Scheda non trovata.' }; if (text.trim().length < 8 || !dueAt) return { ok: false, message: 'Scrivi l\'impegno e scegli una data.' }; await addRecord(kind, { ref: cardId_, owner: u.id, dueAt: new Date(dueAt).toISOString(), data: { text: text.trim().slice(0, 400), who: who.trim().slice(0, 120) || r.data.title, title: r.data.title } }); touch(); revalidatePath('/admin/fiducia'); return { ok: true, message: 'Impegno registrato: alla scadenza compare in Fiducia.' }; }
export async function saveSeriesAction(s: { key: string; label: string; unit: string; source: string; points: string }): Promise<ActionResult> {
  await requirePermission('article.publish'); const key = cardSlug(s.key).replace(/-/g, '_').slice(0, 40); if (!key || !s.label.trim()) return { ok: false, message: 'Servono chiave ed etichetta.' }; const points = parsePoints(s.points); if (!points.length) return { ok: false, message: 'Nessun punto valido: una riga per rilevazione, «AAAA-MM-GG;valore».' };
  const byDate = new Map(points.map((p) => [p.d, p])); await addRecord('series', { id: `ser_${key}`, status: 'approved', data: { key, label: s.label.trim().slice(0, 80), unit: s.unit.trim().slice(0, 20), source: s.source.trim().slice(0, 200), points: [...byDate.values()].sort((a, b) => a.d.localeCompare(b.d)).slice(-2000), updatedAt: new Date().toISOString() } }); touch(); revalidatePath('/admin/dati-civici'); return { ok: true, message: `Serie «${s.label}» salvata con ${byDate.size} rilevazioni.` };
}
export async function deleteSeriesAction(key: string): Promise<ActionResult> { await requirePermission('article.publish'); await deleteRecord(`ser_${key}`); touch(); revalidatePath('/admin/dati-civici'); return { ok: true, message: 'Serie eliminata.' }; }
export async function saveCivicSettingsAction(c: CivicSettings): Promise<ActionResult> { await requirePermission('settings.manage'); const s = await getSettings(); await repo.saveSettingsRow({ ...s, civic: { budget: (c.budget ?? '').slice(0, 200000), basketItems: (c.basketItems ?? '').slice(0, 2000), busLines: (c.busLines ?? '').slice(0, 500), electionTitle: (c.electionTitle ?? '').slice(0, 120), councilUrl: /^https?:\/\//.test(c.councilUrl ?? '') ? c.councilUrl : '' } }); revalidateTag('settings', 'max'); touch(); revalidatePath('/admin/dati-civici'); return { ok: true, message: 'Dati civici salvati.' }; }
/** Fact-check in diretta: un'affermazione, il minuto del video, il verdetto. Compare nell'articolo live collegata al minuto. */
export async function addFactcheckAction(articleId: string, f: { minute: string; claim: string; verdict: string; note: string; source: string }): Promise<ActionResult> {
  const u = await requireUser(); const a = await repo.findArticle(articleId); if (!a) return { ok: false, message: 'Salva prima l\'articolo.' }; const verdicts = ['Vero', 'Falso', 'Impreciso', 'Da verificare', 'Fuori contesto']; if (!verdicts.includes(f.verdict) || f.claim.trim().length < 8) return { ok: false, message: 'Servono l\'affermazione e un verdetto.' };
  await addRecord('factcheck', { ref: articleId, owner: u.id, data: { minute: f.minute.trim().slice(0, 8), claim: f.claim.trim().slice(0, 400), verdict: f.verdict, note: f.note.trim().slice(0, 600), source: /^https?:\/\//.test(f.source) ? f.source.slice(0, 300) : '' } }); const cats = await (await import('./queries')).getCategories(); revalidatePath(`/${cats.find((c) => c.id === a.categoryId)?.slug ?? 'notizie'}/${a.slug}`); return { ok: true, message: 'Verifica aggiunta.' };
}
export async function deleteFactcheckAction(id: string): Promise<ActionResult> { await requireUser(); const r = await findRecord(id); if (!r || r.kind !== 'factcheck') return { ok: false, message: 'Non trovata.' }; await deleteRecord(id); return { ok: true, message: 'Eliminata.' }; }
export async function factchecksAction(articleId: string): Promise<{ id: string; minute: string; claim: string; verdict: string }[]> { await requireUser(); const { factchecksFor } = await import('./civic-data'); return (await factchecksFor(articleId)).map((f) => ({ id: f.id, minute: f.minute, claim: f.claim, verdict: f.verdict })); }
export async function cardsListAction(): Promise<{ id: string; kind: string; title: string }[]> { await requireUser(); const { listCards } = await import('./civic-data'); return (await listCards()).map((c) => ({ id: c.id, kind: c.kind, title: c.title })); }
