'use server';

import { revalidatePath, revalidateTag } from 'next/cache';
import { requirePermission, requireUser } from './auth';
import { aiAvailable, ask, askJson, clip } from './ai';
import * as repo from './repo';
import { getCategories, getSettings, search } from './queries';
import { guardRate } from './ratelimit';
import { addRecord, deleteRecord, findRecord, listRecords, updateRecord } from './records';
import { slugify, stripHtml, uid } from './utils';
import type { Article, PersonalSettings } from './models';
import type { ActionResult } from './actions';

const touch = () => { revalidateTag('settings', 'max'); revalidatePath('/', 'layout'); };
export async function savePersonalAction(p: PersonalSettings): Promise<ActionResult> {
  await requirePermission('settings.manage'); const s = await getSettings(); const cur = s.personal ?? {};
  const seasons = (p.seasons ?? []).filter((x) => x.name.trim() && x.from && x.to).slice(0, 12).map((x) => ({ id: x.id || uid('ss'), name: x.name.trim().slice(0, 60), from: x.from, to: x.to, accent: /^#[0-9a-f]{6}$/i.test(x.accent ?? '') ? x.accent : undefined, brand: /^#[0-9a-f]{6}$/i.test(x.brand ?? '') ? x.brand : undefined, banner: (x.banner ?? '').slice(0, 200), mourning: !!x.mourning }));
  const legacy = p.legacy ? { enabled: !!p.legacy.enabled, days: Math.min(1825, Math.max(60, Math.round(p.legacy.days) || 365)), action: p.legacy.action, heirName: p.legacy.heirName.trim().slice(0, 100), heirEmail: p.legacy.heirEmail.trim().toLowerCase().slice(0, 160), message: p.legacy.message.slice(0, 2000), triggeredAt: p.legacy.enabled ? cur.legacy?.triggeredAt : undefined } : undefined;
  if (legacy?.enabled && legacy.action !== 'freeze' && !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(legacy.heirEmail)) return { ok: false, message: 'Per affidare o archiviare serve l\'email della persona di fiducia.' };
  const next: PersonalSettings = { ...cur, seasons, legacy, autoHome: !!p.autoHome, memory: !!p.memory, ownerChatId: (p.ownerChatId ?? '').replace(/[^\d-]/g, '').slice(0, 20), silence: p.silence?.until ? { until: p.silence.until, message: p.silence.message.slice(0, 300) } : undefined, eventMode: p.eventMode?.title ? { enabled: !!p.eventMode.enabled, title: p.eventMode.title.slice(0, 120), intro: p.eventMode.intro.slice(0, 600), tagId: p.eventMode.tagId, until: p.eventMode.until } : undefined };
  await repo.saveSettingsRow({ ...s, personal: next }); touch(); return { ok: true, message: 'Salvato.' };
}
/** Pagina «adesso». */
export async function saveNowAction(now: Record<string, string>): Promise<ActionResult> { await requirePermission('settings.manage'); const clean = Object.fromEntries(Object.entries(now).filter(([k, v]) => ['reading', 'writing', 'listening', 'watching', 'place', 'note'].includes(k) && v.trim()).map(([k, v]) => [k, v.trim().slice(0, 400)])); await addRecord('now', { id: 'now_main', status: 'approved', data: { ...clean, updatedAt: new Date().toISOString() } }); revalidatePath('/adesso'); return { ok: true, message: 'Pagina «adesso» aggiornata.' }; }
/** Pagina «usa questo»: consigli con la data dell'ultima conferma. */
export async function saveUseAction(id: string, u: { name: string; kind: string; url: string; note: string }): Promise<ActionResult> { await requirePermission('article.publish'); if (u.name.trim().length < 2) return { ok: false, message: 'Dai un nome.' }; await addRecord('uses', { id: id || uid('use'), status: 'approved', data: { name: u.name.trim().slice(0, 100), kind: u.kind.trim().slice(0, 40) || 'Strumenti', url: /^https?:\/\//.test(u.url) ? u.url.slice(0, 300) : '', note: u.note.trim().slice(0, 300), confirmedAt: new Date().toISOString() } }); revalidatePath('/uso'); revalidatePath('/admin/personale'); return { ok: true, message: 'Salvato e confermato oggi.' }; }
export async function confirmUseAction(id: string): Promise<ActionResult> { await requirePermission('article.publish'); const r = await findRecord<Record<string, string>>(id); if (!r) return { ok: false, message: 'Voce non trovata.' }; await updateRecord(id, { data: { ...r.data, confirmedAt: new Date().toISOString() } }); revalidatePath('/uso'); revalidatePath('/admin/personale'); return { ok: true, message: 'Confermato: lo consigli ancora.' }; }
export async function deletePersonalRecordAction(id: string): Promise<ActionResult> { await requirePermission('article.publish'); const r = await findRecord(id); if (!r || !['uses', 'collection', 'letters'].includes(r.kind)) return { ok: false, message: 'Voce non trovata.' }; await deleteRecord(id); revalidatePath('/admin/personale'); revalidatePath('/uso'); revalidatePath('/raccolte'); return { ok: true, message: 'Eliminato.' }; }
/** Raccolte automatiche: una frase descrive il tema, gli articoli si trovano da soli (ricerca semantica se attiva, altrimenti testuale). */
export interface Collection { slug: string; title: string; query: string; intro: string; evolution?: string }
export async function collectionArticles(query: string, limit = 60): Promise<Article[]> {
  const seen = new Map<string, Article>(); try { const { embeddingsEnabled, semanticSearch } = await import('./embeddings'); if (await embeddingsEnabled()) for (const a of await semanticSearch(query, 30)) if (a.status === 'published' && !a.extra?.circle) seen.set(a.id, a); } catch { /* ricerca semantica non attiva */ }
  for (const term of query.split(/[,;]|\s+e\s+/).map((t) => t.trim()).filter((t) => t.length >= 3).slice(0, 6)) for (const a of (await search(term, 40)).items) if (!seen.has(a.id)) seen.set(a.id, a);
  return [...seen.values()].sort((a, b) => (a.publishedAt ?? '').localeCompare(b.publishedAt ?? '')).slice(0, limit);
}
export async function saveCollectionAction(id: string, c: Collection): Promise<ActionResult> { await requirePermission('article.publish'); if (c.title.trim().length < 3 || c.query.trim().length < 3) return { ok: false, message: 'Servono un titolo e le parole del tema.' }; const n = (await collectionArticles(c.query)).length; if (n === 0) return { ok: false, message: 'Nessun articolo trovato con queste parole: prova a cambiarle.' }; const prev = id ? await findRecord<Collection>(id) : undefined; await addRecord('collection', { id: id || uid('col'), status: 'approved', data: { slug: slugify(c.slug || c.title).slice(0, 60), title: c.title.trim().slice(0, 100), query: c.query.trim().slice(0, 200), intro: c.intro.trim().slice(0, 500), evolution: prev?.data.evolution } }); revalidatePath('/raccolte'); revalidatePath('/admin/personale'); return { ok: true, message: `Raccolta salvata: ${n} articoli trovati da soli.` }; }
/** Grafo delle idee: come è cambiato nel tempo quello che scrivi su un tema. Lo prepara l'AI leggendo solo i tuoi testi, e lo puoi correggere. */
export async function evolutionAction(id: string): Promise<ActionResult> {
  await requirePermission('article.publish'); const r = await findRecord<Collection>(id); if (!r) return { ok: false, message: 'Raccolta non trovata.' }; if (!(await aiAvailable())) return { ok: false, message: 'Assistente AI non attivo.' }; const arts = await collectionArticles(r.data.query, 25); if (arts.length < 3) return { ok: false, message: 'Servono almeno tre articoli per vedere un\'evoluzione.' };
  try { const text = await ask(`Questi sono estratti, in ordine di data, di ciò che lo stesso autore ha scritto sul tema «${r.data.title}». Descrivi in 4-6 frasi come sono cambiati nel tempo il tono, le posizioni e le domande, citando gli anni. Non giudicare, non inventare: se non c'è cambiamento, dillo.\n\n${arts.map((a) => `[${(a.publishedAt ?? '').slice(0, 10)}] ${a.title}: ${clip(stripHtml(a.content), 600)}`).join('\n\n')}`, { maxTokens: 500, action: 'evoluzione-idee' }); await updateRecord(id, { data: { ...r.data, evolution: text.trim() } }); revalidatePath('/raccolte'); revalidatePath('/admin/personale'); return { ok: true, message: 'Evoluzione scritta: rileggila nella pagina della raccolta.' }; } catch (e) { return { ok: false, message: (e as Error).message }; }
}
/** Corrispondenza pubblica: uno scambio di lettere tra due blog impaginato come un pezzo solo. */
export interface Correspondence { slug: string; title: string; intro: string; withName: string; withUrl: string; letters: { from: 'me' | 'them'; date: string; text: string; url?: string }[] }
export async function saveCorrespondenceAction(id: string, c: Correspondence): Promise<ActionResult> { await requirePermission('article.publish'); const letters = c.letters.filter((l) => l.text.trim().length > 20).slice(0, 40).map((l) => ({ from: l.from, date: l.date, text: l.text.trim().slice(0, 20000), url: /^https?:\/\//.test(l.url ?? '') ? l.url : undefined })); if (c.title.trim().length < 3 || !c.withName.trim() || letters.length < 1) return { ok: false, message: 'Servono un titolo, il nome dell\'altra persona e almeno una lettera.' }; await addRecord('letters', { id: id || uid('ltr'), status: 'approved', data: { slug: slugify(c.slug || c.title).slice(0, 60), title: c.title.trim().slice(0, 120), intro: c.intro.trim().slice(0, 500), withName: c.withName.trim().slice(0, 80), withUrl: /^https?:\/\//.test(c.withUrl) ? c.withUrl : '', letters } }); revalidatePath('/corrispondenze'); revalidatePath('/admin/personale'); return { ok: true, message: 'Corrispondenza salvata.' }; }
/** Un anno fa oggi: rispondi al te stesso di allora. Crea una bozza collegata al vecchio post. */
export async function replyToPastAction(articleId: string): Promise<ActionResult & { id?: string }> {
  const u = await requireUser(); const old = await repo.findArticle(articleId); if (!old) return { ok: false, message: 'Articolo non trovato.' }; const now = new Date().toISOString(); const id = uid('a'); const title = `Rileggendo «${old.title}»`;
  await repo.upsertArticle({ ...old, id, slug: `${slugify(title).slice(0, 70)}-${id.slice(-4)}`, title, subtitle: '', excerpt: '', kicker: 'Riletto oggi', content: `<blockquote><p>${stripHtml(old.content).slice(0, 400)}…</p></blockquote><p></p>`, coverImage: '', coverCaption: '', authorId: u.id, status: 'draft', featured: false, breaking: false, sponsored: false, views: 0, publishedAt: null, scheduledAt: null, createdAt: now, updatedAt: now, gallery: [], liveUpdates: [], liveActive: false, seo: { title: '', description: '', canonical: '', noIndex: false }, extra: { replyTo: old.id } });
  return { ok: true, message: 'Bozza creata.', id };
}
/** Tipi di contenuto descritti a parole: l'AI propone sezione, campi e modello; tu confermi e il CMS li crea. */
export interface TypeProposal { name: string; fields: { key: string; label: string; type: 'text' | 'number' | 'rating' | 'url' | 'date' }[]; template: string }
export async function proposeTypeAction(description: string): Promise<ActionResult & { data?: TypeProposal }> {
  await requirePermission('settings.manage'); if (description.trim().length < 12) return { ok: false, message: 'Descrivi cosa vuoi pubblicare.' }; if (!(await aiAvailable())) return { ok: false, message: 'Assistente AI non attivo.' };
  try { const d = await askJson<TypeProposal>(`Un autore descrive un tipo di contenuto che vuole pubblicare sul suo sito: «${clip(description, 600)}».\nProponi: "name" (nome della sezione, 1-3 parole), "fields" (3-7 campi strutturati: "key" minuscola senza spazi, "label" in italiano, "type" tra text, number, rating, url, date), "template" (HTML di partenza per il testo libero, con 2-4 <h2> e paragrafi segnaposto tra parentesi quadre).\nJSON: {"name":"...","fields":[...],"template":"..."}`, { maxTokens: 1200, action: 'tipo-contenuto' });
    const types = ['text', 'number', 'rating', 'url', 'date']; return { ok: true, data: { name: String(d.name ?? '').slice(0, 40), fields: (d.fields ?? []).slice(0, 8).map((f) => ({ key: slugify(String(f.key)).replace(/-/g, '_').slice(0, 24), label: String(f.label).slice(0, 40), type: (types.includes(f.type) ? f.type : 'text') as TypeProposal['fields'][number]['type'] })).filter((f) => f.key), template: String(d.template ?? '').slice(0, 3000) } }; } catch (e) { return { ok: false, message: (e as Error).message }; }
}
export async function createTypeAction(p: TypeProposal): Promise<ActionResult> {
  await requirePermission('settings.manage'); const name = p.name.trim(); if (name.length < 2 || !p.fields.length) return { ok: false, message: 'Proposta incompleta.' }; const cats = await getCategories(); if (cats.some((c) => c.slug === slugify(name))) return { ok: false, message: 'Esiste già una sezione con questo nome.' };
  const base = cats[0]; const id = uid('c'); await repo.upsertCategory({ id, slug: slugify(name), name, kind: 'standard', color: base?.color ?? '#22418f', description: '', order: cats.length + 1, showInMenu: true, showOnHome: false });
  const s = await getSettings(); await repo.saveSettingsRow({ ...s, customFields: { ...(s.customFields ?? {}), [id]: p.fields as never }, typeTemplates: { ...((s as { typeTemplates?: Record<string, string> }).typeTemplates ?? {}), [id]: p.template } } as typeof s); revalidateTag('categories', 'max'); touch();
  return { ok: true, message: `Creata la sezione «${name}» con ${p.fields.length} campi e la sua tabella in /dati/${slugify(name)}.` };
}
/** Libro degli ospiti: un messaggio scritto a mano sul touch, sempre moderato. */
export async function signGuestbookAction(name: string, image: string): Promise<ActionResult> {
  if (await guardRate('ospiti', 2, 3_600_000)) return { ok: false, message: 'Hai già firmato da poco. Grazie!' }; if (!image.startsWith('data:image/png;base64,') || image.length < 2000 || image.length > 260_000) return { ok: false, message: 'Scrivi qualcosa nel riquadro (non troppo fitto).' };
  await addRecord('guestbook', { status: 'pending', data: { name: name.trim().slice(0, 60) || 'Anonimo', image } }); return { ok: true, message: 'Grazie! Il tuo messaggio compare dopo uno sguardo dell\'autore.' };
}
export async function nowData() { return (await findRecord<Record<string, string>>('now_main'))?.data ?? null; }
export async function personalLists() { const [uses, collections, letters] = await Promise.all([listRecords<Record<string, string>>('uses', { limit: 200, order: 'old' }), listRecords<Collection>('collection', { limit: 100, order: 'old' }), listRecords<Correspondence>('letters', { limit: 100 })]); return { uses, collections, letters }; }
