import type { ArticleFormat } from './models';

/** Modelli di articolo con struttura guidata: precompilano occhiello, formato, campi e blocchi. */
export interface ArticleTemplate { id: string; name: string; description: string; kicker: string; format: ArticleFormat; content: string; fields?: Record<string, string> }
export const ARTICLE_TEMPLATES: ArticleTemplate[] = [
  { id: 'intervista', name: 'Intervista', description: 'Presentazione, domande in grassetto e risposte.', kicker: 'L\'intervista', format: 'standard', content: '<p><i>Chi è l\'intervistato e perché lo sentiamo oggi (2-3 righe).</i></p>\n<p><b>Prima domanda?</b></p>\n<p>«Risposta».</p>\n<p><b>Seconda domanda?</b></p>\n<p>«Risposta».</p>\n<div class="box box-info"><b>Chi è</b><p>Breve scheda biografica.</p></div>' },
  { id: 'recensione', name: 'Recensione', description: 'Giudizio, pro e contro, scheda e punteggio.', kicker: 'La recensione', format: 'standard', content: '<p>Il giudizio in due righe.</p>\n<h2>Cosa funziona</h2>\n<ul><li>Punto di forza</li><li>Punto di forza</li></ul>\n<h2>Cosa non funziona</h2>\n<ul><li>Limite</li></ul>\n<h2>Il verdetto</h2>\n<p>Conclusione.</p>', fields: { punteggio: '4', prezzo: '', luogo: '' } },
  { id: 'live', name: 'Diretta', description: 'Cronaca in tempo reale con aggiornamenti orari.', kicker: 'La diretta', format: 'live', content: '<p>Cosa sta succedendo e perché conta. Gli aggiornamenti vanno nel pannello «Diretta» a destra.</p>\n<div class="know-box"><div class="know-yes"><b>Cosa sappiamo</b><ul><li>…</li></ul></div><div class="know-no"><b>Cosa non sappiamo</b><ul><li>…</li></ul></div></div>' },
  { id: 'evento', name: 'Scheda evento', description: 'Quando, dove, quanto costa, come arrivare.', kicker: 'Cosa fare', format: 'standard', content: '<p>Di cosa si tratta, in due righe.</p>\n<div class="box box-info"><b>Le informazioni utili</b><p><b>Quando:</b> …<br /><b>Dove:</b> …<br /><b>Biglietti:</b> …<br /><b>Come arrivare:</b> …</p></div>\n<h2>Il programma</h2>\n<ul><li>…</li></ul>', fields: { luogo: '', prezzo: '', data: '' } },
  { id: 'spiegone', name: 'Spiegone', description: 'Domande e risposte per capire un tema complesso.', kicker: 'Per capire', format: 'standard', content: '<p>Perché se ne parla, in tre righe.</p>\n<h2>Cosa è successo</h2>\n<p>…</p>\n<h2>Perché è importante</h2>\n<p>…</p>\n<h2>Cosa succede adesso</h2>\n<p>…</p>' },
  { id: 'breaking', name: 'Ultim\'ora', description: 'Notizia in aggiornamento con quadro certo/incerto.', kicker: 'Ultim\'ora', format: 'standard', content: '<p>Il fatto, in una frase.</p>\n<div class="know-box"><div class="know-yes"><b>Cosa sappiamo</b><ul><li>…</li></ul></div><div class="know-no"><b>Cosa non sappiamo</b><ul><li>…</li></ul></div></div>\n<p><i>Notizia in aggiornamento.</i></p>' },
];
