/** Politica locale e dati civici: schede (candidati, delibere, cantieri, bandi, negozi…), serie di dati, bilancio, bussola, voti. Solo funzioni pure. */
export interface CardField { key: string; label: string; type: 'text' | 'textarea' | 'number' | 'date' | 'url' | 'select'; options?: string[]; hint?: string }
export interface CardKindDef { name: string; plural: string; icon: string; fields: CardField[]; hint: string; group: 'politica' | 'citta' | 'economia' | 'memoria' | 'emergenza' }
export const CARD_KINDS: Record<string, CardKindDef> = {
  candidato: { name: 'Candidato', plural: 'Candidati', icon: '🗳️', group: 'politica', hint: 'Una pagina per candidato: promesse tracciate nel tempo, posizioni verificate, confronto senza retorica.', fields: [{ key: 'lista', label: 'Lista', type: 'text' }, { key: 'ruolo', label: 'Candidato a', type: 'select', options: ['Sindaco', 'Consiglio comunale', 'Presidente di municipio', 'Altro'] }, { key: 'foto', label: 'Foto (URL)', type: 'url' }, { key: 'programma', label: 'Programma (URL)', type: 'url' }, { key: 'posizioni', label: 'Posizioni sui temi', type: 'textarea', hint: 'Una per riga: tema: posizione in una frase (fonte)' }, { key: 'risposte', label: 'Risposte alla bussola', type: 'textarea', hint: 'Una per riga: slug-del-tema=si|no|forse' }] },
  tema: { name: 'Tema della bussola', plural: 'Temi della bussola', icon: '🧭', group: 'politica', hint: 'Le domande a cui rispondono candidati e lettori.', fields: [{ key: 'domanda', label: 'Domanda (sì/no)', type: 'text' }, { key: 'spiegazione', label: 'Spiegazione breve', type: 'textarea' }] },
  giunta: { name: 'Giunta', plural: 'Giunte', icon: '🏛️', group: 'politica', hint: 'Il programma spezzato in impegni verificabili, con scadenza.', fields: [{ key: 'mandato', label: 'Mandato', type: 'text', hint: 'es. 2024-2029' }, { key: 'sindaco', label: 'Sindaco', type: 'text' }, { key: 'programma', label: 'Programma (URL)', type: 'url' }] },
  delibera: { name: 'Delibera', plural: 'Delibere', icon: '📜', group: 'politica', hint: 'Ogni delibera citata diventa una scheda con voti e assenti.', fields: [{ key: 'numero', label: 'Numero', type: 'text' }, { key: 'data', label: 'Data', type: 'date' }, { key: 'oggetto', label: 'Oggetto', type: 'textarea' }, { key: 'esito', label: 'Esito', type: 'select', options: ['Approvata', 'Respinta', 'Rinviata'] }, { key: 'voti', label: 'Voti nominali', type: 'textarea', hint: 'Una riga per consigliere: Nome Cognome: favorevole|contrario|astenuto|assente' }, { key: 'testo', label: 'Testo integrale (URL)', type: 'url' }] },
  odg: { name: 'Punto all\'ordine del giorno', plural: 'Ordine del giorno', icon: '📋', group: 'politica', hint: 'Il consiglio tradotto in italiano semplice, con «perché ti riguarda».', fields: [{ key: 'seduta', label: 'Data della seduta', type: 'date' }, { key: 'ufficiale', label: 'Titolo ufficiale', type: 'textarea' }, { key: 'spiegazione', label: 'In parole semplici', type: 'textarea' }, { key: 'riguarda', label: 'Perché ti riguarda', type: 'textarea' }] },
  seggio: { name: 'Seggio', plural: 'Seggi', icon: '🗺️', group: 'politica', hint: 'Risultati per sezione, con la storia delle elezioni precedenti.', fields: [{ key: 'numero', label: 'Numero sezione', type: 'text' }, { key: 'indirizzo', label: 'Indirizzo', type: 'text' }, { key: 'elezione', label: 'Elezione', type: 'text', hint: 'es. Comunali 2026' }, { key: 'elettori', label: 'Elettori', type: 'number' }, { key: 'votanti', label: 'Votanti', type: 'number' }, { key: 'risultati', label: 'Risultati', type: 'textarea', hint: 'Una riga per lista: Nome lista: voti' }] },
  cantiere: { name: 'Cantiere', plural: 'Cantieri', icon: '🚧', group: 'citta', hint: 'Opere pubbliche con promessa di fine e giorni di ritardo contati.', fields: [{ key: 'opera', label: 'Opera', type: 'text' }, { key: 'via', label: 'Dove', type: 'text' }, { key: 'inizio', label: 'Inizio', type: 'date' }, { key: 'fine_prevista', label: 'Fine promessa', type: 'date' }, { key: 'fine_effettiva', label: 'Fine effettiva', type: 'date' }, { key: 'importo', label: 'Importo (€)', type: 'number' }, { key: 'ditta', label: 'Ditta', type: 'text' }, { key: 'stato', label: 'Stato', type: 'select', options: ['In corso', 'Fermo', 'Concluso', 'Non iniziato'] }] },
  bando: { name: 'Bando', plural: 'Bandi e gare', icon: '📑', group: 'citta', hint: 'Scadenze, vincitori e ribassi letti da fonti ufficiali.', fields: [{ key: 'oggetto', label: 'Oggetto', type: 'textarea' }, { key: 'ente', label: 'Ente', type: 'text' }, { key: 'scadenza', label: 'Scadenza', type: 'date' }, { key: 'base', label: 'Importo a base d\'asta (€)', type: 'number' }, { key: 'vincitore', label: 'Vincitore', type: 'text' }, { key: 'ribasso', label: 'Ribasso (%)', type: 'number' }, { key: 'url', label: 'Fonte (URL)', type: 'url' }] },
  ztl: { name: 'Zona a traffico limitato', plural: 'Parcheggi e ZTL', icon: '🅿️', group: 'citta', hint: 'Dove, quando, quanto, e le modifiche in arrivo.', fields: [{ key: 'zona', label: 'Zona', type: 'text' }, { key: 'orari', label: 'Orari', type: 'textarea' }, { key: 'costo', label: 'Costo', type: 'text' }, { key: 'modifiche', label: 'Modifiche in arrivo', type: 'textarea' }, { key: 'dal', label: 'In vigore dal', type: 'date' }] },
  scuola: { name: 'Scuola', plural: 'Scuole', icon: '🏫', group: 'citta', hint: 'Dati ufficiali più le voci dei genitori.', fields: [{ key: 'tipo', label: 'Tipo', type: 'select', options: ['Infanzia', 'Primaria', 'Secondaria di primo grado', 'Secondaria di secondo grado'] }, { key: 'indirizzo', label: 'Indirizzo', type: 'text' }, { key: 'iscritti', label: 'Iscritti', type: 'number' }, { key: 'classi', label: 'Classi', type: 'number' }, { key: 'tempo_pieno', label: 'Tempo pieno', type: 'select', options: ['Sì', 'No', 'Parziale'] }, { key: 'mensa', label: 'Mensa', type: 'select', options: ['Sì', 'No'] }, { key: 'url', label: 'Sito (URL)', type: 'url' }] },
  negozio: { name: 'Negozio', plural: 'Negozi e attività', icon: '🏪', group: 'economia', hint: 'Una pagina gratuita per ogni attività, con un avviso al mese.', fields: [{ key: 'categoria', label: 'Categoria', type: 'text' }, { key: 'via', label: 'Indirizzo', type: 'text' }, { key: 'orari', label: 'Orari', type: 'textarea' }, { key: 'telefono', label: 'Telefono', type: 'text' }, { key: 'sito', label: 'Sito (URL)', type: 'url' }, { key: 'stato', label: 'Stato', type: 'select', options: ['Aperto', 'Nuova apertura', 'Chiuso', 'In chiusura'] }, { key: 'dal', label: 'Aperto dal', type: 'date' }, { key: 'chiuso_il', label: 'Chiuso il', type: 'date' }, { key: 'avviso', label: 'Avviso del mese', type: 'textarea' }] },
  persona: { name: 'Persona ricordata', plural: 'Persone ricordate', icon: '🕯️', group: 'memoria', hint: 'Pagina permanente con i ricordi dei lettori e gli articoli.', fields: [{ key: 'nascita', label: 'Nascita', type: 'date' }, { key: 'morte', label: 'Morte', type: 'date' }, { key: 'foto', label: 'Foto (URL)', type: 'url' }, { key: 'chi_era', label: 'Chi era', type: 'textarea' }] },
  toponimo: { name: 'Toponimo', plural: 'Toponimi', icon: '🪧', group: 'memoria', hint: 'Dizionario delle vie con l\'origine del nome.', fields: [{ key: 'origine', label: 'Origine del nome', type: 'textarea' }, { key: 'anno', label: 'Anno dell\'intitolazione', type: 'number' }, { key: 'prima', label: 'Come si chiamava prima', type: 'text' }] },
  documento: { name: 'Documento', plural: 'Catalogo dei documenti', icon: '🗂️', group: 'memoria', hint: 'Ogni PDF citato, archiviato e cercabile.', fields: [{ key: 'url', label: 'File (URL)', type: 'url' }, { key: 'ente', label: 'Ente', type: 'text' }, { key: 'data', label: 'Data', type: 'date' }, { key: 'riassunto', label: 'Di cosa parla', type: 'textarea' }] },
  figura: { name: 'Figura pubblica', plural: 'Chi era chi', icon: '👤', group: 'memoria', hint: 'Ruoli nel tempo, costruiti dall\'archivio.', fields: [{ key: 'ruoli', label: 'Ruoli', type: 'textarea', hint: 'Una riga per ruolo: 2019-2024: assessore ai lavori pubblici' }, { key: 'foto', label: 'Foto (URL)', type: 'url' }] },
  fiume: { name: 'Corso d\'acqua', plural: 'Fiumi e torrenti', icon: '🌊', group: 'emergenza', hint: 'Livello, soglie e storico delle piene.', fields: [{ key: 'stazione', label: 'Stazione di misura', type: 'text' }, { key: 'soglia_attenzione', label: 'Soglia di attenzione (m)', type: 'number' }, { key: 'soglia_allarme', label: 'Soglia di allarme (m)', type: 'number' }, { key: 'serie', label: 'Chiave della serie dati', type: 'text', hint: 'la serie con i livelli idrometrici' }, { key: 'url', label: 'Fonte (URL)', type: 'url' }] },
  punto: { name: 'Punto utile', plural: 'Punti utili', icon: '📍', group: 'emergenza', hint: 'Ricarica, acqua, riparo: dove andare in un blackout o in un\'ondata di calore.', fields: [{ key: 'tipo', label: 'Tipo', type: 'select', options: ['Ricarica telefoni', 'Acqua potabile', 'Luogo climatizzato', 'Punto di raccolta', 'Farmacia di turno', 'Altro'] }, { key: 'indirizzo', label: 'Indirizzo', type: 'text' }, { key: 'orari', label: 'Orari', type: 'text' }, { key: 'note', label: 'Note', type: 'textarea' }] },
};
export interface Card { id: string; kind: string; slug: string; title: string; fields: Record<string, string>; body: string; tagId: string; image: string }
export const cardId = (kind: string, slug: string): string => `card_${kind}_${slug}`.slice(0, 120);
export const cardSlug = (s: string): string => s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60);
/** «chiave: valore» per riga → coppie. Usato per voti, posizioni, risultati, ruoli. */
export const parseLines = (text: string | undefined): { k: string; v: string }[] => (text ?? '').split('\n').map((l) => l.trim()).filter(Boolean).map((l) => { const i = l.indexOf(':'); return i === -1 ? { k: l, v: '' } : { k: l.slice(0, i).trim(), v: l.slice(i + 1).trim() }; });
export type Vote = 'favorevole' | 'contrario' | 'astenuto' | 'assente';
/** Chi ha votato cosa: consigliere × delibera. */
export function councilMatrix(delibere: { id: string; title: string; votes: string }[]): { names: string[]; rows: { name: string; votes: (Vote | '')[] }[] } {
  const norm = (v: string): Vote | '' => { const x = v.toLowerCase(); return x.startsWith('fav') || x === 'sì' || x === 'si' ? 'favorevole' : x.startsWith('contr') || x === 'no' ? 'contrario' : x.startsWith('ast') ? 'astenuto' : x.startsWith('ass') ? 'assente' : ''; };
  const per = delibere.map((d) => new Map(parseLines(d.votes).map(({ k, v }) => [k, norm(v)]))); const names = [...new Set(per.flatMap((m) => [...m.keys()]))].sort((a, b) => a.localeCompare(b, 'it'));
  return { names, rows: names.map((name) => ({ name, votes: per.map((m) => m.get(name) ?? '') })) };
}
/** Bussola locale: quante risposte coincidono con quelle di ogni candidato, in percentuale sulle domande a cui entrambi hanno risposto. */
export function compassScore(answers: Record<string, string>, candidates: { title: string; slug: string; risposte: string }[]): { title: string; slug: string; percent: number; matched: number; total: number }[] {
  return candidates.map((c) => { const theirs = Object.fromEntries((c.risposte ?? '').split('\n').map((l) => l.split('=').map((x) => x.trim().toLowerCase())).filter((p) => p.length === 2 && p[0]) as [string, string][]); let total = 0, matched = 0; for (const [q, a] of Object.entries(answers)) { const t = theirs[q]; if (!t || !a) continue; total++; if (t === a) matched++; else if (t === 'forse' || a === 'forse') matched += 0.5; } return { title: c.title, slug: c.slug, percent: total ? Math.round((matched / total) * 100) : 0, matched: Math.round(matched), total }; }).sort((a, b) => b.percent - a.percent);
}
export function parseResults(text: string | undefined): { list: string; votes: number; percent: number }[] { const rows = parseLines(text).map(({ k, v }) => ({ list: k, votes: Number(String(v).replace(/[^\d]/g, '')) || 0 })); const tot = rows.reduce((n, r) => n + r.votes, 0); return rows.map((r) => ({ ...r, percent: tot ? Math.round((r.votes / tot) * 1000) / 10 : 0 })).sort((a, b) => b.votes - a.votes); }
/** Giorni di ritardo di un cantiere rispetto alla fine promessa (positivo = in ritardo). */
export function delayDays(plannedEnd: string | undefined, actualEnd: string | undefined, nowMs: number): number | null { if (!plannedEnd) return null; const end = actualEnd ? +new Date(actualEnd) : nowMs; return Math.floor((end - +new Date(plannedEnd)) / 86_400_000); }
/** Righe separate da punto e virgola o tabulazione; la virgola vale come separatore solo se non ci sono gli altri (per i decimali italiani serve il punto e virgola). */
const splitRow = (l: string): string[] => (l.includes(';') || l.includes('\t') ? l.split(/[;\t]/) : l.split(',')).map((c) => c.trim());
export interface BudgetNode { name: string; amount: number; children: BudgetNode[] }
/** Bilancio come albero: righe «Anno;Entrate/Uscite;Voce;Sottovoce;Importo». Restituisce gli anni disponibili e l'albero dell'anno scelto. */
export function budgetTree(csv: string, year?: string): { years: string[]; year: string; tree: BudgetNode[]; total: Record<string, number> } {
  const rows = csv.split('\n').map(splitRow).filter((c) => c.length >= 4 && c[0]); const years = [...new Set(rows.map((r) => r[0]))].sort(); const y = year && years.includes(year) ? year : years[years.length - 1] ?? '';
  const tree: BudgetNode[] = []; const total: Record<string, number> = {};
  for (const r of rows.filter((x) => x[0] === y)) { const [, side, voce, sotto, imp] = r.length >= 5 ? r : [r[0], r[1], r[2], '', r[3]]; const amount = Number(String(imp).replace(/\./g, '').replace(',', '.')) || 0; let s = tree.find((n) => n.name === side); if (!s) { s = { name: side, amount: 0, children: [] }; tree.push(s); } let v = s.children.find((n) => n.name === voce); if (!v) { v = { name: voce, amount: 0, children: [] }; s.children.push(v); } if (sotto) v.children.push({ name: sotto, amount, children: [] }); v.amount += amount; s.amount += amount; total[side] = (total[side] ?? 0) + amount; }
  for (const s of tree) s.children.sort((a, b) => b.amount - a.amount); return { years, year: y, tree, total };
}
export interface Point { d: string; v: number }
/** Statistiche di una serie: ultimo valore, media, deviazione, variazione e se l'ultimo dato è fuori dalla norma (oltre 2 deviazioni). */
export function seriesStats(points: Point[]): { last: Point | null; prev: Point | null; mean: number; sd: number; z: number; anomaly: boolean; trend: 'su' | 'giù' | 'stabile'; n: number } {
  const p = [...points].filter((x) => Number.isFinite(x.v) && x.d).sort((a, b) => a.d.localeCompare(b.d)); const n = p.length; if (!n) return { last: null, prev: null, mean: 0, sd: 0, z: 0, anomaly: false, trend: 'stabile', n: 0 };
  const hist = p.slice(0, -1); const base = hist.length >= 4 ? hist : p; const mean = base.reduce((s, x) => s + x.v, 0) / base.length; const sd = Math.sqrt(base.reduce((s, x) => s + (x.v - mean) ** 2, 0) / base.length); const last = p[n - 1]; const prev = p[n - 2] ?? null; const z = sd > 0 ? (last.v - mean) / sd : 0;
  const trend = prev ? (last.v > prev.v * 1.02 ? 'su' : last.v < prev.v * 0.98 ? 'giù' : 'stabile') : 'stabile'; return { last, prev, mean: +mean.toFixed(2), sd: +sd.toFixed(2), z: +z.toFixed(2), anomaly: hist.length >= 4 && Math.abs(z) > 2, trend, n };
}
export const parsePoints = (text: string): Point[] => text.split('\n').map(splitRow).filter((c) => c.length >= 2 && /^\d{4}-\d{2}(-\d{2})?/.test(c[0])).map((c) => ({ d: c[0].length === 7 ? `${c[0]}-01` : c[0], v: Number(c[1].replace(/\./g, '').replace(',', '.')) })).filter((p) => Number.isFinite(p.v));
/** Paniere della spesa: mediana del prezzo per prodotto nella settimana, con confronto alla settimana prima. */
export function basket(entries: { product: string; price: number; date: string }[], weekStart: string): { product: string; median: number; prevMedian: number | null; delta: number | null; samples: number }[] {
  const wk = (d: string) => { const t = new Date(d); const day = (t.getUTCDay() + 6) % 7; t.setUTCDate(t.getUTCDate() - day); return t.toISOString().slice(0, 10); }; const prevWeek = new Date(+new Date(weekStart) - 7 * 86_400_000).toISOString().slice(0, 10);
  const med = (xs: number[]) => { const s = [...xs].sort((a, b) => a - b); return s.length ? s.length % 2 ? s[(s.length - 1) / 2] : (s[s.length / 2 - 1] + s[s.length / 2]) / 2 : 0; };
  const products = [...new Set(entries.map((e) => e.product))]; return products.map((product) => { const now = entries.filter((e) => e.product === product && wk(e.date) === weekStart).map((e) => e.price); const before = entries.filter((e) => e.product === product && wk(e.date) === prevWeek).map((e) => e.price); const m = med(now), pm = before.length ? med(before) : null; return { product, median: +m.toFixed(2), prevMedian: pm === null ? null : +pm.toFixed(2), delta: pm ? +(((m - pm) / pm) * 100).toFixed(1) : null, samples: now.length }; }).filter((x) => x.samples > 0).sort((a, b) => a.product.localeCompare(b.product));
}
/** Ritardi del trasporto pubblico segnalati dai lettori: per linea e fascia oraria. */
export function delayStats(reports: { line: string; time: string; kind: string; minutes: number }[]): { line: string; reports: number; skipped: number; avgDelay: number; worstHour: string }[] {
  const lines = [...new Set(reports.map((r) => r.line))]; return lines.map((line) => { const rs = reports.filter((r) => r.line === line); const delays = rs.filter((r) => r.kind !== 'Corsa saltata').map((r) => r.minutes); const byHour: Record<string, number> = {}; for (const r of rs) { const h = (r.time || '').slice(0, 2) + ':00'; byHour[h] = (byHour[h] ?? 0) + 1; } const worst = Object.entries(byHour).sort((a, b) => b[1] - a[1])[0]?.[0] ?? ''; return { line, reports: rs.length, skipped: rs.filter((r) => r.kind === 'Corsa saltata').length, avgDelay: delays.length ? Math.round(delays.reduce((n, m) => n + m, 0) / delays.length) : 0, worstHour: worst }; }).sort((a, b) => b.reports - a.reports);
}
