/** Comunità: i contributi dei lettori descritti come configurazione (campi, limiti, scadenze), più i conti che servono alle pagine. Solo funzioni pure. */
export interface FieldDef { key: string; label: string; type: 'text' | 'textarea' | 'email' | 'select' | 'number' | 'image'; required?: boolean; min?: number; max: number; options?: string[]; placeholder?: string; private?: boolean }
export interface KindDef { kind: string; title: string; button: string; thanks: string; fields: FieldDef[]; expiresDays?: number; perHour: number; needsReader?: boolean }
export const COMMUNITY: Record<string, KindDef> = {
  skill: { kind: 'skill', title: 'Metti a disposizione quello che sai', button: 'Mi rendo disponibile', thanks: 'Grazie: quando ci servirà un parere nel tuo campo ti scriveremo. Il tuo nome non viene pubblicato.', perHour: 2, fields: [{ key: 'name', label: 'Nome e cognome', type: 'text', required: true, min: 3, max: 100, private: true }, { key: 'email', label: 'Email', type: 'email', required: true, max: 160, private: true }, { key: 'field', label: 'Il tuo campo', type: 'text', required: true, min: 3, max: 80, placeholder: 'es. idraulico, avvocata del lavoro, infermiere di pronto soccorso' }, { key: 'about', label: 'Su cosa puoi aiutarci a capire', type: 'textarea', required: true, min: 20, max: 800 }] },
  log: { kind: 'log', title: 'Aggiungi una riga al taccuino', button: 'Annota', thanks: 'Annotato: compare dopo una verifica a campione della redazione.', perHour: 6, fields: [{ key: 'what', label: 'Cosa', type: 'select', required: true, max: 40, options: ['Lampione spento', 'Buca o marciapiede', 'Nuova apertura', 'Chiusura', 'Rifiuti', 'Verde pubblico', 'Altro'] }, { key: 'where', label: 'Dove (via e punto di riferimento)', type: 'text', required: true, min: 4, max: 140 }, { key: 'text', label: 'Due righe', type: 'textarea', required: true, min: 10, max: 500 }, { key: 'name', label: 'Il tuo nome (facoltativo)', type: 'text', max: 60 }] },
  council: { kind: 'council', title: 'Fai una domanda al Comune', button: 'Metti in coda', thanks: 'Ricevuta. Se la redazione la inoltra, da quel giorno contiamo l\'attesa in pubblico.', perHour: 3, fields: [{ key: 'text', label: 'La domanda, in una frase chiara', type: 'textarea', required: true, min: 20, max: 400 }, { key: 'office', label: 'A chi è rivolta (se lo sai)', type: 'text', max: 100, placeholder: 'es. Assessorato ai lavori pubblici' }, { key: 'name', label: 'Il tuo nome (facoltativo)', type: 'text', max: 60 }] },
  translation: { kind: 'translation', title: 'Traduci questo articolo per la tua comunità', button: 'Invia la traduzione', thanks: 'Grazie! La facciamo rileggere e la pubblichiamo con il tuo nome.', perHour: 2, fields: [{ key: 'lang', label: 'Lingua', type: 'select', required: true, max: 30, options: ['Română', 'Shqip', 'العربية', 'Українська', '中文', 'English', 'Français', 'Español', 'বাংলা', 'Altra'] }, { key: 'title', label: 'Titolo tradotto', type: 'text', required: true, min: 5, max: 200 }, { key: 'text', label: 'Testo tradotto', type: 'textarea', required: true, min: 200, max: 20000 }, { key: 'name', label: 'Il tuo nome', type: 'text', required: true, min: 2, max: 80 }, { key: 'email', label: 'La tua email (resta riservata)', type: 'email', required: true, max: 160, private: true }] },
  memory: { kind: 'memory', title: 'Lascia un ricordo', button: 'Lascia il ricordo', thanks: 'Grazie. Il tuo ricordo compare dopo uno sguardo della redazione.', perHour: 3, fields: [{ key: 'name', label: 'Il tuo nome', type: 'text', required: true, min: 2, max: 80 }, { key: 'relation', label: 'Come vi conoscevate', type: 'text', max: 80, placeholder: 'es. compagno di scuola, vicina di casa' }, { key: 'text', label: 'Il ricordo', type: 'textarea', required: true, min: 20, max: 1500 }] },
  board: { kind: 'board', title: 'Metti un avviso in bacheca', button: 'Pubblica l\'avviso', thanks: 'Avviso ricevuto: compare dopo un controllo. Conserva il link che ti diamo: serve a segnarlo come risolto.', expiresDays: 14, perHour: 3, fields: [{ key: 'what', label: 'Tipo', type: 'select', required: true, max: 30, options: ['Ho perso', 'Ho trovato', 'Animale smarrito', 'Animale trovato', 'Cerco un passaggio', 'Offro un passaggio'] }, { key: 'title', label: 'In poche parole', type: 'text', required: true, min: 5, max: 100 }, { key: 'text', label: 'Dettagli (dove, quando, segni particolari)', type: 'textarea', required: true, min: 15, max: 600 }, { key: 'contact', label: 'Come contattarti (sarà pubblico)', type: 'text', required: true, min: 5, max: 100 }] },
  photo: { kind: 'photo', title: 'Apri il cassetto: manda una vecchia foto', button: 'Dona la foto all\'archivio', thanks: 'Grazie! Dopo un controllo entra nell\'archivio, dove tutti potranno aiutare a datarla.', perHour: 4, fields: [{ key: 'image', label: 'La foto (anche fotografata col telefono)', type: 'image', required: true, max: 900000 }, { key: 'caption', label: 'Cosa si vede', type: 'text', required: true, min: 5, max: 200 }, { key: 'place', label: 'Dove è stata scattata', type: 'text', required: true, min: 3, max: 120, placeholder: 'es. via Roma, davanti al municipio' }, { key: 'year', label: 'Anno, se lo sai (anche circa)', type: 'number', max: 4 }, { key: 'name', label: 'Da quale cassetto arriva (il tuo nome o la famiglia)', type: 'text', max: 80 }] },
  'listen-topic': { kind: 'listen-topic', title: 'Proponi un tema per la prossima ora di ascolto', button: 'Proponi', thanks: 'Segnato: ne parliamo alla prossima ora di ascolto.', perHour: 3, fields: [{ key: 'text', label: 'Di cosa vorresti parlare con la redazione', type: 'textarea', required: true, min: 10, max: 400 }, { key: 'name', label: 'Il tuo nome (facoltativo)', type: 'text', max: 60 }] },
  'suspended-request': { kind: 'suspended-request', title: 'Chiedi un abbonamento sospeso', button: 'Chiedi', thanks: 'Richiesta ricevuta. Se c\'è un abbonamento sospeso disponibile ti arriva un codice via email. Nessuno saprà che l\'hai chiesto.', perHour: 1, fields: [{ key: 'email', label: 'La tua email', type: 'email', required: true, max: 160, private: true }, { key: 'note', label: 'Se vuoi, due parole (facoltativo, le legge solo la redazione)', type: 'textarea', max: 300, private: true }] },
};
const EMAIL = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;
/** Valida e ripulisce un contributo secondo la sua definizione. Restituisce i dati puliti oppure il primo errore, in italiano. */
export function validateContribution(def: KindDef, input: Record<string, string>): { ok: true; data: Record<string, string> } | { ok: false; message: string } {
  const data: Record<string, string> = {};
  for (const f of def.fields) { const v = String(input[f.key] ?? '').trim(); if (!v) { if (f.required) return { ok: false, message: `Manca: ${f.label.toLowerCase()}.` }; continue; }
    if (f.type === 'image') { if (!/^data:image\/(jpeg|png|webp);base64,/.test(v) || v.length > f.max) return { ok: false, message: 'L\'immagine non è valida o è troppo pesante.' }; data[f.key] = v; continue; }
    if (f.min && v.length < f.min) return { ok: false, message: `${f.label}: scrivi almeno ${f.min} caratteri.` }; if (f.type === 'email' && !EMAIL.test(v)) return { ok: false, message: 'Inserisci un indirizzo email valido.' }; if (f.type === 'select' && !f.options?.includes(v)) return { ok: false, message: `${f.label}: scegli una voce dell'elenco.` };
    if (f.type === 'number') { const n = Number(v); if (!Number.isInteger(n) || n < 1800 || n > new Date().getFullYear()) return { ok: false, message: 'L\'anno non sembra valido.' }; data[f.key] = String(n); continue; }
    data[f.key] = (f.type === 'email' ? v.toLowerCase() : v).slice(0, f.max).replace(/[<>]/g, ''); }
  return { ok: true, data };
}
/** Toglie i campi privati (nome, email, note riservate) prima di mostrare un contributo in pubblico. */
export const publicData = (def: KindDef, data: Record<string, string>): Record<string, string> => Object.fromEntries(Object.entries(data).filter(([k]) => !def.fields.find((f) => f.key === k)?.private && k !== 'token'));
export const waitingDays = (sentIso: string | undefined, answeredIso: string | undefined, nowMs: number): number | null => (sentIso ? Math.max(0, Math.floor(((answeredIso ? +new Date(answeredIso) : nowMs) - +new Date(sentIso)) / 86_400_000)) : null);
/** Datazione collettiva: la mediana degli anni proposti, con quanta incertezza. */
export function collectiveYear(guesses: number[]): { year: number; spread: number; votes: number } | null { const g = guesses.filter((n) => Number.isFinite(n)).sort((a, b) => a - b); if (!g.length) return null; const mid = Math.floor(g.length / 2); const year = g.length % 2 ? g[mid] : Math.round((g[mid - 1] + g[mid]) / 2); return { year, spread: g[g.length - 1] - g[0], votes: g.length }; }
export const decadeOf = (year: number): string => `Anni ${Math.floor(year / 10) * 10 % 100 === 0 ? Math.floor(year / 10) * 10 : `'${String(Math.floor(year / 10) * 10).slice(2)}`}`;
/** Assemblea dei lettori: conteggio dei voti, un voto a testa. */
export function tally(options: { id: string; title: string }[], votes: string[]): { id: string; title: string; votes: number; percent: number }[] { const total = votes.filter((v) => options.some((o) => o.id === v)).length; return options.map((o) => { const n = votes.filter((v) => v === o.id).length; return { ...o, votes: n, percent: total ? Math.round((n / total) * 100) : 0 }; }).sort((a, b) => b.votes - a.votes); }
/** Prossima ora di ascolto: giorno della settimana (0 = domenica) e ora «HH:MM». */
export function nextSession(weekday: number, time: string, now: Date): Date { const [h, m] = time.split(':').map(Number); const d = new Date(now); d.setHours(h || 18, m || 0, 0, 0); let add = (weekday - d.getDay() + 7) % 7; if (add === 0 && +d <= +now - 3_600_000) add = 7; d.setDate(d.getDate() + add); return d; }
