/** Economia locale e lavoro: aperture e chiusure, affitti, crowdfunding, caffè offerti, trasparenza pubblicitaria. Solo funzioni pure. */
export interface ShopLike { title: string; fields: Record<string, string> }
/** Registro delle attività che aprono e chiudono: eventi per mese e saldo per via. */
export function openingsTrend(shops: ShopLike[]): { months: { month: string; opened: number; closed: number }[]; streets: { street: string; opened: number; closed: number }[] } {
  const ev = shops.flatMap((s) => { const out: { month: string; street: string; kind: 'opened' | 'closed' }[] = []; const street = (s.fields.via ?? '').replace(/[,\s]*\d.*$/, '').trim() || 'Senza via'; if (s.fields.dal) out.push({ month: s.fields.dal.slice(0, 7), street, kind: 'opened' }); if (s.fields.chiuso_il) out.push({ month: s.fields.chiuso_il.slice(0, 7), street, kind: 'closed' }); return out; });
  const months = [...new Set(ev.map((e) => e.month))].sort().slice(-24).map((month) => ({ month, opened: ev.filter((e) => e.month === month && e.kind === 'opened').length, closed: ev.filter((e) => e.month === month && e.kind === 'closed').length }));
  const streets = [...new Set(ev.map((e) => e.street))].map((street) => ({ street, opened: ev.filter((e) => e.street === street && e.kind === 'opened').length, closed: ev.filter((e) => e.street === street && e.kind === 'closed').length })).sort((a, b) => (b.opened + b.closed) - (a.opened + a.closed));
  return { months, streets };
}
export interface RentEntry { zone: string; rooms: string; size: number; price: number; date: string }
/** Prezzi degli affitti: per zona, mediana del canone e del prezzo al metro, con confronto al mese precedente. */
export function rentStats(entries: RentEntry[], month: string): { zone: string; n: number; median: number; perSqm: number | null; prevMedian: number | null; delta: number | null }[] {
  const med = (xs: number[]) => { const s = [...xs].sort((a, b) => a - b); return s.length ? s.length % 2 ? s[(s.length - 1) / 2] : (s[s.length / 2 - 1] + s[s.length / 2]) / 2 : 0; }; const prev = (() => { const d = new Date(`${month}-01T00:00:00Z`); d.setUTCMonth(d.getUTCMonth() - 1); return d.toISOString().slice(0, 7); })();
  const zones = [...new Set(entries.map((e) => e.zone.trim().toLowerCase()))]; return zones.map((z) => { const cur = entries.filter((e) => e.zone.trim().toLowerCase() === z && e.date.startsWith(month)); const old = entries.filter((e) => e.zone.trim().toLowerCase() === z && e.date.startsWith(prev)); const m = med(cur.map((e) => e.price)); const pm = old.length ? med(old.map((e) => e.price)) : null; const sq = cur.filter((e) => e.size > 0); return { zone: entries.find((e) => e.zone.trim().toLowerCase() === z)!.zone.trim(), n: cur.length, median: Math.round(m), perSqm: sq.length ? +med(sq.map((e) => e.price / e.size)).toFixed(1) : null, prevMedian: pm === null ? null : Math.round(pm), delta: pm ? +(((m - pm) / pm) * 100).toFixed(1) : null }; }).filter((x) => x.n > 0).sort((a, b) => b.n - a.n);
}
export const fundProgress = (goal: number, raised: number): { percent: number; left: number; done: boolean } => ({ percent: goal > 0 ? Math.min(100, Math.round((raised / goal) * 100)) : 0, left: Math.max(0, goal - raised), done: goal > 0 && raised >= goal });
export const marker = (kind: 'caffè' | 'inchiesta', id: string): string => `${kind}:${id}`;
/** Somma e conteggio delle donazioni pagate che portano un marcatore («caffè:<articolo>», «inchiesta:<slug>») nel messaggio. */
export function donationsFor(donations: { amount: number; status: string; message: string }[], mark: string): { count: number; total: number } { const l = donations.filter((d) => d.status === 'paid' && (d.message ?? '').toLowerCase().includes(mark.toLowerCase())); return { count: l.length, total: +l.reduce((n, d) => n + d.amount, 0).toFixed(2) }; }
/** Trasparenza pubblicitaria in forma aggregata: per spazio, impressioni e clic totali e tasso, senza nomi di inserzionisti. */
export function adsTransparency(ads: { slot: string; impressions: number; clicks: number; active: boolean }[]): { slot: string; campaigns: number; impressions: number; clicks: number; ctr: number }[] { const slots = [...new Set(ads.map((a) => a.slot))]; return slots.map((slot) => { const l = ads.filter((a) => a.slot === slot); const imp = l.reduce((n, a) => n + a.impressions, 0), cl = l.reduce((n, a) => n + a.clicks, 0); return { slot, campaigns: l.length, impressions: imp, clicks: cl, ctr: imp ? +((cl / imp) * 100).toFixed(2) : 0 }; }).sort((a, b) => b.impressions - a.impressions); }
