/** Emergenze e territorio: funzioni pure (allerta, SMS, catene, chiusure, fiumi, resoconto). */
export type AlertLevel = 'giallo' | 'arancione' | 'rosso';
export interface EmergencySettings { active?: boolean; title?: string; text?: string; level?: AlertLevel; since?: string; emergencyId?: string; sms?: { sid: string; token: string; from: string } }
export const LEVEL_LABELS: Record<AlertLevel, string> = { giallo: 'Allerta gialla', arancione: 'Allerta arancione', rosso: 'Allerta rossa' };
/** Chiave di una catena: testo normalizzato, prime dodici parole; due inoltri dello stesso messaggio finiscono sulla stessa verifica. */
export function chainKey(text: string): string { return text.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/https?:\/\/\S+/g, '').replace(/[^a-z0-9àèéìòù\s]/g, ' ').split(/\s+/).filter((w) => w.length > 2).slice(0, 12).join(' '); }
/** Numero italiano in formato internazionale; null se non sembra un cellulare. */
export function normalizePhone(p: string): string | null { let d = p.replace(/[^\d+]/g, ''); if (d.startsWith('00')) d = '+' + d.slice(2); if (!d.startsWith('+')) d = '+39' + d.replace(/^0+/, ''); return /^\+\d{9,15}$/.test(d) ? d : null; }
/** Un SMS d'emergenza: sigla del sito, testo, link; mai oltre 160 caratteri (un solo segmento, arriva anche con rete scarsa). */
export function smsText(site: string, text: string, url: string): string { const head = `${site.slice(0, 20)}: `; const tail = url ? ` ${url}` : ''; const room = 160 - head.length - tail.length; const body = text.replace(/\s+/g, ' ').trim(); return head + (body.length > room ? body.slice(0, room - 1) + '…' : body) + tail; }
export type ClosureKind = 'strada' | 'scuola' | 'ufficio' | 'ponte' | 'parco' | 'trasporti' | 'altro';
export const CLOSURE_LABELS: Record<ClosureKind, string> = { strada: 'Strade', scuola: 'Scuole', ufficio: 'Uffici e servizi', ponte: 'Ponti e sottopassi', parco: 'Parchi e cimiteri', trasporti: 'Trasporti', altro: 'Altro' };
export interface Closure { id: string; kind: ClosureKind; name: string; status: 'chiuso' | 'parziale' | 'riaperto'; until: string; note: string; updatedAt: string }
export function closureGroups(list: Closure[]): { kind: ClosureKind; label: string; items: Closure[] }[] { const by = new Map<ClosureKind, Closure[]>(); for (const c of [...list].sort((a, b) => (a.status === 'riaperto' ? 1 : 0) - (b.status === 'riaperto' ? 1 : 0) || a.name.localeCompare(b.name, 'it'))) by.set(c.kind, [...(by.get(c.kind) ?? []), c]); return (Object.keys(CLOSURE_LABELS) as ClosureKind[]).filter((k) => by.has(k)).map((kind) => ({ kind, label: CLOSURE_LABELS[kind], items: by.get(kind)! })); }
/** «Sto bene»: per zona, i più recenti prima; ricerca per nome. */
export function groupByZone<T extends { zone: string; name: string; createdAt: string }>(list: T[], q = ''): { zone: string; items: T[] }[] { const n = (s: string) => s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, ''); const f = q ? list.filter((x) => n(x.name).includes(n(q))) : list; const by = new Map<string, T[]>(); for (const x of [...f].sort((a, b) => b.createdAt.localeCompare(a.createdAt))) by.set(x.zone || 'Altro', [...(by.get(x.zone || 'Altro') ?? []), x]); return [...by.entries()].sort((a, b) => a[0].localeCompare(b[0], 'it')).map(([zone, items]) => ({ zone, items })); }
/** Stato del fiume dalle soglie. */
export function riverStatus(level: number | null, attention?: number, alarm?: number): { state: 'ok' | 'attenzione' | 'allarme' | 'nd'; label: string } { if (level === null) return { state: 'nd', label: 'livello non disponibile' }; if (alarm && level >= alarm) return { state: 'allarme', label: 'sopra la soglia di allarme' }; if (attention && level >= attention) return { state: 'attenzione', label: 'sopra la soglia di attenzione' }; return { state: 'ok', label: 'sotto le soglie' }; }
/** Piene storiche: i picchi sopra la soglia di attenzione, per episodio (giorni consecutivi). */
export function floods(points: { d: string; v: number }[], attention: number): { from: string; to: string; peak: number }[] { const out: { from: string; to: string; peak: number }[] = []; let cur: { from: string; to: string; peak: number } | null = null; for (const p of [...points].sort((a, b) => a.d.localeCompare(b.d))) { if (p.v >= attention) { if (cur && (+new Date(p.d) - +new Date(cur.to)) <= 2 * 86_400_000) { cur.to = p.d; cur.peak = Math.max(cur.peak, p.v); } else { if (cur) out.push(cur); cur = { from: p.d, to: p.d, peak: p.v }; } } } if (cur) out.push(cur); return out.reverse(); }
/** Dopo l'emergenza: il resoconto in testo, pronto per il fascicolo. */
export function emergencyReport(e: { title: string; level?: string; from: string; to: string }, diary: { at: string; text: string; source?: string }[], closures: Closure[], okCount: number, smsSent: number): string {
  const fmt = (iso: string) => new Date(iso).toLocaleString('it-IT', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }); const hours = Math.round((+new Date(e.to) - +new Date(e.from)) / 3_600_000);
  return [`${e.title}${e.level ? ` (${LEVEL_LABELS[e.level as AlertLevel] ?? e.level})` : ''}`, `Dal ${fmt(e.from)} al ${fmt(e.to)} (${hours} ore).`, `${diary.length} aggiornamenti nel diario, ${closures.length} chiusure registrate, ${okCount} «sto bene», ${smsSent} SMS inviati.`, '', 'CRONOLOGIA', ...[...diary].sort((a, b) => a.at.localeCompare(b.at)).map((d) => `${fmt(d.at)} — ${d.text}${d.source ? ` (${d.source})` : ''}`), '', 'CHIUSURE', ...closures.map((c) => `${CLOSURE_LABELS[c.kind]}: ${c.name} — ${c.status}${c.until ? ` fino al ${c.until}` : ''}`)].join('\n');
}
