/** Guida in-app: una voce per area della redazione, con testo breve e video (link YouTube da sostituire con i propri). */
export interface GuideSection { id: string; path: string; title: string; text: string; steps: string[]; video?: string }
export const GUIDE: GuideSection[] = [
  { id: 'dashboard', path: '/admin', title: 'Dashboard e primi passi', text: 'La dashboard mostra cosa succede oggi: articoli in revisione, commenti da moderare, il tuo lavoro. La guida ai primi passi sparisce quando hai completato la configurazione.', steps: ['Completa i primi passi (nome testata, tema, categorie, primo articolo, colleghi).', 'Usa «Il mio lavoro» per bozze, assegnazioni e richieste di modifica.', 'La campanella in alto raccoglie le notifiche della redazione.'] },
  { id: 'scrivi', path: '/admin/scrivi', title: 'Scrivere un articolo', text: 'Scrivi (semplice) pensa alla SEO per te: titolo, sommario, tag e immagine bastano. L\'editor completo aggiunge blocchi, modelli, campi personalizzati e strumenti avanzati.', steps: ['Parti da un modello (intervista, recensione, diretta…) se serve una struttura.', 'Inserisci i blocchi con «+»: riquadri, timeline, grafici, quiz, prima/dopo, PDF, audio.', 'Le note a piè di pagina si scrivono così: [^testo della nota].', 'Con «Ottimizza automaticamente» la SEO viene sistemata; l\'accessibilità è controllata in tempo reale.'] },
  { id: 'media', path: '/admin/media', title: 'Libreria media', text: 'Le foto caricate diventano WebP in cinque misure. Il punto focale decide dove tagliare; da lì nascono i ritagli per i social.', steps: ['Cartelle e tag per ritrovare i file; il cestino conserva 30 giorni.', 'Ritocchi base, filigrana per le esclusive, credit e scadenza dei diritti.', 'Banca immagini (Unsplash/Pexels) e video hosting (Cloudflare/Mux) dalle Impostazioni.'] },
  { id: 'redazione', path: '/admin/redazione', title: 'Desk, flussi e regole', text: 'I desk raggruppano categorie e persone con code di revisione separate; le fasi di approvazione impongono passaggi prima della pubblicazione; le regole automatizzano evidenza, ultim\'ora e social.', steps: ['Crea un desk per squadra e assegna categorie e membri.', 'Imposta le fasi (es. desk → caporedattore → legale).', 'Aggiungi regole «se… allora…» per la pubblicazione.'] },
  { id: 'community', path: '/admin/commenti', title: 'Commenti e lettori', text: 'I commenti passano dalla moderazione (anche assistita da Claude); i lettori hanno profili, preferenze, articoli salvati e abbonamenti.', steps: ['Ordina la coda per priorità: i casi rischiosi sono in cima.', 'Rispondi come redazione direttamente sotto l\'articolo.', 'Piani, regali e muro di registrazione si impostano in Impostazioni → Monetizzazione e Lettori.'] },
  { id: 'distribuzione', path: '/admin/social', title: 'Social, newsletter, feed', text: 'Ogni articolo può partire da solo su Facebook, X, Telegram e webhook; le newsletter hanno liste e blocchi; i feed per Google News, Flipboard, Apple News e podcast sono pronti.', steps: ['Collega i canali in Impostazioni → Social.', 'Pianifica per canale dal pannello «Pianificazione per canale» dell\'editor.', 'Registra i feed nei Publisher Center.'] },
  { id: 'seo', path: '/admin/statistiche', title: 'SEO e prestazioni', text: 'La SEO è automatica; qui trovi Search Console, tendenze, titoli della concorrenza, test A/B, PageSpeed e Web Vitals reali.', steps: ['Inserisci la chiave PageSpeed e l\'account Search Console.', 'Guarda le pagine premiate da Discover e i titoli che vincono i test A/B.', 'Le immagini si ridimensionano da sole: se un punteggio scende, il pannello dice cosa fare.'] },
  { id: 'sistema', path: '/admin/impostazioni', title: 'Impostazioni, sicurezza e aggiornamenti', text: 'Tema, CSS con anteprima, builder della home, edizioni, estensioni, backup, aggiornamenti con un clic, staging, log di sicurezza, privacy e consensi.', steps: ['Fai un backup prima di aggiornare.', 'Prova gli aggiornamenti in staging e promuovili in produzione.', 'Controlla il registro accessi e i consensi cookie dal menu Sistema.'] },
];
export const guideFor = (pathname: string): GuideSection => [...GUIDE].sort((a, b) => b.path.length - a.path.length).find((g) => pathname.startsWith(g.path)) ?? GUIDE[0];
