import type { HomeBlock } from './models';
import type { ThemeSettings } from './themes';

/** Libreria di layout: tema + composizione della home pronti da applicare (e da esportare/importare in JSON). */
export interface LayoutPreset { id: string; name: string; description: string; theme: Partial<ThemeSettings>; blocks: HomeBlock[] }
const b = (type: HomeBlock['type'], title: string, extra: Partial<HomeBlock> = {}): HomeBlock => ({ id: `${type}-${Math.random().toString(36).slice(2, 7)}`, type, title, sourceId: '', layout: 'grid4', count: 4, ...extra });
export const LAYOUT_PRESETS: LayoutPreset[] = [
  { id: 'quotidiano', name: 'Quotidiano', description: 'Testata classica: apertura forte, sezioni per categoria a quattro colonne, eventi e più letti.', theme: { preset: 'today', homeLayout: 'today' }, blocks: [b('latest', 'Ultime notizie', { layout: 'list', count: 8 }), b('events', 'Cosa fare in città', { count: 4 }), b('category', 'Sezioni', { layout: 'grid4', count: 4, sourceId: '*' }), b('format', 'Video', { sourceId: 'video', layout: 'grid3', count: 3 }), b('mostread', 'Più letti', { count: 8 }), b('newsletter', 'Newsletter')] },
  { id: 'magazine', name: 'Magazine', description: 'Foto grandi, tre colonne, rubriche in evidenza: per settimanali e riviste online.', theme: { preset: 'today', homeLayout: 'magazine', cardStyle: 'flat' }, blocks: [b('category', 'Sezioni', { layout: 'grid3', count: 3, sourceId: '*' }), b('format', 'Fotogallery', { sourceId: 'gallery', layout: 'grid3', count: 3 }), b('tag', 'In evidenza', { layout: 'band', count: 4 }), b('mostread', 'Più letti', { count: 6 }), b('newsletter', 'Newsletter')] },
  { id: 'locale', name: 'Giornale locale', description: 'Zone e quartieri in primo piano, eventi, segnalazioni e meteo: il modello Citynews.', theme: { preset: 'today', homeLayout: 'today' }, blocks: [b('events', 'Cosa fare in città', { count: 4 }), b('zone', 'Dalle zone', { layout: 'grid4', count: 4, sourceId: '*' }), b('category', 'Sezioni', { layout: 'grid4', count: 4, sourceId: '*' }), b('latest', 'Ultime', { layout: 'list', count: 10 }), b('mostread', 'Più letti', { count: 8 }), b('newsletter', 'Newsletter')] },
  { id: 'minimal', name: 'Minimal', description: 'Poche sezioni, tanto bianco, lettura veloce: per newsletter-first e testate verticali.', theme: { preset: 'today', homeLayout: 'grid', cardStyle: 'flat', radius: 0 }, blocks: [b('latest', 'Ultime notizie', { layout: 'list', count: 12 }), b('newsletter', 'Newsletter'), b('mostread', 'Più letti', { count: 5 })] },
];
export const BLOCK_TYPES: { id: HomeBlock['type']; label: string; needsSource: 'category' | 'tag' | 'zone' | 'format' | null }[] = [{ id: 'latest', label: 'Ultime notizie', needsSource: null }, { id: 'category', label: 'Categoria (o tutte con «*»)', needsSource: 'category' }, { id: 'tag', label: 'Tag / dossier', needsSource: 'tag' }, { id: 'zone', label: 'Zona (o tutte con «*»)', needsSource: 'zone' }, { id: 'format', label: 'Formato (video, gallery, live)', needsSource: 'format' }, { id: 'events', label: 'Eventi', needsSource: null }, { id: 'mostread', label: 'Più letti', needsSource: null }, { id: 'newsletter', label: 'Iscrizione newsletter', needsSource: null }, { id: 'html', label: 'HTML libero (banner, embed)', needsSource: null }];
export const LAYOUTS: { id: HomeBlock['layout']; label: string }[] = [{ id: 'grid4', label: '4 colonne' }, { id: 'grid3', label: '3 colonne' }, { id: 'grid2', label: '2 colonne grandi' }, { id: 'list', label: 'Elenco orizzontale' }, { id: 'band', label: 'Fascia colorata' }];
