/** Tipi di contributo dei lettori che passano dalla moderazione unica in /admin/partecipazione. `who` e `body` sono le chiavi dei dati da mostrare. */
export const PARTICIPATION_KINDS: { kind: string; label: string; who: string; body: string }[] = [
  { kind: 'response', label: 'Risposte lunghe agli articoli', who: 'name', body: 'text' },
  { kind: 'manifesto', label: 'Manifesti elettorali fotografati', who: 'where', body: 'image' },
  { kind: 'paniere', label: 'Prezzi rilevati per il paniere', who: 'shop', body: 'product' },
  { kind: 'rumore', label: 'Rumore e odori', who: 'where', body: 'text' },
  { kind: 'ritardo', label: 'Ritardi del trasporto pubblico', who: 'line', body: 'kind' },
  { kind: 'albero', label: 'Censimento degli alberi', who: 'where', body: 'image' },
  { kind: 'voce-genitori', label: 'Voce dei genitori (scuole)', who: 'name', body: 'text' },
  { kind: 'cantiere-foto', label: 'Foto dei cantieri', who: 'text', body: 'image' },
  { kind: 'lettura', label: 'Letture ad alta voce dei volontari', who: 'name', body: 'audio' },
  { kind: 'memoria-audio', label: 'Memorie dei quartieri (audio)', who: 'name', body: 'audio' },
  { kind: 'negozio-richiesta', label: 'Richieste di pagina negozio (Pubblica = crea la scheda)', who: 'name', body: 'via' },
  { kind: 'avviso-negozio', label: 'Avvisi del mese dei negozi', who: 'ref', body: 'text' },
  { kind: 'lavoro', label: 'Offerte di lavoro (Pubblica = azienda verificata)', who: 'company', body: 'role' },
  { kind: 'mercatino', label: 'Mercatino del quartiere', who: 'contact', body: 'title' },
  { kind: 'affitto', label: 'Prezzi degli affitti rilevati', who: 'zone', body: 'price' },
  { kind: 'guestbook', label: 'Libro degli ospiti (messaggi scritti a mano)', who: 'name', body: 'image' },
  { kind: 'log', label: 'Taccuino di quartiere', who: 'name', body: 'text' },
  { kind: 'council', label: 'Domande al Comune', who: 'name', body: 'text' },
  { kind: 'board', label: 'Bacheca (smarriti, trovati, passaggi)', who: 'contact', body: 'text' },
  { kind: 'photo', label: 'Archivio fotografico', who: 'name', body: 'image' },
  { kind: 'memory', label: 'Ricordi sui necrologi', who: 'name', body: 'text' },
  { kind: 'translation', label: 'Traduzioni volontarie', who: 'name', body: 'text' },
  { kind: 'skill', label: 'Banca delle competenze (mai pubblicata: «Pubblica» = accetta in rubrica)', who: 'name', body: 'about' },
];
