import 'server-only';
import { all, get, run } from './db';
import { Ad, Listing, Newsletter, NewsletterBlock, SocialPost, Subscriber } from './models';

type Row = Record<string, unknown>;
const b = (v: unknown) => (v ? 1 : 0);
const pj = <T,>(s: unknown, fallback: T): T => { try { return s ? (JSON.parse(String(s)) as T) : fallback; } catch { return fallback; } };
const now = () => new Date().toISOString();

// ---------------- Social ----------------
const rowToSocial = (r: Row): SocialPost => ({ id: String(r.id), articleId: String(r.article_id ?? ''), network: r.network as SocialPost['network'], status: r.status as SocialPost['status'], text: String(r.text ?? ''), image: String(r.image ?? ''), url: String(r.url ?? ''), scheduledAt: (r.scheduled_at as string | null) ?? null, sentAt: (r.sent_at as string | null) ?? null, result: String(r.result ?? ''), createdBy: String(r.created_by ?? ''), createdAt: String(r.created_at ?? '') });
export async function insertSocialPost(p: SocialPost): Promise<void> { await run('INSERT INTO social_posts (id, article_id, network, status, text, image, url, scheduled_at, sent_at, result, created_by, created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)', [p.id, p.articleId, p.network, p.status, p.text, p.image, p.url, p.scheduledAt, p.sentAt, p.result, p.createdBy, p.createdAt]); }
export async function updateSocialPost(id: string, patch: Partial<Pick<SocialPost, 'status' | 'sentAt' | 'result' | 'text' | 'scheduledAt'>>): Promise<void> {
  const cols: Record<string, unknown> = {}; if (patch.status) cols.status = patch.status; if (patch.sentAt !== undefined) cols.sent_at = patch.sentAt; if (patch.result !== undefined) cols.result = patch.result; if (patch.text !== undefined) cols.text = patch.text; if (patch.scheduledAt !== undefined) cols.scheduled_at = patch.scheduledAt;
  if (!Object.keys(cols).length) return; await run(`UPDATE social_posts SET ${Object.keys(cols).map((k) => `${k} = ?`).join(', ')} WHERE id = ?`, [...Object.values(cols), id]);
}
export const listSocialPosts = async (limit = 100, status?: SocialPost['status']): Promise<SocialPost[]> => ((status ? await all('SELECT * FROM social_posts WHERE status = ? ORDER BY COALESCE(scheduled_at, created_at) DESC LIMIT ?', [status, limit]) : await all('SELECT * FROM social_posts ORDER BY created_at DESC LIMIT ?', [limit])) as Row[]).map(rowToSocial);
export const dueSocialPosts = async (limit = 20): Promise<SocialPost[]> => (await all("SELECT * FROM social_posts WHERE status = 'queued' AND (scheduled_at IS NULL OR scheduled_at <= ?) ORDER BY created_at LIMIT ?", [now(), limit]) as Row[]).map(rowToSocial);
export const socialPostsForArticle = async (articleId: string): Promise<SocialPost[]> => (await all('SELECT * FROM social_posts WHERE article_id = ? ORDER BY created_at DESC', [articleId]) as Row[]).map(rowToSocial);
export async function deleteSocialPost(id: string): Promise<void> { await run('DELETE FROM social_posts WHERE id = ?', [id]); }

// ---------------- Newsletter multiple ----------------
const rowToNewsletter = (r: Row): Newsletter => ({ id: String(r.id), slug: String(r.slug), name: String(r.name), description: String(r.description ?? ''), kind: (r.kind as Newsletter['kind']) ?? 'digest', config: pj<Newsletter['config']>(r.config, {}), blocks: pj<NewsletterBlock[]>(r.blocks, []), schedule: { hour: 7, days: [1, 2, 3, 4, 5, 6, 0], enabled: false, ...pj<Partial<Newsletter['schedule']>>(r.schedule, {}) }, enabled: !!r.enabled, isDefault: !!r.is_default, createdAt: String(r.created_at ?? '') });
export const listNewsletters = async (): Promise<Newsletter[]> => (await all('SELECT * FROM newsletters ORDER BY is_default DESC, name') as Row[]).map(rowToNewsletter);
export const findNewsletter = async (id: string): Promise<Newsletter | undefined> => { const r = await get('SELECT * FROM newsletters WHERE id = ? OR slug = ?', [id, id]) as Row | undefined; return r ? rowToNewsletter(r) : undefined; };
export async function upsertNewsletter(n: Newsletter): Promise<void> { await run('INSERT INTO newsletters (id, slug, name, description, kind, config, blocks, schedule, enabled, is_default, created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT (id) DO UPDATE SET slug=excluded.slug, name=excluded.name, description=excluded.description, kind=excluded.kind, config=excluded.config, blocks=excluded.blocks, schedule=excluded.schedule, enabled=excluded.enabled, is_default=excluded.is_default', [n.id, n.slug, n.name, n.description, n.kind, JSON.stringify(n.config), JSON.stringify(n.blocks), JSON.stringify(n.schedule), b(n.enabled), b(n.isDefault), n.createdAt]); if (n.isDefault) await run('UPDATE newsletters SET is_default = 0 WHERE id <> ?', [n.id]); }
export async function deleteNewsletter(id: string): Promise<void> { await run('DELETE FROM newsletters WHERE id = ?', [id]); await run('DELETE FROM subscriber_lists WHERE list_id = ?', [id]); }
export async function subscribeToList(subscriberId: string, listId: string): Promise<void> { await run('INSERT INTO subscriber_lists (subscriber_id, list_id, created_at) VALUES (?,?,?) ON CONFLICT DO NOTHING', [subscriberId, listId, now()]); }
export async function unsubscribeFromList(subscriberId: string, listId: string): Promise<void> { await run('DELETE FROM subscriber_lists WHERE subscriber_id = ? AND list_id = ?', [subscriberId, listId]); }
export const listsOfSubscriber = async (subscriberId: string): Promise<string[]> => (await all('SELECT list_id FROM subscriber_lists WHERE subscriber_id = ?', [subscriberId]) as Row[]).map((r) => String(r.list_id));
export const listCounts = async (): Promise<Record<string, number>> => { const out: Record<string, number> = {}; (await all("SELECT sl.list_id, COUNT(*) c FROM subscriber_lists sl JOIN subscribers s ON s.id = sl.subscriber_id WHERE s.status = 'confirmed' GROUP BY sl.list_id") as Row[]).forEach((r) => { out[String(r.list_id)] = Number(r.c); }); return out; };
export const subscribersOfList = async (listId: string, limit = 50000): Promise<Subscriber[]> => (await all("SELECT s.* FROM subscribers s JOIN subscriber_lists sl ON sl.subscriber_id = s.id WHERE sl.list_id = ? AND s.status = 'confirmed' ORDER BY s.created_at LIMIT ?", [listId, limit]) as Row[]).map((r) => ({ id: String(r.id), email: String(r.email), createdAt: String(r.created_at), status: 'confirmed' as const }));
export async function recordNewsletterEvent(sendId: string, subscriberId: string, kind: 'open' | 'click', url = ''): Promise<void> {
  const exists = await get('SELECT 1 FROM newsletter_events WHERE send_id = ? AND subscriber_id = ? AND kind = ? AND url = ?', [sendId, subscriberId, kind, url]);
  if (exists) return;
  await run('INSERT INTO newsletter_events (id, send_id, subscriber_id, kind, url, created_at) VALUES (?,?,?,?,?,?)', ['ne_' + Math.random().toString(36).slice(2, 12), sendId, subscriberId, kind, url, now()]);
  await run(`UPDATE newsletter_sends SET ${kind === 'open' ? 'opens' : 'clicks'} = (SELECT COUNT(DISTINCT subscriber_id) FROM newsletter_events WHERE send_id = ? AND kind = ?) WHERE id = ?`, [sendId, kind, sendId]);
}
export const topClickedUrls = async (sendId: string): Promise<{ url: string; n: number }[]> => (await all("SELECT url, COUNT(*) n FROM newsletter_events WHERE send_id = ? AND kind = 'click' GROUP BY url ORDER BY n DESC LIMIT 10", [sendId]) as Row[]).map((r) => ({ url: String(r.url), n: Number(r.n) }));

// ---------------- Pubblicità ----------------
const rowToAd = (r: Row): Ad => ({ id: String(r.id), slot: String(r.slot), name: String(r.name), type: (r.type as Ad['type']) ?? 'image', image: String(r.image ?? ''), url: String(r.url ?? ''), html: String(r.html ?? ''), label: String(r.label ?? ''), startAt: (r.start_at as string | null) ?? null, endAt: (r.end_at as string | null) ?? null, weight: Number(r.weight ?? 1), impressions: Number(r.impressions ?? 0), clicks: Number(r.clicks ?? 0), active: !!r.active, createdAt: String(r.created_at ?? '') });
export const listAds = async (): Promise<Ad[]> => (await all('SELECT * FROM ads ORDER BY slot, created_at DESC') as Row[]).map(rowToAd);
export const activeAdsForSlot = async (slot: string): Promise<Ad[]> => (await all('SELECT * FROM ads WHERE slot = ? AND active = 1 AND (start_at IS NULL OR start_at <= ?) AND (end_at IS NULL OR end_at >= ?)', [slot, now(), now()]) as Row[]).map(rowToAd);
export const findAd = async (id: string): Promise<Ad | undefined> => { const r = await get('SELECT * FROM ads WHERE id = ?', [id]) as Row | undefined; return r ? rowToAd(r) : undefined; };
export async function upsertAd(a: Ad): Promise<void> { await run('INSERT INTO ads (id, slot, name, type, image, url, html, label, start_at, end_at, weight, impressions, clicks, active, created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT (id) DO UPDATE SET slot=excluded.slot, name=excluded.name, type=excluded.type, image=excluded.image, url=excluded.url, html=excluded.html, label=excluded.label, start_at=excluded.start_at, end_at=excluded.end_at, weight=excluded.weight, active=excluded.active', [a.id, a.slot, a.name, a.type, a.image, a.url, a.html, a.label, a.startAt, a.endAt, a.weight, a.impressions, a.clicks, b(a.active), a.createdAt]); }
export async function deleteAd(id: string): Promise<void> { await run('DELETE FROM ads WHERE id = ?', [id]); }
export async function bumpAd(id: string, field: 'impressions' | 'clicks'): Promise<void> { await run(`UPDATE ads SET ${field} = ${field} + 1 WHERE id = ?`, [id]); }

// ---------------- Annunci e necrologi ----------------
const rowToListing = (r: Row): Listing => ({ id: String(r.id), kind: r.kind as Listing['kind'], title: String(r.title), body: String(r.body ?? ''), image: String(r.image ?? ''), category: String(r.category ?? ''), price: String(r.price ?? ''), contactName: String(r.contact_name ?? ''), contactEmail: String(r.contact_email ?? ''), contactPhone: String(r.contact_phone ?? ''), zoneId: String(r.zone_id ?? ''), status: r.status as Listing['status'], paid: !!r.paid, amount: Number(r.amount ?? 0), expiresAt: (r.expires_at as string | null) ?? null, readerId: String(r.reader_id ?? ''), createdAt: String(r.created_at ?? ''), publishedAt: (r.published_at as string | null) ?? null, extra: pj<Record<string, string>>(r.extra, {}) });
export async function upsertListing(l: Listing): Promise<void> { await run('INSERT INTO listings (id, kind, title, body, image, category, price, contact_name, contact_email, contact_phone, zone_id, status, paid, amount, expires_at, reader_id, created_at, published_at, extra) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT (id) DO UPDATE SET title=excluded.title, body=excluded.body, image=excluded.image, category=excluded.category, price=excluded.price, contact_name=excluded.contact_name, contact_email=excluded.contact_email, contact_phone=excluded.contact_phone, zone_id=excluded.zone_id, status=excluded.status, paid=excluded.paid, amount=excluded.amount, expires_at=excluded.expires_at, published_at=excluded.published_at, extra=excluded.extra', [l.id, l.kind, l.title, l.body, l.image, l.category, l.price, l.contactName, l.contactEmail, l.contactPhone, l.zoneId, l.status, b(l.paid), l.amount, l.expiresAt, l.readerId, l.createdAt, l.publishedAt, JSON.stringify(l.extra)]); }
export const findListing = async (id: string): Promise<Listing | undefined> => { const r = await get('SELECT * FROM listings WHERE id = ?', [id]) as Row | undefined; return r ? rowToListing(r) : undefined; };
export const listListings = async (f: { kind?: Listing['kind']; status?: Listing['status']; category?: string; zoneId?: string; q?: string } = {}, limit = 60, offset = 0): Promise<Listing[]> => {
  const w: string[] = []; const p: unknown[] = [];
  if (f.kind) { w.push('kind = ?'); p.push(f.kind); } if (f.status) { w.push('status = ?'); p.push(f.status); } if (f.category) { w.push('category = ?'); p.push(f.category); } if (f.zoneId) { w.push('zone_id = ?'); p.push(f.zoneId); } if (f.q) { w.push('(title ILIKE ? OR body ILIKE ?)'); p.push(`%${f.q}%`, `%${f.q}%`); }
  return (await all(`SELECT * FROM listings ${w.length ? 'WHERE ' + w.join(' AND ') : ''} ORDER BY COALESCE(published_at, created_at) DESC LIMIT ? OFFSET ?`, [...p, limit, offset]) as Row[]).map(rowToListing);
};
export const countListings = async (f: { kind?: Listing['kind']; status?: Listing['status'] } = {}): Promise<number> => { const w: string[] = []; const p: unknown[] = []; if (f.kind) { w.push('kind = ?'); p.push(f.kind); } if (f.status) { w.push('status = ?'); p.push(f.status); } return Number((await get(`SELECT COUNT(*) c FROM listings ${w.length ? 'WHERE ' + w.join(' AND ') : ''}`, p) as Row).c); };
export async function updateListingStatus(id: string, status: Listing['status'], paid?: boolean): Promise<void> { await run(`UPDATE listings SET status = ?, published_at = CASE WHEN ? = 'published' AND published_at IS NULL THEN ? ELSE published_at END${paid !== undefined ? ', paid = ' + (paid ? 1 : 0) : ''} WHERE id = ?`, [status, status, now(), id]); }
export async function deleteListing(id: string): Promise<void> { await run('DELETE FROM listings WHERE id = ?', [id]); }
export async function expireListings(): Promise<void> { await run("UPDATE listings SET status = 'expired' WHERE status = 'published' AND expires_at IS NOT NULL AND expires_at < ?", [now()]); }
