import { articleBySlug, getCategories, getSettings } from '@/lib/queries';
import { siteUrl } from '@/lib/site-url';
import { stripHtml } from '@/lib/utils';

export const dynamic = 'force-dynamic';
const esc = (s: string) => s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));

/** Web Story (AMP) generata dall'articolo: copertina + una pagina per foto della gallery (o per paragrafo chiave) + pagina finale con link. */
export async function GET(_req: Request, { params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const a = await articleBySlug(slug); if (!a) return new Response('Not found', { status: 404 });
  const [s, cats] = await Promise.all([getSettings(), getCategories()]); const base = siteUrl(); const cat = cats.find((c) => c.id === a.categoryId);
  const images = [...new Set([a.coverImage, ...a.gallery, ...[...a.content.matchAll(/<img[^>]*src="([^"]+)"/g)].map((m) => m[1])].filter(Boolean))].slice(0, 12);
  if (images.length < 2) return new Response('Storia non disponibile: servono almeno due immagini.', { status: 404 });
  const paras = stripHtml(a.content).split(/(?<=[.!?])\s+/).filter((p) => p.length > 40).slice(0, images.length);
  const logo = `${base}/api/og/site.png`; const url = `${base}/${cat?.slug ?? 'notizie'}/${a.slug}`;
  const page = (i: number, img: string, text: string, first = false) => `<amp-story-page id="p${i}"><amp-story-grid-layer template="fill"><amp-img src="${esc(img)}" width="720" height="1280" layout="responsive" alt="${esc(a.title)}"></amp-img></amp-story-grid-layer><amp-story-grid-layer template="vertical" class="bottom"><div class="txt">${first ? `<span class="k">${esc(a.kicker || cat?.name || '')}</span><h1>${esc(a.title)}</h1><p>${esc(a.subtitle || a.excerpt)}</p>` : `<p>${esc(text)}</p>`}</div></amp-story-grid-layer></amp-story-page>`;
  const html = `<!doctype html><html ⚡ lang="it"><head><meta charset="utf-8"><title>${esc(a.title)}</title><link rel="canonical" href="${base}/storie/${a.slug}"><meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"><script async src="https://cdn.ampproject.org/v0.js"></script><script async custom-element="amp-story" src="https://cdn.ampproject.org/v0/amp-story-1.0.js"></script><style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript><style amp-custom>amp-story{font-family:Georgia,serif}.bottom{align-content:end}.txt{background:linear-gradient(transparent,rgba(0,0,0,.85));padding:120px 24px 40px;color:#fff}.k{font:800 12px/1 Arial,sans-serif;letter-spacing:.14em;text-transform:uppercase;color:#ffd200}h1{font-size:34px;line-height:1.1;margin:8px 0}p{font-size:18px;line-height:1.4;margin:0}.end{display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;color:#fff;background:#22418f;height:100%;padding:24px}.end a{color:#fff;font:700 18px Arial,sans-serif;border:2px solid #fff;padding:12px 20px;border-radius:30px;text-decoration:none;margin-top:16px}</style><script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@type': 'NewsArticle', headline: a.title, image: images, datePublished: a.publishedAt, publisher: { '@type': 'Organization', name: s.siteName, logo: { '@type': 'ImageObject', url: logo } }, mainEntityOfPage: url })}</script></head><body><amp-story standalone title="${esc(a.title)}" publisher="${esc(s.siteName)}" publisher-logo-src="${logo}" poster-portrait-src="${esc(images[0])}">${images.map((img, i) => page(i, img, paras[i] ?? a.excerpt, i === 0)).join('')}<amp-story-page id="end"><amp-story-grid-layer template="fill"><div class="end"><h1>${esc(s.siteName)}</h1><p>Leggi l'articolo completo</p><a href="${url}">Apri</a></div></amp-story-grid-layer></amp-story-page></amp-story></body></html>`;
  return new Response(html, { headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'public, max-age=600' } });
}
