import { describe, expect, it } from 'vitest';
import { alphaIndex, chainOk, depositHash, filterDocs, followUps, frontPage, parseRoles, randomDay, rolesInYear, sameDay, timeline, withoutFollowUp, yearGrid } from '../src/lib/archive';

const A = (id: string, publishedAt: string, tagIds: string[] = [], views = 0, categoryId = 'c1', featured = false) => ({ id, title: id, categoryId, tagIds, publishedAt, views, featured });
describe('archivio e memoria', () => {
  it('prima pagina: apertura in evidenza e sezioni per numero di pezzi', () => { const fp = frontPage([A('a', '2025-01-01', [], 10), A('b', '2025-01-01', [], 5, 'c2', true), A('c', '2025-01-01', [], 1, 'c2'), A('d', '2025-01-01', [], 3)]); expect(fp.lead?.id).toBe('b'); expect(fp.sections[0].categoryId).toBe('c1'); expect(fp.sections[0].items.map((x) => x.id)).toEqual(['a', 'd']); });
  it('accadde oggi: solo anni passati, dal più lontano', () => { const r = sameDay([A('x', '2022-10-02'), A('y', '2024-10-02'), A('z', '2026-10-02'), A('w', '2024-10-03')], '10-02', 2026); expect(r.map((g) => g.year)).toEqual([2022, 2024]); });
  it('indice alfabetico ignora «via» e accenti', () => { const idx = alphaIndex([{ title: 'Via Roma' }, { title: 'Piazza degli Èroi' }, { title: 'Corso Italia' }, { title: '3 Novembre' }]); expect(idx.map((l) => l.letter)).toEqual(['#', 'E', 'I', 'R']); });
  it('catalogo documenti: ricerca e filtro per ente', () => { const d = [{ title: 'Delibera 12', fields: { ente: 'Comune', riassunto: 'piano traffico', data: '2024-01-01' } }, { title: 'Bando', fields: { ente: 'Regione', riassunto: 'traffico', data: '2025-01-01' } }]; expect(filterDocs(d, 'traffico').map((x) => x.title)).toEqual(['Bando', 'Delibera 12']); expect(filterDocs(d, 'traffico', 'Comune')).toHaveLength(1); });
  it('linea del tempo per anno e mese', () => { const t = timeline([A('a', '2024-03-01'), A('b', '2023-05-01'), A('c', '2024-03-09')]); expect(t.map((y) => y.year)).toEqual(['2023', '2024']); expect(t[1].months[0].items).toHaveLength(2); expect(t[1].n).toBe(2); });
  it('ruoli e chi era chi', () => { const r = parseRoles('2019-2024: assessore\ndal 2024: sindaco\n2016: candidato\nriga senza senso'); expect(r).toHaveLength(3); expect(r[0]).toEqual({ from: 2016, to: 2016, role: 'candidato' }); expect(r[2].to).toBeNull(); const who = rolesInYear([{ title: 'Rossi', fields: { ruoli: '2019-2024: assessore\ndal 2024: sindaco' } }], 2021); expect(who[0].role).toBe('assessore'); expect(rolesInYear([{ title: 'Rossi', fields: { ruoli: 'dal 2024: sindaco' } }], 2026)[0].role).toBe('sindaco'); });
  it('griglia delle annate', () => { const g = yearGrid([{ month: '2025-01', n: 3 }, { month: '2025-12', n: 2 }, { month: '2024-06', n: 1 }]); expect(g[0].year).toBe('2025'); expect(g[0].months[0]).toBe(3); expect(g[0].total).toBe(5); });
  it('seguiti: dopo almeno sette giorni, con argomento condiviso', () => { const a = A('a', '2025-01-01T00:00:00.000Z', ['t1', 't2']); const c = [A('b', '2025-01-03', ['t1']), A('c', '2025-02-01', ['t1', 't2']), A('d', '2025-03-01', ['t1']), A('e', '2025-03-01', ['t9'])]; expect(followUps(a, c).map((x) => x.id)).toEqual(['c', 'd']); expect(withoutFollowUp([a, ...c], +new Date('2026-01-01')).map((x) => x.id)).toEqual(['d', 'e']); });
  it('catena del deposito', async () => { const h1 = await depositHash('', 'x'); const h2 = await depositHash(h1, 'y'); expect(chainOk([{ date: '2025-01-02', hash: h2, prev: h1 }, { date: '2025-01-01', hash: h1, prev: '' }]).ok).toBe(true); expect(chainOk([{ date: '2025-01-01', hash: h1, prev: '' }, { date: '2025-01-02', hash: h2, prev: 'altro' }]).brokenAt).toBe('2025-01-02'); });
  it('giorno a caso pesato', () => { expect(randomDay([], 0.5)).toBeNull(); expect(randomDay([{ day: 'a', n: 1 }, { day: 'b', n: 9 }], 0.05)).toBe('a'); expect(randomDay([{ day: 'a', n: 1 }, { day: 'b', n: 9 }], 0.5)).toBe('b'); });
});
