import { describe, expect, it } from 'vitest';
import { basket, budgetTree, compassScore, councilMatrix, delayDays, delayStats, parseLines, parseResults, seriesStats, parsePoints, cardSlug } from '../src/lib/civic';

describe('politica locale e dati civici', () => {
  it('voti nominali → matrice consigliere × delibera', () => { const m = councilMatrix([{ id: 'd1', title: 'A', votes: 'Rossi: favorevole\nBianchi: contrario' }, { id: 'd2', title: 'B', votes: 'Rossi: assente\nVerdi: astenuto' }]); expect(m.names).toEqual(['Bianchi', 'Rossi', 'Verdi']); expect(m.rows.find((r) => r.name === 'Rossi')?.votes).toEqual(['favorevole', 'assente']); expect(m.rows.find((r) => r.name === 'Verdi')?.votes).toEqual(['', 'astenuto']); });
  it('bussola: coincidenze piene e mezze', () => { const r = compassScore({ ztl: 'si', piscina: 'no', tram: 'forse' }, [{ title: 'A', slug: 'a', risposte: 'ztl=si\npiscina=si\ntram=no' }, { title: 'B', slug: 'b', risposte: 'ztl=si\npiscina=no' }]); expect(r[0]).toMatchObject({ slug: 'b', percent: 100, total: 2 }); expect(r[1]).toMatchObject({ slug: 'a', percent: 50, total: 3 }); });
  it('risultati, ritardi e slug', () => { expect(parseResults('Lista Uno: 1.200\nLista Due: 800')[0]).toMatchObject({ list: 'Lista Uno', votes: 1200, percent: 60 }); expect(delayDays('2026-01-01', undefined, +new Date('2026-01-31'))).toBe(30); expect(delayDays('2026-03-01', '2026-02-20', 0)).toBe(-9); expect(delayDays(undefined, undefined, 0)).toBeNull(); expect(cardSlug('Via Roma, 12 (centro)')).toBe('via-roma-12-centro'); expect(parseLines('a: 1\nb\n\nc: x: y')).toEqual([{ k: 'a', v: '1' }, { k: 'b', v: '' }, { k: 'c', v: 'x: y' }]); });
  it('bilancio ad albero per anno', () => { const b = budgetTree('2025;Uscite;Scuola;Mense;1.000,50\n2025;Uscite;Scuola;Edifici;500\n2025;Entrate;Tributi;IMU;3000\n2024;Uscite;Scuola;Mense;900', '2025'); expect(b.years).toEqual(['2024', '2025']); expect(b.total).toEqual({ Uscite: 1500.5, Entrate: 3000 }); expect(b.tree.find((n) => n.name === 'Uscite')?.children[0]).toMatchObject({ name: 'Scuola', amount: 1500.5 }); expect(budgetTree('', '').tree).toEqual([]); });
  it('serie: anomalia oltre due deviazioni, trend, punti da testo', () => { const pts = parsePoints('2026-01;10\n2026-02;11\n2026-03;10\n2026-04;9\n2026-05;10\n2026-06;30'); expect(pts).toHaveLength(6); const s = seriesStats(pts); expect(s.anomaly).toBe(true); expect(s.trend).toBe('su'); expect(seriesStats(pts.slice(0, 5)).anomaly).toBe(false); expect(seriesStats([]).n).toBe(0); });
  it('paniere e ritardi', () => { const b = basket([{ product: 'Pane', price: 3, date: '2026-09-21' }, { product: 'Pane', price: 5, date: '2026-09-23' }, { product: 'Pane', price: 4, date: '2026-09-14' }], '2026-09-21'); expect(b[0]).toMatchObject({ product: 'Pane', median: 4, prevMedian: 4, delta: 0, samples: 2 }); const d = delayStats([{ line: '12', time: '08:10', kind: 'Ritardo', minutes: 10 }, { line: '12', time: '08:40', kind: 'Corsa saltata', minutes: 0 }, { line: '3', time: '17:00', kind: 'Ritardo', minutes: 4 }]); expect(d[0]).toMatchObject({ line: '12', reports: 2, skipped: 1, avgDelay: 10, worstHour: '08:00' }); });
});
