import { describe, expect, it } from 'vitest';
import { articleEconomics, co2Grams, co2Rating, fairPrice, inQuietHours, isNight, meaningScore, redirectMap, workload } from '../src/lib/rhythm';

describe('sostenibilità', () => {
  it('CO₂ per pagina e notte', () => { expect(co2Grams(1_000_000)).toBeCloseTo(0.269, 2); expect(co2Rating(0.05)).toBe('A'); expect(co2Rating(0.9)).toBe('E'); expect(isNight(23)).toBe(true); expect(isNight(3)).toBe(true); expect(isNight(12)).toBe(false); });
  it('orari di quiete anche a cavallo della mezzanotte', () => { expect(inQuietHours('22:00', '07:30', '23:15')).toBe(true); expect(inQuietHours('22:00', '07:30', '06:59')).toBe(true); expect(inQuietHours('22:00', '07:30', '12:00')).toBe(false); expect(inQuietHours('13:00', '14:00', '13:30')).toBe(true); expect(inQuietHours(undefined, '07:00', '03:00')).toBe(false); });
  it('sovraccarico: segnala chi ha troppo e dice perché', () => { const r = workload([{ userId: 'a', name: 'Anna', openDrafts: 9, dueSoon: 3, overdue: 1, publishedWeek: 5, handoffs: 0 }, { userId: 'b', name: 'Bruno', openDrafts: 2, dueSoon: 0, overdue: 0, publishedWeek: 3, handoffs: 0 }]); expect(r[0]).toMatchObject({ userId: 'a', level: 'troppo' }); expect(r[0].reasons).toHaveLength(3); expect(r[1].level).toBe('ok'); });
  it('costo reale di un articolo, con la quota alla fonte', () => { expect(articleEconomics({ hours: 10, expenses: 40, views: 8000, subscriptions: 3, sourceShare: 10 }, { hourlyRate: 20, rpm: 4, subscriptionValue: 50 })).toEqual({ cost: 240, revenue: 182, margin: -73, owedToSource: 15, perReader: 0.03 }); });
  it('prezzo libero sensato: tra il minimo e il pieno, al mezzo euro', () => { expect(fairPrice(0, 6).suggested).toBe(1); expect(fairPrice(60, 6).suggested).toBe(3.5); expect(fairPrice(600, 6).suggested).toBe(6); expect(fairPrice(60, 6).label).toBe('leggi ogni tanto'); });
  it('metriche di senso: contano i gesti, non i clic', () => { const base = { id: 'a', title: 't', saves: 0, thanks: 0, highlights: 0, mindChanged: 0, mindTotal: 0, responses: 0 }; const viral = meaningScore({ ...base, views: 50000, ends: 2000 }); const deep = meaningScore({ ...base, views: 400, ends: 300, saves: 12, thanks: 4, mindChanged: 5, mindTotal: 10, responses: 1 }); expect(deep.score).toBeGreaterThan(viral.score * 5); expect(deep.endRate).toBe(0.75); expect(meaningScore({ ...base, views: 5, ends: 5 }).endRate).toBeNull(); });
  it('mappa dei redirect per altri sistemi', () => { const p = [{ from: '/a/b', to: '/b' }, { from: '/same', to: '/same' }]; expect(redirectMap(p, 'netlify')).toBe('/a/b  /b  301\n'); expect(redirectMap(p, 'apache')).toBe('Redirect 301 /a/b /b\n'); expect(redirectMap(p, 'nginx')).toContain('rewrite ^/a/b/?$ /b permanent;'); expect(redirectMap(p, 'csv')).toBe('da,a\n/a/b,/b\n'); });
});
