import { getCurrentUser } from '@/lib/auth';
import { can } from '@/lib/permissions';
import { findArticle, listCategories } from '@/lib/repo';
import { getSettings } from '@/lib/queries';
import { sponsorReport } from '@/lib/insights';
import { siteUrl } from '@/lib/site-url';

export const dynamic = 'force-dynamic';
const esc = (s: string) => s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));
/** Report per l'inserzionista di un contenuto sponsorizzato: pagina pronta per «Salva come PDF». */
export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const me = await getCurrentUser(); if (!me || !can(me, 'stats.view')) return new Response('Non autorizzato', { status: 401 });
  const a = await findArticle(id); if (!a) return new Response('Non trovato', { status: 404 });
  const [r, s, cats] = await Promise.all([sponsorReport(id, 90), getSettings(), listCategories()]); const url = `${siteUrl()}/${cats.find((c) => c.id === a.categoryId)?.slug ?? 'notizie'}/${a.slug}`;
  const max = Math.max(1, ...r.byDay.map((d) => d.views)); const mins = `${Math.floor(r.readSec / 60)}:${String(r.readSec % 60).padStart(2, '0')}`;
  const bars = r.byDay.map((d) => `<div title="${d.day}: ${d.views}" style="flex:1;background:#22418f;height:${Math.max(2, (d.views / max) * 100)}%"></div>`).join('');
  const html = `<!doctype html><html lang="it"><head><meta charset="utf-8"><title>Report · ${esc(a.title)}</title><style>@page{size:A4;margin:16mm}body{font-family:Helvetica,Arial,sans-serif;color:#111;max-width:760px;margin:0 auto;padding:24px}h1{font-size:24px;margin:4px 0 2px}.k{color:#c00;font-size:11px;letter-spacing:.12em;text-transform:uppercase;font-weight:700}.meta{color:#666;font-size:13px;margin-bottom:20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:16px 0}.stat{border:1px solid #ddd;padding:14px}.stat b{display:block;font-size:30px}.stat span{font-size:12px;color:#666;text-transform:uppercase;letter-spacing:.06em}.chart{display:flex;align-items:flex-end;gap:2px;height:140px;border-bottom:1px solid #999;margin:8px 0 4px}table{width:100%;border-collapse:collapse;font-size:14px}td{padding:6px 0;border-bottom:1px solid #eee}td:last-child{text-align:right;font-weight:700}.foot{margin-top:24px;font-size:11px;color:#777}@media print{.noprint{display:none}}</style></head><body><p class="noprint" style="background:#fff3cd;padding:8px 12px;font-size:13px">Per il PDF: Stampa → «Salva come PDF». <button onclick="window.print()">Stampa</button></p><div class="k">Report contenuto sponsorizzato · ${esc(s.siteName)}</div><h1>${esc(a.title)}</h1><div class="meta">${esc(url)}<br>Pubblicato il ${a.publishedAt ? new Date(a.publishedAt).toLocaleDateString('it-IT') : '—'} · dati degli ultimi 90 giorni, aggiornati al ${new Date().toLocaleDateString('it-IT')}</div><div class="grid"><div class="stat"><b>${r.views.toLocaleString('it-IT')}</b><span>visualizzazioni</span></div><div class="stat"><b>${mins}</b><span>tempo medio di lettura</span></div><div class="stat"><b>${r.byDay.length}</b><span>giorni con letture</span></div></div><h3>Andamento giornaliero</h3><div class="chart">${bars || '<span style="color:#999;font-size:13px">Nessuna lettura registrata</span>'}</div><div style="display:flex;justify-content:space-between;font-size:11px;color:#666"><span>${r.byDay[0]?.day ?? ''}</span><span>${r.byDay[r.byDay.length - 1]?.day ?? ''}</span></div><h3>Da dove sono arrivati i lettori</h3><table>${r.bySource.map((x) => `<tr><td>${esc(x.source)}</td><td>${x.views.toLocaleString('it-IT')}</td></tr>`).join('')}</table><div class="foot">Statistiche interne di ${esc(s.siteName)}: conteggio senza cookie né profilazione, una visualizzazione per caricamento di pagina, tempo di lettura misurato all'uscita.</div></body></html>`;
  return new Response(html, { headers: { 'Content-Type': 'text/html; charset=utf-8' } });
}
