import { requirePermission } from '@/lib/auth';
import { a11yAudits, lastByteAudit, peerFeeds } from '@/lib/platform-data';
import { getSettings } from '@/lib/queries';
import { ImageCheck, PeerImport, PlatformSettings } from '@/components/admin/platform-admin';

export const dynamic = 'force-dynamic';
export default async function PlatformPage() {
  await requirePermission('settings.manage'); const [s, peers, bytes, a11y] = await Promise.all([getSettings(), peerFeeds(), lastByteAudit(), a11yAudits(1)]);
  return <><div className="page-title"><div><h1>Piattaforma</h1><p>Rete di testate e scambio articoli, parole locali, budget di byte, verifica delle immagini, copia su rete locale, audit di accessibilità, manuale.</p></div></div><div className="admin-grid-2"><PlatformSettings initial={{ peers: s.network?.peers ?? [], uiWords: s.uiWords ?? {}, byteBudgetKb: s.platform?.byteBudgetKb ?? 0 }} /><PeerImport peers={peers} /></div><div className="admin-grid-2"><ImageCheck /><div className="panel"><div className="panel-title">Misure</div>{bytes ? <><p><b>Budget di byte</b> ({bytes.data.budgetKb} kB) · misurato il {bytes.createdAt.slice(0, 10)}: {bytes.data.over.length === 0 ? 'tutte le pagine entro il tetto' : `${bytes.data.over.length} oltre`}</p>{bytes.data.over.length > 0 && <ul className="help">{bytes.data.over.map((o) => <li key={o.path}><code>{o.path}</code> {Math.round(o.bytes / 1024)} kB ({o.pct}%)</li>)}</ul>}</> : <p className="help">Nessuna misura dei byte (imposta un budget e misura).</p>}{a11y[0] ? <p><b>Accessibilità</b> {a11y[0].month}: punteggio {a11y[0].score}/100, {a11y[0].errors} errori, {a11y[0].warns} avvisi · <a href="/accessibilita" target="_blank">pagina pubblica</a></p> : <p className="help">Nessun audit di accessibilità ancora (parte il primo del mese, o con «Misura adesso»).</p>}<hr /><p><b>Copia su rete locale</b>: <a href="/api/export/statico?limite=300&nome=copia-locale">scarica lo ZIP degli ultimi 300 articoli</a> (HTML puro) e servilo da un computer o un Raspberry in rete locale:</p><pre className="help" style={{ whiteSpace: 'pre-wrap' }}>unzip copia-locale-*.zip -d sito && cd sito && python3 -m http.server 8080</pre><p className="help">Chi è connesso allo stesso wi-fi (un hotspot in piazza, la rete della scuola) legge il giornale anche senza internet.</p><p><b>Manuale</b>: <a href="/admin/manuale">generato dal codice</a> · <a href="/admin/manuale?md=1">in Markdown</a></p><p><b>Solo testo</b>: <a href="/1k" target="_blank">/1k</a> (una pagina da un kilobyte).</p></div></div></>;
}
