'use client';
import { useState, useTransition } from 'react';
import { toast } from '@/components/ui/toaster';
import { newsletterFromNotesAction, saveAiPolicyAction } from '@/lib/actions-outputs';

export function AiPolicyForm({ notes: n0, allowTraining: a0 }: { notes: string; allowTraining: boolean }) {
  const [notes, setNotes] = useState(n0); const [allow, setAllow] = useState(a0); const [pending, start] = useTransition();
  return <div className="panel"><div className="panel-title">Cosa diciamo agli assistenti AI <a className="help" href="/llms.txt" target="_blank">apri /llms.txt</a></div><p className="help">Il file spiega ai modelli come citarci e cosa non riassumere. È un invito: i divieti veri per i crawler restano in robots.txt.</p><label className="switch"><input type="checkbox" checked={allow} onChange={(e) => setAllow(e.target.checked)} /> Consentiamo l&apos;uso dei testi per addestrare modelli (citando la fonte)</label><textarea className="textarea" style={{ minHeight: 70, marginTop: 8 }} aria-label="Note per gli assistenti AI" placeholder="Note in più: chi siamo, come preferiamo essere citati, temi su cui chiediamo cautela" value={notes} onChange={(e) => setNotes(e.target.value)} /><button type="button" className="btn btn-primary btn-sm" style={{ marginTop: 8 }} disabled={pending} onClick={() => start(async () => { const r = await saveAiPolicyAction(notes, allow); (r.ok ? toast.success : toast.error)(r.message ?? ''); })}>Salva</button></div>;
}
export function NewsletterFromNotes() {
  const [d, setD] = useState<{ subject: string; html: string } | null>(null); const [pending, start] = useTransition();
  return <div className="panel"><div className="panel-title">La newsletter che si scrive dalle tue note</div><p className="help">Prende gli appunti degli ultimi sette giorni e ciò che hai pubblicato, e ne fa una bozza di lettera. A te restano dieci minuti di rifinitura.</p><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => start(async () => { const r = await newsletterFromNotesAction(); if (r.ok && r.data) { setD(r.data); toast.success(r.message ?? 'Bozza pronta.'); } else toast.error(r.message ?? ''); })}>{pending ? 'Scrivo la bozza…' : 'Scrivi la bozza di questa settimana'}</button>
    {d && <div style={{ marginTop: 10 }}><div className="field"><label htmlFor="nfn-subject">Oggetto</label><input id="nfn-subject" className="input" value={d.subject} onChange={(e) => setD({ ...d, subject: e.target.value })} /></div><div className="field"><label htmlFor="nfn-html">Testo (HTML)</label><textarea id="nfn-html" className="textarea" style={{ minHeight: 220, fontSize: 13 }} value={d.html} onChange={(e) => setD({ ...d, html: e.target.value })} /></div><div style={{ display: 'flex', gap: 6 }}><button type="button" className="btn btn-ghost btn-sm" onClick={() => navigator.clipboard?.writeText(d.html).then(() => toast.success('Copiato: incollalo in Newsletter → Nuovo invio.'))}>Copia il testo</button><a className="btn btn-outline btn-sm" href="/admin/newsletter">Vai alla newsletter</a></div></div>}</div>;
}
