'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import { dismissFollowUpAction, runDepositNowAction, saveArchiveSettingsAction } from '@/lib/actions-archive';

export function ArchiveSettings({ initial, deposits, chain }: { initial: { depositEnabled: boolean; depositEmail: string }; deposits: { date: string; n: number; hash: string; url?: string }[]; chain: { ok: boolean; brokenAt: string | null; n: number } }) {
  const [a, setA] = useState(initial); const [pending, start] = useTransition(); const router = useRouter();
  const run = (fn: () => Promise<{ ok: boolean; message?: string }>) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); router.refresh(); });
  return <div className="panel"><div className="panel-title">Deposito legale digitale <a className="help" href="/deposito" target="_blank">pagina pubblica</a></div><label className="switch"><input type="checkbox" checked={a.depositEnabled} onChange={(e) => setA({ ...a, depositEnabled: e.target.checked })} /> Ogni notte deposita i giorni mancanti (impronta concatenata + fascicolo nello storage)</label><div className="field" style={{ marginTop: 8 }}><label htmlFor="ar-mail">Email dell&apos;archivio esterno (biblioteca, università, notaio): riceve il fascicolo in allegato</label><input id="ar-mail" className="input" type="email" placeholder="deposito@biblioteca.it" value={a.depositEmail} onChange={(e) => setA({ ...a, depositEmail: e.target.value })} /></div><div style={{ display: 'flex', gap: 6, marginTop: 8 }}><button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => run(() => saveArchiveSettingsAction(a))}>Salva</button><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(runDepositNowAction)}>Deposita adesso</button></div><p className={chain.ok ? 'help' : 'error-text'} style={{ marginTop: 8 }}>{chain.n} giorni depositati · catena {chain.ok ? 'integra' : `rotta al ${chain.brokenAt}`}</p>{deposits.length > 0 && <table className="table"><tbody>{deposits.slice(0, 10).map((d) => <tr key={d.date}><td>{d.date}</td><td>{d.n} art.</td><td><code>{d.hash.slice(0, 12)}…</code></td><td>{d.url ? <a href={d.url} target="_blank" rel="noopener">copia</a> : <span className="help">solo impronta</span>}</td></tr>)}</tbody></table>}</div>;
}
export function NoFollowUp({ list }: { list: { id: string; title: string; publishedAt: string; views: number; url: string }[] }) {
  const [pending, start] = useTransition(); const router = useRouter();
  return <div className="panel"><div className="panel-title">Storie senza seguito ({list.length})</div><p className="help">Pezzi letti, usciti da più di sei mesi, cui non è seguito nessun articolo sullo stesso argomento. Che fine ha fatto?</p>{list.length === 0 && <p className="help">Nessuna: tutto ha avuto un seguito, o non c&apos;è abbastanza archivio.</p>}<table className="table"><tbody>{list.map((a) => <tr key={a.id}><td className="t-title"><a href={a.url} target="_blank">{a.title}</a><div className="help">{a.publishedAt.slice(0, 10)} · {a.views} letture</div></td><td style={{ textAlign: 'right', whiteSpace: 'nowrap' }}><a className="btn btn-outline btn-sm" href={`/admin/articoli/nuovo?seguito=${a.id}`}>Scrivi il seguito</a> <button type="button" className="btn btn-ghost btn-sm" disabled={pending} onClick={() => start(async () => { await dismissFollowUpAction(a.id); router.refresh(); })}>Non serve</button></td></tr>)}</tbody></table></div>;
}
