'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import { CARD_KINDS, type Card } from '@/lib/civic';
import { addCardEventAction, cardCommitmentAction, deleteCardAction, saveCardAction } from '@/lib/actions-civic';

const EMPTY = (kind: string): Card => ({ id: '', kind, slug: '', title: '', fields: {}, body: '', tagId: '', image: '' });
export function CardsManager({ cards, tags }: { cards: Card[]; tags: { id: string; name: string }[] }) {
  const [kind, setKind] = useState('cantiere'); const [c, setC] = useState<Card>(EMPTY('cantiere')); const [ev, setEv] = useState({ date: new Date().toISOString().slice(0, 10), text: '', image: '' }); const [cm, setCm] = useState({ kind: 'promise' as 'promise' | 'prediction', text: '', due: '', who: '' }); const [pending, start] = useTransition(); const router = useRouter(); const def = CARD_KINDS[kind];
  const run = (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } });
  return (
    <div className="admin-grid-2">
      <div className="panel"><div className="panel-title">Schede</div>
        <select className="select" aria-label="Tipo di scheda" value={kind} onChange={(e) => { setKind(e.target.value); setC(EMPTY(e.target.value)); }}>{Object.entries(CARD_KINDS).map(([k, d]) => <option key={k} value={k}>{d.icon} {d.plural}</option>)}</select><p className="help">{def.hint}</p>
        <table className="table"><tbody>{cards.filter((x) => x.kind === kind).map((x) => <tr key={x.id}><td className="t-title"><a href="#" onClick={(e) => { e.preventDefault(); setC(x); }}>{x.title}</a><div className="help"><a href={`/schede/${x.kind}/${x.slug}`} target="_blank">apri</a></div></td><td style={{ textAlign: 'right' }}><button type="button" className="icon-btn danger" aria-label={`Elimina ${x.title}`} onClick={() => { if (confirm('Eliminare la scheda?')) run(() => deleteCardAction(x.id), () => setC(EMPTY(kind))); }}>✕</button></td></tr>)}{cards.filter((x) => x.kind === kind).length === 0 && <tr><td className="help">Nessuna scheda di questo tipo.</td></tr>}</tbody></table>
      </div>
      <div className="panel"><div className="panel-title">{c.id ? `Modifica: ${c.title}` : `Nuova scheda · ${def.name}`}</div>
        <div className="field"><label htmlFor="cd-title">Titolo</label><input id="cd-title" className="input" value={c.title} onChange={(e) => setC({ ...c, title: e.target.value })} /></div>
        {def.fields.map((f) => <div className="field" key={f.key}><label htmlFor={`cd-${f.key}`}>{f.label}</label>{f.type === 'textarea' ? <textarea id={`cd-${f.key}`} className="textarea" style={{ minHeight: 64 }} placeholder={f.hint} value={c.fields[f.key] ?? ''} onChange={(e) => setC({ ...c, fields: { ...c.fields, [f.key]: e.target.value } })} /> : f.type === 'select' ? <select id={`cd-${f.key}`} className="select" value={c.fields[f.key] ?? ''} onChange={(e) => setC({ ...c, fields: { ...c.fields, [f.key]: e.target.value } })}><option value="">—</option>{f.options!.map((o) => <option key={o}>{o}</option>)}</select> : <input id={`cd-${f.key}`} className="input" type={f.type === 'number' ? 'number' : f.type === 'date' ? 'date' : 'text'} placeholder={f.hint} value={c.fields[f.key] ?? ''} onChange={(e) => setC({ ...c, fields: { ...c.fields, [f.key]: e.target.value } })} />}{f.hint && f.type !== 'textarea' && <span className="help">{f.hint}</span>}</div>)}
        <div className="form-row"><div className="field"><label htmlFor="cd-img">Immagine (URL)</label><input id="cd-img" className="input" value={c.image} onChange={(e) => setC({ ...c, image: e.target.value })} /></div><div className="field"><label htmlFor="cd-tag">Argomento collegato (articoli)</label><select id="cd-tag" className="select" value={c.tagId} onChange={(e) => setC({ ...c, tagId: e.target.value })}><option value="">Cerca per titolo</option>{tags.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select></div></div>
        <div className="field"><label htmlFor="cd-body">Testo libero (HTML)</label><textarea id="cd-body" className="textarea" style={{ minHeight: 80 }} value={c.body} onChange={(e) => setC({ ...c, body: e.target.value })} /></div>
        <div style={{ display: 'flex', gap: 6 }}><button type="button" className="btn btn-primary btn-sm" disabled={pending || c.title.trim().length < 2} onClick={() => run(() => saveCardAction({ ...c, id: c.id || undefined }), () => setC(EMPTY(kind)))}>Salva scheda</button>{c.id && <button type="button" className="btn btn-ghost btn-sm" onClick={() => setC(EMPTY(kind))}>Nuova</button>}</div>
        {c.id && <><div className="panel-title" style={{ marginTop: 16 }}>Linea del tempo</div><div className="form-row"><input className="input" type="date" aria-label="Data" value={ev.date} onChange={(e) => setEv({ ...ev, date: e.target.value })} /><input className="input" placeholder="Cosa è successo" aria-label="Testo" value={ev.text} onChange={(e) => setEv({ ...ev, text: e.target.value })} /></div><input className="input" style={{ marginTop: 6 }} placeholder="Foto (URL, facoltativa)" aria-label="Foto" value={ev.image} onChange={(e) => setEv({ ...ev, image: e.target.value })} /><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 6 }} disabled={pending || ev.text.trim().length < 3} onClick={() => run(() => addCardEventAction(c.id, ev.date, ev.text, ev.image), () => setEv({ ...ev, text: '', image: '' }))}>Aggiungi voce</button>
          <div className="panel-title" style={{ marginTop: 16 }}>Impegno o previsione con scadenza</div><div className="form-row"><select className="select" aria-label="Tipo" value={cm.kind} onChange={(e) => setCm({ ...cm, kind: e.target.value as 'promise' | 'prediction' })}><option value="promise">Impegno (promessa)</option><option value="prediction">Previsione</option></select><input className="input" type="date" aria-label="Scadenza" value={cm.due} onChange={(e) => setCm({ ...cm, due: e.target.value })} /></div><input className="input" style={{ marginTop: 6 }} placeholder="Chi lo promette (vuoto = la scheda)" aria-label="Chi" value={cm.who} onChange={(e) => setCm({ ...cm, who: e.target.value })} /><input className="input" style={{ marginTop: 6 }} placeholder="es. Riapertura della piscina entro giugno" aria-label="Testo dell'impegno" value={cm.text} onChange={(e) => setCm({ ...cm, text: e.target.value })} /><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 6 }} disabled={pending || cm.text.trim().length < 8 || !cm.due} onClick={() => run(() => cardCommitmentAction(c.id, cm.kind, cm.text, cm.due, cm.who), () => setCm({ ...cm, text: '' }))}>Registra</button><p className="help">L&apos;esito si registra in Fiducia alla scadenza e resta visibile nella scheda.</p></>}
      </div>
    </div>
  );
}
