'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import type { CivicSettings } from '@/lib/models';
import { deleteSeriesAction, saveCivicSettingsAction, saveSeriesAction } from '@/lib/actions-civic';

export function SeriesManager({ series }: { series: { key: string; label: string; unit: string; source: string; points: { d: string; v: number }[] }[] }) {
  const empty = { key: '', label: '', unit: '', source: '', points: '' }; const [s, setS] = useState(empty); const [pending, start] = useTransition(); const router = useRouter();
  const run = (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } });
  return <div className="panel"><div className="panel-title">Serie di dati (cruscotto, fiumi, affitti…)</div><p className="help">Una riga per rilevazione: <code>AAAA-MM-GG;valore</code>. Quando l&apos;ultimo dato esce dalla norma, di notte nasce una bozza per la redazione.</p>
    <table className="table"><tbody>{series.map((x) => <tr key={x.key}><td className="t-title"><a href="#" onClick={(e) => { e.preventDefault(); setS({ key: x.key, label: x.label, unit: x.unit, source: x.source, points: x.points.map((p) => `${p.d};${p.v}`).join('\n') }); }}>{x.label}</a><div className="help"><code>{x.key}</code> · {x.points.length} rilevazioni{x.unit ? ` · ${x.unit}` : ''}</div></td><td style={{ textAlign: 'right' }}><button type="button" className="icon-btn danger" aria-label={`Elimina ${x.label}`} onClick={() => run(() => deleteSeriesAction(x.key))}>✕</button></td></tr>)}</tbody></table>
    <div className="form-row"><input className="input" placeholder="chiave (es. incidenti)" aria-label="Chiave della serie" value={s.key} onChange={(e) => setS({ ...s, key: e.target.value })} /><input className="input" placeholder="Etichetta" aria-label="Etichetta" value={s.label} onChange={(e) => setS({ ...s, label: e.target.value })} /></div><div className="form-row" style={{ marginTop: 6 }}><input className="input" placeholder="Unità (es. µg/m³)" aria-label="Unità" value={s.unit} onChange={(e) => setS({ ...s, unit: e.target.value })} /><input className="input" placeholder="Fonte" aria-label="Fonte" value={s.source} onChange={(e) => setS({ ...s, source: e.target.value })} /></div><textarea className="textarea" style={{ minHeight: 100, marginTop: 6, fontFamily: 'monospace', fontSize: 12 }} aria-label="Rilevazioni" placeholder={'2026-01-01;12\n2026-02-01;14'} value={s.points} onChange={(e) => setS({ ...s, points: e.target.value })} /><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 6 }} disabled={pending} onClick={() => run(() => saveSeriesAction(s), () => setS(empty))}>Salva serie</button></div>;
}
export function CivicForm({ initial }: { initial: CivicSettings }) {
  const [c, setC] = useState<CivicSettings>({ budget: '', basketItems: '', busLines: '', electionTitle: '', councilUrl: '', ...initial }); const [pending, start] = useTransition();
  return <div className="panel"><div className="panel-title">Bilancio, paniere, elezioni, consiglio</div>
    <div className="field"><label htmlFor="cv-budget">Bilancio comunale (una riga per voce: <code>Anno;Entrate|Uscite;Voce;Sottovoce;Importo</code>)</label><textarea id="cv-budget" className="textarea" style={{ minHeight: 140, fontFamily: 'monospace', fontSize: 12 }} placeholder={'2025;Uscite;Istruzione;Mense scolastiche;1.250.000\n2025;Entrate;Tributi;IMU;9.800.000'} value={c.budget} onChange={(e) => setC({ ...c, budget: e.target.value })} /></div>
    <div className="form-row"><div className="field"><label htmlFor="cv-basket">Prodotti del paniere (separati da virgola)</label><input id="cv-basket" className="input" placeholder="pane, latte, uova, pasta, caffè" value={c.basketItems} onChange={(e) => setC({ ...c, basketItems: e.target.value })} /></div><div className="field"><label htmlFor="cv-lines">Linee del trasporto pubblico</label><input id="cv-lines" className="input" placeholder="3, 12, 21, 40" value={c.busLines} onChange={(e) => setC({ ...c, busLines: e.target.value })} /></div></div>
    <div className="form-row"><div className="field"><label htmlFor="cv-el">Titolo della pagina elezioni</label><input id="cv-el" className="input" placeholder="Comunali 2026" value={c.electionTitle} onChange={(e) => setC({ ...c, electionTitle: e.target.value })} /></div><div className="field"><label htmlFor="cv-council">Diretta del consiglio (URL)</label><input id="cv-council" className="input" value={c.councilUrl} onChange={(e) => setC({ ...c, councilUrl: e.target.value })} /></div></div>
    <button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => start(async () => { const r = await saveCivicSettingsAction(c); (r.ok ? toast.success : toast.error)(r.message ?? ''); })}>Salva</button></div>;
}
