'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import type { CommonsSettings } from '@/lib/models';
import { councilUpdateAction, grantSuspendedAction, saveCommonsAction, saveRoundAction, verifyLogAction } from '@/lib/actions-commons';

const useRun = () => { const [pending, start] = useTransition(); const router = useRouter(); return { pending, run: (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } }) }; };
type Round = { title: string; intro: string; options: { id: string; title: string; desc: string }[]; closesAt: string; subscribersOnly: boolean; open: boolean };
export function RoundsManager({ rounds }: { rounds: { id: string; data: Round; votes: number }[] }) {
  const empty: Round = { title: '', intro: '', options: [{ id: '', title: '', desc: '' }, { id: '', title: '', desc: '' }], closesAt: '', subscribersOnly: false, open: true }; const [id, setId] = useState(''); const [r, setR] = useState(empty); const { pending, run } = useRun(); const opt = (i: number, p: Partial<Round['options'][number]>) => setR({ ...r, options: r.options.map((o, j) => (j === i ? { ...o, ...p } : o)) });
  return <div className="panel"><div className="panel-title">Assemblea dei lettori <a className="help" href="/assemblea" target="_blank">apri</a></div>{rounds.map((x) => <p key={x.id}><a href="#" onClick={(e) => { e.preventDefault(); setId(x.id); setR(x.data); }}>{x.data.title}</a> <span className="help">{x.data.open ? 'aperta' : 'chiusa'} · {x.votes} voti</span></p>)}
    <div className="field"><label htmlFor="rd-title">Su cosa si vota</label><input id="rd-title" className="input" placeholder="es. Quale inchiesta facciamo a ottobre?" value={r.title} onChange={(e) => setR({ ...r, title: e.target.value })} /></div><textarea className="textarea" style={{ minHeight: 50 }} aria-label="Spiegazione" placeholder="Perché chiediamo ai lettori e cosa succede dopo" value={r.intro} onChange={(e) => setR({ ...r, intro: e.target.value })} />
    {r.options.map((o, i) => <div key={i} className="source-row"><input className="input" placeholder={`Proposta ${i + 1}`} aria-label={`Titolo della proposta ${i + 1}`} value={o.title} onChange={(e) => opt(i, { title: e.target.value })} /><input className="input" placeholder="In una riga: cosa scopriremmo" aria-label={`Descrizione della proposta ${i + 1}`} value={o.desc} onChange={(e) => opt(i, { desc: e.target.value })} /></div>)}
    <div className="form-row" style={{ marginTop: 6 }}><input className="input" type="date" aria-label="Chiusura della votazione" value={r.closesAt.slice(0, 10)} onChange={(e) => setR({ ...r, closesAt: e.target.value })} /><label className="switch"><input type="checkbox" checked={r.subscribersOnly} onChange={(e) => setR({ ...r, subscribersOnly: e.target.checked })} /> Solo abbonati</label><label className="switch"><input type="checkbox" checked={r.open} onChange={(e) => setR({ ...r, open: e.target.checked })} /> Aperta</label></div>
    <div style={{ display: 'flex', gap: 6, marginTop: 8 }}><button type="button" className="btn btn-ghost btn-sm" onClick={() => setR({ ...r, options: [...r.options, { id: '', title: '', desc: '' }] })}>+ Proposta</button><button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => run(() => saveRoundAction(id, r), () => { setId(''); setR(empty); })}>Salva votazione</button></div></div>;
}
export function CouncilRow({ id, text, sentAt, answer }: { id: string; text: string; sentAt?: string; answer?: string }) {
  const [a, setA] = useState(answer ?? ''); const [d, setD] = useState(sentAt?.slice(0, 10) ?? new Date().toISOString().slice(0, 10)); const { pending, run } = useRun();
  return <div className="reply-item"><p>{text}</p>{!sentAt ? <div className="settle"><input className="input" type="date" aria-label="Inoltrata il" value={d} onChange={(e) => setD(e.target.value)} /><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(() => councilUpdateAction(id, { sentAt: d }))}>Inoltrata al Comune: parte il contatore</button></div> : <div className="settle"><input className="input" placeholder="Risposta del Comune (sarà pubblica)" aria-label="Risposta del Comune" value={a} onChange={(e) => setA(e.target.value)} /><button type="button" className="btn btn-outline btn-sm" disabled={pending || a.trim().length < 5} onClick={() => run(() => councilUpdateAction(id, { answer: a }))}>Pubblica la risposta</button><span className="help">inoltrata il {new Date(sentAt).toLocaleDateString('it-IT')}</span></div>}</div>;
}
export function RowButton({ id, action, label }: { id: string; action: 'verify' | 'grant'; label: string }) { const { pending, run } = useRun(); return <button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(() => (action === 'verify' ? verifyLogAction(id) : grantSuspendedAction(id)))}>{label}</button>; }
const DAYS = ['Domenica', 'Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato'];
export function CommonsForm({ initial, siteSlug }: { initial: CommonsSettings; siteSlug: string }) {
  const [c, setC] = useState<CommonsSettings>({ partners: [], suspendedPool: 0, ...initial }); const { pending, run } = useRun(); const L = c.listening ?? { enabled: false, weekday: 4, time: '18:00', url: `https://meet.jit.si/${siteSlug}-ore-di-ascolto`, note: '' }; const partner = (i: number, p: Partial<NonNullable<CommonsSettings['partners']>[number]>) => setC({ ...c, partners: (c.partners ?? []).map((x, j) => (j === i ? { ...x, ...p } : x)) });
  return <div className="panel"><div className="panel-title">Ore di ascolto, abbonamenti sospesi, tessera</div>
    <label className="switch"><input type="checkbox" checked={L.enabled} onChange={(e) => setC({ ...c, listening: { ...L, enabled: e.target.checked } })} /> Ore di ascolto in calendario</label><div className="form-row" style={{ marginTop: 6 }}><select className="select" aria-label="Giorno della settimana" value={L.weekday} onChange={(e) => setC({ ...c, listening: { ...L, weekday: Number(e.target.value) } })}>{DAYS.map((d, i) => <option key={d} value={i}>{d}</option>)}</select><input className="input" type="time" aria-label="Ora" value={L.time} onChange={(e) => setC({ ...c, listening: { ...L, time: e.target.value } })} /></div><input className="input" style={{ marginTop: 6 }} aria-label="Indirizzo della stanza" placeholder="https://… (stanza audio o video)" value={L.url} onChange={(e) => setC({ ...c, listening: { ...L, url: e.target.value } })} /><input className="input" style={{ marginTop: 6 }} aria-label="Nota" placeholder="Nota (es. questa settimana parliamo di trasporti)" value={L.note} onChange={(e) => setC({ ...c, listening: { ...L, note: e.target.value } })} />
    <div className="field" style={{ marginTop: 14 }}><label htmlFor="cm-pool">Abbonamenti sospesi disponibili (aggiungine uno per ogni donazione «sospeso»)</label><input id="cm-pool" className="input" type="number" min={0} style={{ maxWidth: 120 }} value={c.suspendedPool ?? 0} onChange={(e) => setC({ ...c, suspendedPool: Number(e.target.value) })} /></div>
    <div className="panel-title" style={{ marginTop: 14 }}>Dove vale la tessera <button type="button" className="btn btn-outline btn-sm" onClick={() => setC({ ...c, partners: [...(c.partners ?? []), { name: '', benefit: '', address: '' }] })}>+ Negozio</button></div>{(c.partners ?? []).map((p, i) => <div key={i} className="source-row"><input className="input" placeholder="Nome" aria-label="Nome del negozio" value={p.name} onChange={(e) => partner(i, { name: e.target.value })} /><input className="input" placeholder="Vantaggio (es. 10% sui libri)" aria-label="Vantaggio" value={p.benefit} onChange={(e) => partner(i, { benefit: e.target.value })} /><input className="input" placeholder="Indirizzo" aria-label="Indirizzo" value={p.address} onChange={(e) => partner(i, { address: e.target.value })} /><button type="button" className="icon-btn danger" aria-label="Rimuovi negozio" onClick={() => setC({ ...c, partners: (c.partners ?? []).filter((_, j) => j !== i) })}>✕</button></div>)}
    <button type="button" className="btn btn-primary" style={{ marginTop: 10 }} disabled={pending} onClick={() => run(() => saveCommonsAction({ ...c, listening: L }))}>Salva</button></div>;
}
