'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import { dossierDeleteAction, dossierSaveAction, dossierSummaryAction, type Dossier } from '@/lib/actions-method';

export function Dossiers({ list, tags }: { list: (Dossier & { id: string; owner: string })[]; tags: { id: string; name: string }[] }) {
  const empty: Dossier = { title: '', slug: '', tagId: '', people: '', timeline: '', docs: '', notes: '', status: 'aperto' }; const [id, setId] = useState(''); const [d, setD] = useState<Dossier>(empty); const [pending, start] = useTransition(); const router = useRouter(); const cur = list.find((x) => x.id === id);
  const run = (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } });
  return <div className="admin-grid-2"><div className="panel"><div className="panel-title">Fascicoli</div>{list.length === 0 && <p className="help">Nessun fascicolo.</p>}<table className="table"><tbody>{list.map((x) => <tr key={x.id}><td className="t-title"><a href="#" onClick={(e) => { e.preventDefault(); setId(x.id); setD({ title: x.title, slug: x.slug, tagId: x.tagId, people: x.people, timeline: x.timeline, docs: x.docs, notes: x.notes, status: x.status }); }}>{x.title}</a><div className="help">{x.status}{x.summary ? ' · con riassunto' : ''}</div></td><td style={{ textAlign: 'right' }}><button type="button" className="icon-btn danger" aria-label="Elimina" onClick={() => { if (confirm('Eliminare il fascicolo?')) run(() => dossierDeleteAction(x.id), () => setId('')); }}>✕</button></td></tr>)}</tbody></table></div>
    <div className="panel"><div className="panel-title">{id ? 'Fascicolo' : 'Nuovo fascicolo'}</div>{cur?.summary && <div className="riguarda" style={{ whiteSpace: 'pre-line', marginBottom: 10 }}><b>Riassunto</b><br />{cur.summary}</div>}<div className="form-row"><input className="input" placeholder="Titolo della vicenda" aria-label="Titolo" value={d.title} onChange={(e) => setD({ ...d, title: e.target.value })} /><select className="select" aria-label="Argomento collegato" value={d.tagId} onChange={(e) => setD({ ...d, tagId: e.target.value })}><option value="">Argomento…</option>{tags.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select><select className="select" aria-label="Stato" value={d.status} onChange={(e) => setD({ ...d, status: e.target.value as Dossier['status'] })}><option value="aperto">Aperto</option><option value="fermo">Fermo</option><option value="chiuso">Chiuso</option></select></div>{(['people', 'timeline', 'docs', 'notes'] as const).map((k) => <textarea key={k} className="textarea" style={{ minHeight: 70, marginTop: 6 }} aria-label={k} placeholder={{ people: 'Persone (una per riga: nome, ruolo, contatto, cosa sa)', timeline: 'Cronologia (una per riga: data, fatto, fonte)', docs: 'Documenti (una per riga: titolo, dove sta, cosa prova)', notes: 'Note di lavoro' }[k]} value={d[k]} onChange={(e) => setD({ ...d, [k]: e.target.value })} />)}<div style={{ display: 'flex', gap: 6, marginTop: 6 }}><button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => run(() => dossierSaveAction(id, d), () => {})}>Salva</button>{id && <button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(() => dossierSummaryAction(id))}>Riassumi con l&apos;AI</button>}{id && <button type="button" className="btn btn-ghost btn-sm" onClick={() => { setId(''); setD(empty); }}>Nuovo</button>}</div></div></div>;
}
