'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import type { SectionSponsor } from '@/lib/models';
import { deleteFundAction, saveFundAction, saveSponsorAction, type Fund } from '@/lib/actions-economy';

const useRun = () => { const [pending, start] = useTransition(); const router = useRouter(); return { pending, run: (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } }) }; };
export function SponsorsManager({ cats, sponsors }: { cats: { id: string; name: string }[]; sponsors: Record<string, SectionSponsor> }) {
  const empty: SectionSponsor = { name: '', logo: '', url: '', contractUrl: '', until: '', note: '' }; const [cat, setCat] = useState(cats[0]?.id ?? ''); const [sp, setSp] = useState<SectionSponsor>(sponsors[cats[0]?.id ?? ''] ?? empty); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Sponsor di sezione</div><select className="select" aria-label="Sezione" value={cat} onChange={(e) => { setCat(e.target.value); setSp(sponsors[e.target.value] ?? empty); }}>{cats.map((c) => <option key={c.id} value={c.id}>{c.name}{sponsors[c.id] ? ` · ${sponsors[c.id].name}` : ''}</option>)}</select>{([['name', 'Azienda'], ['logo', 'Logo (URL)'], ['url', 'Sito (URL)'], ['contractUrl', 'Contratto pubblicato (URL)'], ['until', 'Fino al (AAAA-MM-GG)'], ['note', 'Nota pubblica']] as const).map(([k, l]) => <div className="field" key={k}><label htmlFor={`sp-${k}`}>{l}</label><input id={`sp-${k}`} className="input" type={k === 'until' ? 'date' : 'text'} value={sp[k]} onChange={(e) => setSp({ ...sp, [k]: e.target.value })} /></div>)}<div style={{ display: 'flex', gap: 6 }}><button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => run(() => saveSponsorAction(cat, sp))}>Salva</button><button type="button" className="btn btn-ghost btn-sm" disabled={pending} onClick={() => run(() => saveSponsorAction(cat, null), () => setSp(empty))}>Rimuovi</button></div><p className="help">Compare in testata alla sezione e in /sponsor con il contratto.</p></div>;
}
export function FundsManager({ funds }: { funds: (Fund & { id: string; donors: number })[] }) {
  const empty: Fund = { slug: '', title: '', intro: '', goal: 0, raised: 0, status: 'open', updates: '', expenses: '', articleId: '' }; const [id, setId] = useState(''); const [f, setF] = useState<Fund>(empty); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Crowdfunding per inchiesta <a className="help" href="/inchieste" target="_blank">apri</a></div>{funds.map((x) => <p key={x.id}><a href="#" onClick={(e) => { e.preventDefault(); setId(x.id); setF({ slug: x.slug, title: x.title, intro: x.intro, goal: x.goal, raised: x.raised - 0, status: x.status, updates: x.updates, expenses: x.expenses, articleId: x.articleId }); }}>{x.title}</a> <span className="help">· {x.raised} € su {x.goal} € · {x.donors} donatori</span> <button type="button" className="icon-btn danger" aria-label={`Elimina ${x.title}`} onClick={() => run(() => deleteFundAction(x.id))}>✕</button></p>)}
    <div className="field"><label htmlFor="fd-title">Titolo</label><input id="fd-title" className="input" value={f.title} onChange={(e) => setF({ ...f, title: e.target.value })} /></div><textarea className="textarea" style={{ minHeight: 60 }} aria-label="Presentazione" placeholder="Cosa vogliamo scoprire e perché costa" value={f.intro} onChange={(e) => setF({ ...f, intro: e.target.value })} /><div className="form-row" style={{ marginTop: 6 }}><input className="input" type="number" aria-label="Obiettivo in euro" placeholder="Obiettivo €" value={f.goal || ''} onChange={(e) => setF({ ...f, goal: Number(e.target.value) })} /><input className="input" type="number" aria-label="Raccolto fuori piattaforma" placeholder="Raccolto fuori piattaforma €" value={f.raised || ''} onChange={(e) => setF({ ...f, raised: Number(e.target.value) })} /><select className="select" aria-label="Stato" value={f.status} onChange={(e) => setF({ ...f, status: e.target.value as Fund['status'] })}><option value="open">Aperta</option><option value="done">Finanziata</option><option value="closed">Chiusa</option></select></div><input className="input" style={{ marginTop: 6 }} placeholder="Id dell'articolo pubblicato (quando esce)" aria-label="Articolo" value={f.articleId} onChange={(e) => setF({ ...f, articleId: e.target.value })} /><textarea className="textarea" style={{ minHeight: 60, marginTop: 6 }} aria-label="Aggiornamenti" placeholder="Aggiornamenti per i donatori (datati)" value={f.updates} onChange={(e) => setF({ ...f, updates: e.target.value })} /><textarea className="textarea" style={{ minHeight: 60, marginTop: 6 }} aria-label="Spese" placeholder="Resoconto delle spese (una voce per riga)" value={f.expenses} onChange={(e) => setF({ ...f, expenses: e.target.value })} /><div style={{ display: 'flex', gap: 6, marginTop: 6 }}><button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => run(() => saveFundAction(id, f), () => { setId(''); setF(empty); })}>Salva</button>{id && <button type="button" className="btn btn-ghost btn-sm" onClick={() => { setId(''); setF(empty); }}>Nuova</button>}</div><p className="help">Le donazioni con «inchiesta:slug» nel messaggio si sommano da sole.</p></div>;
}
