'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import { CLOSURE_LABELS, LEVEL_LABELS, smsText, type AlertLevel, type Closure, type ClosureKind } from '@/lib/emergency';
import { acceptClosureReportAction, chainVerdictAction, closureDeleteAction, closureSaveAction, diaryAddAction, diaryDeleteAction, saveSmsSettingsAction, sendSmsAction, setAlertAction } from '@/lib/actions-emergency';

const useRun = () => { const [pending, start] = useTransition(); const router = useRouter(); return { pending, run: (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } }) }; };
export function AlertPanel({ initial }: { initial: { active: boolean; title: string; text: string; level: AlertLevel; since?: string } }) {
  const [a, setA] = useState(initial); const { pending, run } = useRun();
  return <div className={`panel alert-panel ${a.active ? 'on' : ''}`}><div className="panel-title">Modalità allerta {initial.active && <span className="badge">ATTIVA dal {new Date(initial.since ?? '').toLocaleString('it-IT', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</span>}</div><p className="help">Accende il banner rosso su tutto il sito e la pagina /emergenza, avvisa la redazione (prima chi è di reperibilità, anche via email) e manda una push ai lettori. Chiudendola, il diario diventa un resoconto e un fascicolo.</p><div className="form-row"><input className="input" placeholder="Titolo (es. Allerta meteo rossa: esondazioni)" aria-label="Titolo" value={a.title} onChange={(e) => setA({ ...a, title: e.target.value })} /><select className="select" aria-label="Livello" value={a.level} onChange={(e) => setA({ ...a, level: e.target.value as AlertLevel })}>{(Object.keys(LEVEL_LABELS) as AlertLevel[]).map((l) => <option key={l} value={l}>{LEVEL_LABELS[l]}</option>)}</select></div><textarea className="textarea" style={{ minHeight: 56, marginTop: 6 }} placeholder="Una riga per i lettori: cosa fare adesso" aria-label="Testo" value={a.text} onChange={(e) => setA({ ...a, text: e.target.value })} /><div style={{ display: 'flex', gap: 6, marginTop: 8 }}>{!initial.active ? <button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => { if (confirm('Attivare la modalità allerta su tutto il sito?')) run(() => setAlertAction({ ...a, active: true })); }}>🚨 Attiva l&apos;allerta</button> : <><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(() => setAlertAction({ ...a, active: true }))}>Aggiorna il testo</button><button type="button" className="btn btn-dark btn-sm" disabled={pending} onClick={() => { if (confirm('Chiudere l\'emergenza? Il diario diventa resoconto e fascicolo.')) run(() => setAlertAction({ ...a, active: false })); }}>Chiudi l&apos;emergenza</button></>}</div></div>;
}
export function Diary({ list, active }: { list: { id: string; at: string; text: string; source: string; by: string }[]; active: boolean }) {
  const [t, setT] = useState(''); const [src, setSrc] = useState(''); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Diario dell&apos;emergenza</div>{active ? <><textarea className="textarea" style={{ minHeight: 56 }} placeholder="Aggiornamento verificato (es. Chiuso il ponte di via Roma, Vigili del fuoco sul posto)" aria-label="Aggiornamento" value={t} onChange={(e) => setT(e.target.value)} /><div className="form-row" style={{ marginTop: 6 }}><input className="input" placeholder="Fonte (es. Protezione civile, ore 14:10)" aria-label="Fonte" value={src} onChange={(e) => setSrc(e.target.value)} /><button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => run(() => diaryAddAction(t, src), () => { setT(''); setSrc(''); })}>Pubblica</button></div></> : <p className="help">Il diario si scrive durante un&apos;allerta attiva.</p>}<ul className="em-diary" style={{ marginTop: 8 }}>{list.map((d) => <li key={d.id}><time>{new Date(d.at).toLocaleString('it-IT', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</time><div>{d.text}{d.source && <span className="help"> · {d.source}</span>} <span className="help">· {d.by}</span> <button type="button" className="icon-btn danger" aria-label="Elimina" onClick={() => run(() => diaryDeleteAction(d.id))}>✕</button></div></li>)}</ul></div>;
}
export function ClosuresAdmin({ list, reports }: { list: Closure[]; reports: { id: string; kind: string; name: string; note: string }[] }) {
  const empty = { id: '', kind: 'strada' as ClosureKind, name: '', status: 'chiuso' as Closure['status'], until: '', note: '' }; const [c, setC] = useState(empty); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Chiusure <a className="help" href="/chiusure" target="_blank">pagina pubblica</a></div>{reports.length > 0 && <div className="riguarda" style={{ marginBottom: 8 }}><b>Segnalate dai lettori ({reports.length})</b>{reports.map((r) => <p key={r.id}>{CLOSURE_LABELS[r.kind as ClosureKind] ?? r.kind}: <b>{r.name}</b> {r.note && <span className="help">· {r.note}</span>} <button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(() => acceptClosureReportAction(r.id))}>Conferma</button></p>)}</div>}<table className="table"><tbody>{list.map((x) => <tr key={x.id}><td>{CLOSURE_LABELS[x.kind]}</td><td className="t-title"><a href="#" onClick={(e) => { e.preventDefault(); setC({ id: x.id, kind: x.kind, name: x.name, status: x.status, until: x.until, note: x.note }); }}>{x.name}</a> <span className="help">· {x.status}{x.until ? ` fino al ${x.until}` : ''}</span></td><td style={{ textAlign: 'right' }}><button type="button" className="icon-btn danger" aria-label="Elimina" onClick={() => run(() => closureDeleteAction(x.id))}>✕</button></td></tr>)}</tbody></table><div className="form-row" style={{ marginTop: 8 }}><select className="select" aria-label="Tipo" value={c.kind} onChange={(e) => setC({ ...c, kind: e.target.value as ClosureKind })}>{(Object.keys(CLOSURE_LABELS) as ClosureKind[]).map((k) => <option key={k} value={k}>{CLOSURE_LABELS[k]}</option>)}</select><input className="input" placeholder="Nome (via, scuola, linea)" aria-label="Nome" value={c.name} onChange={(e) => setC({ ...c, name: e.target.value })} /><select className="select" aria-label="Stato" value={c.status} onChange={(e) => setC({ ...c, status: e.target.value as Closure['status'] })}><option value="chiuso">chiuso</option><option value="parziale">parziale</option><option value="riaperto">riaperto</option></select><input className="input" type="date" aria-label="Fino al" value={c.until} onChange={(e) => setC({ ...c, until: e.target.value })} /></div><input className="input" style={{ marginTop: 6 }} placeholder="Nota" aria-label="Nota" value={c.note} onChange={(e) => setC({ ...c, note: e.target.value })} /><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 6 }} disabled={pending} onClick={() => run(() => closureSaveAction(c), () => setC(empty))}>Salva</button></div>;
}
export function ChainsQueue({ list }: { list: { id: string; text: string; where: string; createdAt: string }[] }) {
  const [v, setV] = useState<Record<string, { verdict: 'vero' | 'falso' | 'in-parte' | 'non-verificabile'; note: string }>>({}); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Catene da verificare ({list.length}) <a className="help" href="/catene" target="_blank">pagina pubblica</a></div>{list.length === 0 && <p className="help">Nessun messaggio in attesa.</p>}{list.map((r) => { const x = v[r.id] ?? { verdict: 'falso' as const, note: '' }; const set = (p: Partial<typeof x>) => setV({ ...v, [r.id]: { ...x, ...p } }); return <div key={r.id} className="reply-item"><blockquote>{r.text}</blockquote><p className="help">{r.where ? `girava su ${r.where} · ` : ''}{new Date(r.createdAt).toLocaleString('it-IT')}</p><div className="form-row"><select className="select" aria-label="Verdetto" value={x.verdict} onChange={(e) => set({ verdict: e.target.value as typeof x.verdict })}><option value="vero">Vero</option><option value="falso">Falso</option><option value="in-parte">Vero solo in parte</option><option value="non-verificabile">Non verificabile</option></select></div><textarea className="textarea" style={{ minHeight: 56, marginTop: 6 }} placeholder="Cosa avete verificato, con chi" aria-label="Nota" value={x.note} onChange={(e) => set({ note: e.target.value })} /><button type="button" className="btn btn-primary btn-sm" style={{ marginTop: 6 }} disabled={pending} onClick={() => run(() => chainVerdictAction(r.id, x.verdict, x.note))}>Pubblica la verifica</button></div>; })}</div>;
}
export function SmsPanel({ configured, subscribers, siteName, canSettings, sent }: { configured: boolean; subscribers: number; siteName: string; canSettings: boolean; sent: { body: string; sent: number; failed: number; at: string }[] }) {
  const [t, setT] = useState(''); const [cfg, setCfg] = useState({ sid: '', token: '', from: '' }); const { pending, run } = useRun(); const preview = smsText(siteName, t || '…', 'https://…/emergenza');
  return <div className="panel"><div className="panel-title">Canale SMS d&apos;emergenza <span className="help">· {subscribers} numeri iscritti</span></div>{configured ? <><textarea className="textarea" style={{ minHeight: 56 }} placeholder="Il messaggio (un solo SMS: arriva anche con poca rete)" aria-label="SMS" value={t} onChange={(e) => setT(e.target.value)} /><p className="help">Anteprima ({preview.length}/160): <code>{preview}</code></p><button type="button" className="btn btn-primary btn-sm" disabled={pending || t.trim().length < 10} onClick={() => { if (confirm(`Inviare l'SMS a ${subscribers} numeri?`)) run(() => sendSmsAction(t), () => setT('')); }}>Invia a tutti</button></> : <p className="help">Non configurato: servono SID, token e numero mittente di Twilio (o compatibile).</p>}{canSettings && <details style={{ marginTop: 8 }}><summary>Configurazione (Twilio)</summary><div className="form-row" style={{ marginTop: 6 }}><input className="input" placeholder="Account SID" aria-label="SID" value={cfg.sid} onChange={(e) => setCfg({ ...cfg, sid: e.target.value })} /><input className="input" type="password" placeholder={configured ? 'Token (lascia vuoto per non cambiarlo)' : 'Auth token'} aria-label="Token" value={cfg.token} onChange={(e) => setCfg({ ...cfg, token: e.target.value })} /><input className="input" placeholder="Numero mittente (+39…)" aria-label="Mittente" value={cfg.from} onChange={(e) => setCfg({ ...cfg, from: e.target.value })} /></div><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 6 }} disabled={pending} onClick={() => run(() => saveSmsSettingsAction(cfg))}>Salva</button></details>}{sent.length > 0 && <ul className="help" style={{ marginTop: 8 }}>{sent.slice(0, 5).map((s, i) => <li key={i}>{new Date(s.at).toLocaleString('it-IT', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}: {s.sent} inviati{s.failed ? `, ${s.failed} falliti` : ''} · «{s.body.slice(0, 60)}»</li>)}</ul>}</div>;
}
