'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import { deleteVignettaAction, makeRadioNowAction, saveVignettaAction, sendEreaderNowAction } from '@/lib/actions-formats';

export function FormatsAdmin({ vignette, ereaders, radio }: { vignette: { id: string; image: string; caption: string; createdAt: string }[]; ereaders: number; radio: { date: string; url: string } | null }) {
  const [v, setV] = useState({ image: '', caption: '', articleId: '', author: '' }); const [pending, start] = useTransition(); const router = useRouter();
  const run = (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } });
  return <div className="admin-grid-2"><div className="panel"><div className="panel-title">La vignetta della settimana</div>{vignette.map((x) => <p key={x.id}><img src={x.image} alt="" style={{ height: 40, verticalAlign: 'middle', marginRight: 8 }} />{x.caption.slice(0, 50)} <span className="help">{new Date(x.createdAt).toLocaleDateString('it-IT')}</span> <button type="button" className="icon-btn danger" aria-label="Elimina" onClick={() => run(() => deleteVignettaAction(x.id))}>✕</button></p>)}<input className="input" placeholder="Immagine (URL dalla Libreria media)" aria-label="Immagine" value={v.image} onChange={(e) => setV({ ...v, image: e.target.value })} /><input className="input" style={{ marginTop: 6 }} placeholder="Didascalia" aria-label="Didascalia" value={v.caption} onChange={(e) => setV({ ...v, caption: e.target.value })} /><div className="form-row" style={{ marginTop: 6 }}><input className="input" placeholder="Disegnata da" aria-label="Autore" value={v.author} onChange={(e) => setV({ ...v, author: e.target.value })} /><input className="input" placeholder="Id dell'articolo" aria-label="Articolo" value={v.articleId} onChange={(e) => setV({ ...v, articleId: e.target.value })} /></div><button type="button" className="btn btn-primary btn-sm" style={{ marginTop: 6 }} disabled={pending} onClick={() => run(() => saveVignettaAction(v), () => setV({ image: '', caption: '', articleId: '', author: '' }))}>Pubblica</button></div>
    <div className="panel"><div className="panel-title">Radio ed e-reader</div><p>Radio del mattino: {radio ? <>ultima registrazione del {radio.date} (<a href={radio.url}>ascolta</a>)</> : 'nessuna registrazione'}. Si registra da sola ogni notte se la voce sintetica è configurata.</p><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(() => makeRadioNowAction())}>Registra adesso</button><p style={{ marginTop: 14 }}>Edizione e-reader: <b>{ereaders}</b> iscritti; parte ogni lunedì con l&apos;EPUB della settimana in allegato.</p><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(() => sendEreaderNowAction())}>Invia adesso</button></div></div>;
}
