'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import type { MethodSettings } from '@/lib/method';
import { KIND_LABELS } from '@/lib/trust';
import { anonSourceDeleteAction, anonSourceRevealAction, oblivionDecideAction, postmortemDeleteAction, postmortemSaveAction, saveMethodSettingsAction } from '@/lib/actions-method';

const useRun = () => { const [pending, start] = useTransition(); const router = useRouter(); return { pending, start, run: (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } }) }; };
const KINDS = ['default', ...Object.keys(KIND_LABELS)];
export function MethodForm({ initial }: { initial: MethodSettings }) {
  const [m, setM] = useState<MethodSettings>({ checklists: {}, lexicon: '', twoSources: false, crossReadKinds: [], ...initial }); const [kind, setKind] = useState('default'); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Regole della casa</div><div className="field"><label htmlFor="mt-kind">Check-list prima di pubblicare, per genere (una voce per riga)</label><select id="mt-kind" className="select" value={kind} onChange={(e) => setKind(e.target.value)}>{KINDS.map((k) => <option key={k} value={k}>{k === 'default' ? 'Tutti gli articoli (predefinita)' : KIND_LABELS[k as keyof typeof KIND_LABELS].name}</option>)}</select><textarea className="textarea" style={{ minHeight: 90, marginTop: 6 }} aria-label={`Check-list ${kind}`} placeholder={'Nomi e cariche verificati\nMinori non identificabili\nControparte sentita o contattata'} value={m.checklists?.[kind] ?? ''} onChange={(e) => setM({ ...m, checklists: { ...(m.checklists ?? {}), [kind]: e.target.value } })} /></div><div className="field"><label htmlFor="mt-lex">Lessico della testata (una riga: da evitare =&gt; preferire | nota)</label><textarea id="mt-lex" className="textarea" style={{ minHeight: 90 }} placeholder={'clandestino => persona senza permesso di soggiorno | termine giuridicamente impreciso\nvittima di femminicidio => donna uccisa'} value={m.lexicon} onChange={(e) => setM({ ...m, lexicon: e.target.value })} /></div><label className="switch"><input type="checkbox" checked={!!m.twoSources} onChange={(e) => setM({ ...m, twoSources: e.target.checked })} /> Regola delle due fonti: cronaca e inchiesta non si pubblicano con meno di due fonti con nome</label><div className="field" style={{ marginTop: 8 }}><label>Rilettura incrociata obbligatoria per</label><div className="chips">{Object.entries(KIND_LABELS).map(([k, v]) => <button key={k} type="button" className="chip" style={(m.crossReadKinds ?? []).includes(k) ? { background: '#111', color: '#fff' } : undefined} onClick={() => setM({ ...m, crossReadKinds: (m.crossReadKinds ?? []).includes(k) ? (m.crossReadKinds ?? []).filter((x) => x !== k) : [...(m.crossReadKinds ?? []), k] })}>{v.name}</button>)}</div></div><button type="button" className="btn btn-primary btn-sm" style={{ marginTop: 10 }} disabled={pending} onClick={() => run(() => saveMethodSettingsAction(m))}>Salva</button></div>;
}
export function AnonSources({ list }: { list: { id: string; title: string; by: string; createdAt: string; mine: boolean }[] }) {
  const [open, setOpen] = useState<Record<string, { who: string; how: string; verifiedAt: string }>>({}); const { pending, start, run } = useRun();
  return <div className="panel"><div className="panel-title">Registro delle fonti anonime</div><p className="help">Identità cifrate. Vedi solo quelle per cui sei autorizzato; ogni lettura resta nel registro delle attività.</p>{list.length === 0 && <p className="help">Nessuna fonte registrata.</p>}{list.map((s) => <div key={s.id} className="reply-item"><p><b>{s.title}</b> <span className="help">· registrata da {s.by} il {new Date(s.createdAt).toLocaleDateString('it-IT')}</span></p>{open[s.id] ? <p className="riguarda"><b>{open[s.id].who}</b><br />{open[s.id].how}<br /><span className="help">verificata il {open[s.id].verifiedAt}</span></p> : <button type="button" className="btn btn-outline btn-sm" disabled={pending || !s.mine} onClick={() => start(async () => { const r = await anonSourceRevealAction(s.id); if (r.ok) setOpen({ ...open, [s.id]: { who: r.who!, how: r.how!, verifiedAt: r.verifiedAt! } }); else toast.error(r.message ?? ''); })}>{s.mine ? 'Leggi (resta registrato)' : 'Non autorizzato'}</button>} {s.mine && <button type="button" className="btn btn-ghost btn-sm" disabled={pending} onClick={() => { if (confirm('Distruggere la registrazione? Non si recupera.')) run(() => anonSourceDeleteAction(s.id)); }}>Distruggi</button>}</div>)}</div>;
}
export function OblivionQueue({ list }: { list: { id: string; reason: string; url: string; text: string; name: string; createdAt: string }[] }) {
  const [d, setD] = useState<Record<string, { decision: 'accolta' | 'parziale' | 'respinta'; motivation: string; noindex: boolean; anonymize: boolean }>>({}); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Diritto all&apos;oblio: richieste in esame ({list.length})</div>{list.length === 0 && <p className="help">Nessuna richiesta.</p>}{list.map((r) => { const v = d[r.id] ?? { decision: 'respinta' as const, motivation: '', noindex: false, anonymize: false }; const set = (p: Partial<typeof v>) => setD({ ...d, [r.id]: { ...v, ...p } }); const days = Math.floor((Date.now() - +new Date(r.createdAt)) / 86_400_000); return <div key={r.id} className="reply-item"><p><b>{r.reason}</b> · {r.name} · <a href={r.url} target="_blank" rel="noopener">{r.url.slice(0, 60)}</a> · <span className={days > 25 ? 'error-text' : 'help'}>{days} giorni fa (termine: 30)</span></p><blockquote>{r.text}</blockquote><div className="form-row"><select className="select" aria-label="Decisione" value={v.decision} onChange={(e) => set({ decision: e.target.value as typeof v.decision })}><option value="accolta">Accolta</option><option value="parziale">Accolta in parte</option><option value="respinta">Respinta</option></select><label className="switch"><input type="checkbox" checked={v.noindex} onChange={(e) => set({ noindex: e.target.checked })} /> Escludi dai motori</label><label className="switch"><input type="checkbox" checked={v.anonymize} onChange={(e) => set({ anonymize: e.target.checked })} /> Da anonimizzare</label></div><textarea className="textarea" style={{ minHeight: 56, marginTop: 6 }} aria-label="Motivazione" placeholder="Motivazione (pubblica, senza nomi)" value={v.motivation} onChange={(e) => set({ motivation: e.target.value })} /><button type="button" className="btn btn-primary btn-sm" style={{ marginTop: 6 }} disabled={pending} onClick={() => run(() => oblivionDecideAction(r.id, v))}>Decidi e notifica</button></div>; })}</div>;
}
export function Postmortems({ list }: { list: { id: string; title: string; what: string; why: string; change: string; articleId: string; isPublic: boolean }[] }) {
  const empty = { title: '', what: '', why: '', change: '', articleId: '', isPublic: false }; const [id, setId] = useState(''); const [p, setP] = useState(empty); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Post-mortem <a className="help" href="/come-abbiamo-sbagliato" target="_blank">pagina pubblica</a></div>{list.map((x) => <p key={x.id}><a href="#" onClick={(e) => { e.preventDefault(); setId(x.id); setP(x); }}>{x.title}</a> <span className="help">{x.isPublic ? '· pubblico' : '· interno'}</span> <button type="button" className="icon-btn danger" aria-label="Elimina" onClick={() => run(() => postmortemDeleteAction(x.id))}>✕</button></p>)}<input className="input" placeholder="Titolo (es. Il nome sbagliato nell'articolo sul processo)" aria-label="Titolo" value={p.title} onChange={(e) => setP({ ...p, title: e.target.value })} />{(['what', 'why', 'change'] as const).map((k) => <textarea key={k} className="textarea" style={{ minHeight: 56, marginTop: 6 }} aria-label={k} placeholder={{ what: 'Cosa è successo, nei fatti', why: 'Perché è successo (processo, fretta, mancata verifica…)', change: 'Cosa cambia da ora' }[k]} value={p[k]} onChange={(e) => setP({ ...p, [k]: e.target.value })} />)}<div className="form-row" style={{ marginTop: 6 }}><input className="input" placeholder="Id dell'articolo" aria-label="Articolo" value={p.articleId} onChange={(e) => setP({ ...p, articleId: e.target.value })} /><label className="switch"><input type="checkbox" checked={p.isPublic} onChange={(e) => setP({ ...p, isPublic: e.target.checked })} /> Versione pubblica</label></div><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 6 }} disabled={pending} onClick={() => run(() => postmortemSaveAction(id, p), () => { setId(''); setP(empty); })}>Salva</button></div>;
}
