'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import type { PersonalSettings } from '@/lib/models';
import { confirmUseAction, createTypeAction, deletePersonalRecordAction, evolutionAction, proposeTypeAction, replyToPastAction, saveCollectionAction, saveCorrespondenceAction, saveNowAction, savePersonalAction, saveUseAction, type Collection, type Correspondence, type TypeProposal } from '@/lib/actions-personal';

const useRun = () => { const [pending, start] = useTransition(); const router = useRouter(); const run = (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } }); return { pending, run, router }; };
export function PastToday({ items }: { items: { id: string; title: string; yearsAgo: number; excerpt: string }[] }) {
  const { pending, router } = useRun(); const [, start] = useTransition();
  if (!items.length) return null;
  return <div className="panel panel-warn"><div className="panel-title">Un anno fa oggi</div>{items.map((a) => <div key={a.id} className="reply-item"><p><b>{a.yearsAgo === 1 ? 'Un anno fa' : `${a.yearsAgo} anni fa`}</b> scrivevi «{a.title}»</p><blockquote>{a.excerpt}</blockquote><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => start(async () => { const r = await replyToPastAction(a.id); if (r.ok && r.id) router.push(`/admin/articoli/${r.id}`); else toast.error(r.message ?? ''); })}>Rispondi al te di allora</button></div>)}</div>;
}
const NOW: [string, string][] = [['place', 'Dove sono'], ['writing', 'Sto scrivendo'], ['reading', 'Sto leggendo'], ['listening', 'Sto ascoltando'], ['watching', 'Sto guardando'], ['note', 'Una nota']];
export function NowForm({ initial }: { initial: Record<string, string> }) {
  const [n, setN] = useState(initial); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Pagina «adesso» <a className="help" href="/adesso" target="_blank">apri</a></div>{NOW.map(([k, l]) => <div className="field" key={k}><label htmlFor={`now-${k}`}>{l}</label><input id={`now-${k}`} className="input" value={n[k] ?? ''} onChange={(e) => setN({ ...n, [k]: e.target.value })} /></div>)}<button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => run(() => saveNowAction(n))}>Aggiorna</button><p className="help" style={{ marginTop: 6 }}>Si aggiorna anche dal bot Telegram: <code>/adesso leggo: …; ascolto: …</code></p></div>;
}
export function UsesManager({ uses }: { uses: { id: string; data: Record<string, string> }[] }) {
  const empty = { name: '', kind: '', url: '', note: '' }; const [id, setId] = useState(''); const [u, setU] = useState(empty); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">«Usa questo» <a className="help" href="/uso" target="_blank">apri</a></div><table className="table"><tbody>{uses.map((x) => <tr key={x.id}><td className="t-title"><a href="#" onClick={(e) => { e.preventDefault(); setId(x.id); setU({ name: x.data.name, kind: x.data.kind, url: x.data.url, note: x.data.note }); }}>{x.data.name}</a><div className="help">{x.data.kind} · confermato il {new Date(x.data.confirmedAt).toLocaleDateString('it-IT')}</div></td><td style={{ textAlign: 'right', whiteSpace: 'nowrap' }}><button type="button" className="btn btn-ghost btn-sm" disabled={pending} onClick={() => run(() => confirmUseAction(x.id))}>Lo consiglio ancora</button><button type="button" className="icon-btn danger" aria-label={`Elimina ${x.data.name}`} onClick={() => run(() => deletePersonalRecordAction(x.id))}>✕</button></td></tr>)}</tbody></table>
    <div className="form-row" style={{ marginTop: 8 }}><input className="input" placeholder="Nome (es. Obsidian)" aria-label="Nome del consiglio" value={u.name} onChange={(e) => setU({ ...u, name: e.target.value })} /><input className="input" placeholder="Gruppo (Strumenti, Libri, Luoghi)" aria-label="Gruppo" value={u.kind} onChange={(e) => setU({ ...u, kind: e.target.value })} /></div><input className="input" style={{ marginTop: 6 }} placeholder="Link (facoltativo)" aria-label="Link" value={u.url} onChange={(e) => setU({ ...u, url: e.target.value })} /><input className="input" style={{ marginTop: 6 }} placeholder="Perché lo consigli" aria-label="Perché lo consigli" value={u.note} onChange={(e) => setU({ ...u, note: e.target.value })} /><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 8 }} disabled={pending} onClick={() => run(() => saveUseAction(id, u), () => { setId(''); setU(empty); })}>{id ? 'Aggiorna' : 'Aggiungi'}</button></div>;
}
export function CollectionsManager({ collections }: { collections: { id: string; data: Collection }[] }) {
  const empty: Collection = { slug: '', title: '', query: '', intro: '' }; const [id, setId] = useState(''); const [c, setC] = useState(empty); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Raccolte automatiche <a className="help" href="/raccolte" target="_blank">apri</a></div><p className="help">Scrivi le parole del tema («mio padre, papà, officina»): gli articoli si trovano da soli, anche senza tag. Ogni raccolta si scarica come libro.</p><table className="table"><tbody>{collections.map((x) => <tr key={x.id}><td className="t-title"><a href="#" onClick={(e) => { e.preventDefault(); setId(x.id); setC(x.data); }}>{x.data.title}</a><div className="help">{x.data.query}{x.data.evolution ? ' · con evoluzione' : ''}</div></td><td style={{ textAlign: 'right', whiteSpace: 'nowrap' }}><button type="button" className="btn btn-ghost btn-sm" disabled={pending} onClick={() => run(() => evolutionAction(x.id))}>Come è cambiato?</button><a className="btn btn-ghost btn-sm" href={`/api/export/libro?raccolta=${x.data.slug}&formato=epub`}>EPUB</a><button type="button" className="icon-btn danger" aria-label={`Elimina ${x.data.title}`} onClick={() => run(() => deletePersonalRecordAction(x.id))}>✕</button></td></tr>)}</tbody></table>
    <input className="input" style={{ marginTop: 8 }} placeholder="Titolo (es. Mio padre)" aria-label="Titolo della raccolta" value={c.title} onChange={(e) => setC({ ...c, title: e.target.value })} /><input className="input" style={{ marginTop: 6 }} placeholder="Parole del tema, separate da virgola" aria-label="Parole del tema" value={c.query} onChange={(e) => setC({ ...c, query: e.target.value })} /><input className="input" style={{ marginTop: 6 }} placeholder="Due righe di introduzione" aria-label="Introduzione" value={c.intro} onChange={(e) => setC({ ...c, intro: e.target.value })} /><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 8 }} disabled={pending} onClick={() => run(() => saveCollectionAction(id, c), () => { setId(''); setC(empty); })}>{id ? 'Aggiorna' : 'Crea raccolta'}</button></div>;
}
export function LettersManager({ list }: { list: { id: string; data: Correspondence }[] }) {
  const empty: Correspondence = { slug: '', title: '', intro: '', withName: '', withUrl: '', letters: [{ from: 'me', date: '', text: '' }] }; const [id, setId] = useState(''); const [c, setC] = useState(empty); const { pending, run } = useRun(); const upd = (i: number, p: Partial<Correspondence['letters'][number]>) => setC({ ...c, letters: c.letters.map((l, j) => (j === i ? { ...l, ...p } : l)) });
  return <div className="panel"><div className="panel-title">Corrispondenze pubbliche <a className="help" href="/corrispondenze" target="_blank">apri</a></div>{list.map((x) => <p key={x.id}><a href="#" onClick={(e) => { e.preventDefault(); setId(x.id); setC(x.data); }}>{x.data.title}</a> <span className="help">con {x.data.withName} · {x.data.letters.length} lettere</span> <button type="button" className="icon-btn danger" aria-label={`Elimina ${x.data.title}`} onClick={() => run(() => deletePersonalRecordAction(x.id))}>✕</button></p>)}
    <div className="form-row"><input className="input" placeholder="Titolo dello scambio" aria-label="Titolo dello scambio" value={c.title} onChange={(e) => setC({ ...c, title: e.target.value })} /><input className="input" placeholder="Con chi" aria-label="Con chi" value={c.withName} onChange={(e) => setC({ ...c, withName: e.target.value })} /></div><input className="input" style={{ marginTop: 6 }} placeholder="Indirizzo del suo blog (facoltativo)" aria-label="Blog dell'altra persona" value={c.withUrl} onChange={(e) => setC({ ...c, withUrl: e.target.value })} /><input className="input" style={{ marginTop: 6 }} placeholder="Di cosa parlate" aria-label="Introduzione allo scambio" value={c.intro} onChange={(e) => setC({ ...c, intro: e.target.value })} />
    {c.letters.map((l, i) => <div key={i} className="letter-edit"><div className="form-row"><select className="select" aria-label="Chi scrive" value={l.from} onChange={(e) => upd(i, { from: e.target.value as 'me' | 'them' })}><option value="me">Scrivo io</option><option value="them">Scrive {c.withName || 'l\'altra persona'}</option></select><input className="input" type="date" aria-label="Data della lettera" value={l.date} onChange={(e) => upd(i, { date: e.target.value })} /></div><textarea className="textarea" style={{ minHeight: 90, marginTop: 6 }} aria-label={`Testo della lettera ${i + 1}`} value={l.text} onChange={(e) => upd(i, { text: e.target.value })} />{l.from === 'them' && <input className="input" style={{ marginTop: 6 }} placeholder="Dove è stata pubblicata (link)" aria-label="Link originale" value={l.url ?? ''} onChange={(e) => upd(i, { url: e.target.value })} />}</div>)}
    <div style={{ display: 'flex', gap: 6, marginTop: 8 }}><button type="button" className="btn btn-ghost btn-sm" onClick={() => setC({ ...c, letters: [...c.letters, { from: c.letters[c.letters.length - 1]?.from === 'me' ? 'them' : 'me', date: '', text: '' }] })}>+ Lettera</button><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(() => saveCorrespondenceAction(id, c), () => { setId(''); setC(empty); })}>Salva</button></div></div>;
}
export function TypeByWords() {
  const [text, setText] = useState(''); const [p, setP] = useState<TypeProposal | null>(null); const [pending, start] = useTransition(); const { run } = useRun();
  return <div className="panel"><div className="panel-title">Un nuovo tipo di contenuto, descritto a parole</div><textarea className="textarea" style={{ minHeight: 60 }} aria-label="Descrivi il tipo di contenuto" placeholder="es. Voglio schede di libri con voto, autore, anno e una citazione" value={text} onChange={(e) => setText(e.target.value)} /><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 6 }} disabled={pending || text.trim().length < 12} onClick={() => start(async () => { const r = await proposeTypeAction(text); if (r.ok && r.data) setP(r.data); else toast.error(r.message ?? ''); })}>{pending ? 'Ci penso…' : 'Proponi campi e modello'}</button>
    {p && <div className="type-proposal"><div className="field"><label htmlFor="tp-name">Nome della sezione</label><input id="tp-name" className="input" value={p.name} onChange={(e) => setP({ ...p, name: e.target.value })} /></div><ul>{p.fields.map((f, i) => <li key={f.key}><input className="input" aria-label={`Etichetta del campo ${f.key}`} value={f.label} onChange={(e) => setP({ ...p, fields: p.fields.map((x, j) => (j === i ? { ...x, label: e.target.value } : x)) })} /><span className="help">{f.type}</span><button type="button" className="icon-btn danger" aria-label={`Togli ${f.label}`} onClick={() => setP({ ...p, fields: p.fields.filter((_, j) => j !== i) })}>✕</button></li>)}</ul><button type="button" className="btn btn-primary btn-sm" onClick={() => run(() => createTypeAction(p), () => { setP(null); setText(''); })}>Crea sezione, campi e tabella</button></div>}</div>;
}
export function PersonalSettingsForm({ initial, tags }: { initial: PersonalSettings; tags: { id: string; name: string }[] }) {
  const [p, setP] = useState<PersonalSettings>({ seasons: [], ...initial }); const { pending, run } = useRun(); const L = p.legacy ?? { enabled: false, days: 365, action: 'freeze' as const, heirName: '', heirEmail: '', message: '' }; const E = p.eventMode ?? { enabled: false, title: '', intro: '', tagId: '', until: '' };
  const season = (i: number, patch: Partial<NonNullable<PersonalSettings['seasons']>[number]>) => setP({ ...p, seasons: (p.seasons ?? []).map((s, j) => (j === i ? { ...s, ...patch } : s)) });
  return (
    <div className="panel"><div className="panel-title">Il sito cambia forma</div>
      <label className="switch"><input type="checkbox" checked={!!p.autoHome} onChange={(e) => setP({ ...p, autoHome: e.target.checked })} /> La home si compone da sola: galleria se pubblico soprattutto foto, indice se scrivo testi lunghi</label>
      <label className="switch" style={{ marginTop: 6 }}><input type="checkbox" checked={!!p.memory} onChange={(e) => setP({ ...p, memory: e.target.checked })} /> Ricordi con posto e meteo: annota da solo dove ero e che tempo faceva quando pubblico</label>
      <div className="panel-title" style={{ marginTop: 16 }}>Silenzio dichiarato</div><div className="form-row"><input className="input" type="date" aria-label="Torno il" value={p.silence?.until ?? ''} onChange={(e) => setP({ ...p, silence: { until: e.target.value, message: p.silence?.message ?? '' } })} /><input className="input" placeholder="Messaggio (es. Mi prendo una pausa per finire il libro)" aria-label="Messaggio del silenzio" value={p.silence?.message ?? ''} onChange={(e) => setP({ ...p, silence: { until: p.silence?.until ?? '', message: e.target.value } })} /></div><p className="help">In cima al sito compare il conto alla rovescia e chi vuole lascia l&apos;email per essere avvisato al ritorno. Svuota la data per toglierlo.</p>
      <div className="panel-title" style={{ marginTop: 16 }}>Stagioni del sito <button type="button" className="btn btn-outline btn-sm" onClick={() => setP({ ...p, seasons: [...(p.seasons ?? []), { id: '', name: '', from: '', to: '' }] })}>+ Stagione</button></div><p className="help">Date ricorrenti MM-GG (es. 12-08 → 01-06) oppure una volta sola AAAA-MM-GG. Finito il periodo tutto torna com&apos;era.</p>
      {(p.seasons ?? []).map((s, i) => <div key={i} className="season-row"><input className="input" placeholder="Nome" aria-label="Nome della stagione" value={s.name} onChange={(e) => season(i, { name: e.target.value })} /><input className="input" placeholder="dal" aria-label="Dal" value={s.from} onChange={(e) => season(i, { from: e.target.value })} /><input className="input" placeholder="al" aria-label="Al" value={s.to} onChange={(e) => season(i, { to: e.target.value })} /><input type="color" aria-label="Colore d'accento" value={s.accent ?? '#d7262d'} onChange={(e) => season(i, { accent: e.target.value })} /><input className="input" placeholder="Avviso in cima al sito (facoltativo)" aria-label="Avviso" value={s.banner ?? ''} onChange={(e) => season(i, { banner: e.target.value })} /><label className="switch"><input type="checkbox" checked={!!s.mourning} onChange={(e) => season(i, { mourning: e.target.checked })} /> lutto</label><button type="button" className="icon-btn danger" aria-label="Rimuovi stagione" onClick={() => setP({ ...p, seasons: (p.seasons ?? []).filter((_, j) => j !== i) })}>✕</button></div>)}
      <div className="panel-title" style={{ marginTop: 16 }}>Modalità evento</div><label className="switch"><input type="checkbox" checked={E.enabled} onChange={(e) => setP({ ...p, eventMode: { ...E, enabled: e.target.checked } })} /> Attiva lo speciale in cima al sito</label><div className="form-row" style={{ marginTop: 6 }}><input className="input" placeholder="Titolo (es. Festival della Valle 2026)" aria-label="Titolo dello speciale" value={E.title} onChange={(e) => setP({ ...p, eventMode: { ...E, title: e.target.value } })} /><select className="select" aria-label="Argomento dello speciale" value={E.tagId} onChange={(e) => setP({ ...p, eventMode: { ...E, tagId: e.target.value } })}><option value="">Argomento…</option>{tags.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select><input className="input" type="date" aria-label="Fino al" value={E.until} onChange={(e) => setP({ ...p, eventMode: { ...E, until: e.target.value } })} /></div><input className="input" style={{ marginTop: 6 }} placeholder="Due righe di presentazione" aria-label="Presentazione dello speciale" value={E.intro} onChange={(e) => setP({ ...p, eventMode: { ...E, intro: e.target.value } })} /><p className="help">Dopo la data l&apos;avviso sparisce e <code>/speciale</code> resta come capitolo concluso.</p>
      <div className="panel-title" style={{ marginTop: 16 }}>Testamento digitale</div><label className="switch"><input type="checkbox" checked={L.enabled} onChange={(e) => setP({ ...p, legacy: { ...L, enabled: e.target.checked } })} /> Se nessuno accede per</label> <input className="input" type="number" min={60} max={1825} style={{ maxWidth: 90, display: 'inline-block' }} aria-label="Giorni di inattività" value={L.days} onChange={(e) => setP({ ...p, legacy: { ...L, days: Number(e.target.value) } })} /> <span className="help">giorni, il sito viene:</span>
      <select className="select" style={{ marginTop: 6 }} aria-label="Cosa succede al sito" value={L.action} onChange={(e) => setP({ ...p, legacy: { ...L, action: e.target.value as typeof L.action } })}><option value="freeze">congelato: resta leggibile con un avviso</option><option value="handover">affidato a una persona di fiducia</option><option value="archive">archiviato: la persona di fiducia riceve il sito in scatola</option></select>
      <div className="form-row" style={{ marginTop: 6 }}><input className="input" placeholder="Persona di fiducia" aria-label="Nome della persona di fiducia" value={L.heirName} onChange={(e) => setP({ ...p, legacy: { ...L, heirName: e.target.value } })} /><input className="input" type="email" placeholder="La sua email" aria-label="Email della persona di fiducia" value={L.heirEmail} onChange={(e) => setP({ ...p, legacy: { ...L, heirEmail: e.target.value } })} /></div><textarea className="textarea" style={{ minHeight: 60, marginTop: 6 }} placeholder="Il messaggio che riceverà (e che comparirà sul sito, se congelato)" aria-label="Messaggio per la persona di fiducia" value={L.message} onChange={(e) => setP({ ...p, legacy: { ...L, message: e.target.value } })} />{L.triggeredAt && <p className="form-error">Eseguito il {new Date(L.triggeredAt).toLocaleDateString('it-IT')}. Disattiva e salva per riaprire il sito.</p>}
      <div className="field" style={{ marginTop: 12 }}><label htmlFor="ps-chat">Il tuo id chat Telegram (per aggiornare «adesso» dal bot)</label><input id="ps-chat" className="input" value={p.ownerChatId ?? ''} onChange={(e) => setP({ ...p, ownerChatId: e.target.value })} /></div>
      <button type="button" className="btn btn-primary" disabled={pending} onClick={() => run(() => savePersonalAction({ ...p, legacy: p.legacy ? L : undefined }))}>{pending ? 'Salvo…' : 'Salva'}</button>
    </div>
  );
}
