'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import { UI_WORDS, type Exif } from '@/lib/platform';
import { checkImageAction, imageCheckNoteAction, importPeerArticleAction, runPlatformAuditAction, savePlatformSettingsAction } from '@/lib/actions-platform';

const useRun = () => { const [pending, start] = useTransition(); const router = useRouter(); return { pending, start, run: (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } }) }; };
export function PlatformSettings({ initial }: { initial: { peers: { name: string; url: string }[]; uiWords: Record<string, string>; byteBudgetKb: number } }) {
  const [p, setP] = useState(initial); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Rete, parole locali, budget di byte</div><div className="field"><label>Testate della rete (nome e indirizzo; devono esporre <code>/api/rete</code>)</label>{p.peers.map((x, i) => <div key={i} className="form-row" style={{ marginBottom: 4 }}><input className="input" placeholder="Nome" aria-label="Nome" value={x.name} onChange={(e) => setP({ ...p, peers: p.peers.map((y, j) => (j === i ? { ...y, name: e.target.value } : y)) })} /><input className="input" placeholder="https://…" aria-label="Indirizzo" value={x.url} onChange={(e) => setP({ ...p, peers: p.peers.map((y, j) => (j === i ? { ...y, url: e.target.value } : y)) })} /><button type="button" className="icon-btn danger" aria-label="Togli" onClick={() => setP({ ...p, peers: p.peers.filter((_, j) => j !== i) })}>✕</button></div>)}<button type="button" className="btn btn-ghost btn-sm" onClick={() => setP({ ...p, peers: [...p.peers, { name: '', url: '' }] })}>+ testata</button></div><div className="field"><label>Parole locali dell&apos;interfaccia (vuoto = predefinita)</label><div className="form-row" style={{ flexWrap: 'wrap' }}>{UI_WORDS.map((w) => <input key={w.key} className="input" style={{ maxWidth: 200 }} placeholder={w.fallback} aria-label={w.label} value={p.uiWords[w.key] ?? ''} onChange={(e) => setP({ ...p, uiWords: { ...p.uiWords, [w.key]: e.target.value } })} />)}</div></div><div className="field"><label htmlFor="pf-bytes">Budget di byte per pagina (kB di HTML; 0 = nessun controllo)</label><input id="pf-bytes" className="input" type="number" min={0} max={5000} style={{ maxWidth: 140 }} value={p.byteBudgetKb} onChange={(e) => setP({ ...p, byteBudgetKb: Number(e.target.value) })} /></div><div style={{ display: 'flex', gap: 6 }}><button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => run(() => savePlatformSettingsAction(p))}>Salva</button><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(runPlatformAuditAction)}>Misura adesso (byte + accessibilità)</button></div></div>;
}
export function PeerImport({ peers }: { peers: { name: string; url: string; ok: boolean; articles: { id: string; title: string; share: boolean; url: string }[] }[] }) {
  const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Scambio articoli</div><p className="help">I pezzi marcati «condivisibile» dalle altre testate si importano come bozza, con il credito in testa. I nostri: spunta «condivisibile» nell&apos;editor.</p>{peers.length === 0 && <p className="help">Nessuna testata collegata.</p>}{peers.map((p) => <div key={p.url}><b>{p.name}</b>{!p.ok && <span className="help"> · non raggiungibile</span>}<ul>{p.articles.filter((a) => a.share).map((a) => <li key={a.id}><a href={a.url} target="_blank" rel="noopener">{a.title}</a> <button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(() => importPeerArticleAction(p.url, a.id))}>Importa</button></li>)}{p.articles.filter((a) => a.share).length === 0 && p.ok && <li className="help">niente di condivisibile al momento</li>}</ul></div>)}</div>;
}
export function ImageCheck() {
  const [url, setUrl] = useState(''); const [r, setR] = useState<{ exif?: Exif; hash?: string; known?: { id: string; name: string; createdAt: string; credit?: string } | null; links?: { name: string; url: string }[] } | null>(null); const [note, setNote] = useState({ verdict: 'originale', note: '' }); const { pending, start, run } = useRun();
  const go = (dataUrl: string) => start(async () => { const x = await checkImageAction(dataUrl, url); if (!x.ok) { toast.error(x.message ?? ''); return; } setR(x); });
  const onFile = (f: File) => { const rd = new FileReader(); rd.onload = () => go(String(rd.result)); rd.readAsDataURL(f); };
  const e = r?.exif;
  return <div className="panel"><div className="panel-title">Verifica di un&apos;immagine</div><p className="help">Prima di pubblicare una foto arrivata da fuori: i metadati (quando, con cosa, dove), se ce l&apos;abbiamo già, e i link per la ricerca inversa.</p><input type="file" accept="image/*" aria-label="File" onChange={(ev) => ev.target.files?.[0] && onFile(ev.target.files[0])} /><div className="form-row" style={{ marginTop: 6 }}><input className="input" placeholder="…oppure l'indirizzo pubblico dell'immagine" aria-label="Indirizzo" value={url} onChange={(ev) => setUrl(ev.target.value)} /><button type="button" className="btn btn-outline btn-sm" disabled={pending || !url} onClick={() => go('')}>Controlla</button></div>{r && <div className="riguarda" style={{ marginTop: 8 }}><p><b>Impronta</b> <code>{r.hash}</code>{r.known ? <> · <b>già nel nostro archivio</b>: {r.known.name}, caricata il {new Date(r.known.createdAt).toLocaleDateString('it-IT')}{r.known.credit ? `, credito ${r.known.credit}` : ''}</> : ' · non è nel nostro archivio'}</p><p><b>EXIF</b> {e && (e.make || e.model || e.dateTimeOriginal || e.dateTime || e.software || e.lat) ? <>{[e.make, e.model].filter(Boolean).join(' ')}{e.dateTimeOriginal || e.dateTime ? ` · scattata ${e.dateTimeOriginal ?? e.dateTime}` : ''}{e.software ? ` · software: ${e.software}` : ''}{e.lat !== undefined && e.lon !== undefined ? <> · <a href={`https://www.openstreetmap.org/?mlat=${e.lat}&mlon=${e.lon}#map=16/${e.lat}/${e.lon}`} target="_blank" rel="noopener">posizione GPS</a></> : ''}</> : <span className="help">nessun metadato (spesso rimosso da WhatsApp e social: non è di per sé un segnale)</span>}</p>{r.links && r.links.length > 0 && <p><b>Ricerca inversa:</b> {r.links.map((l) => <a key={l.name} href={l.url} target="_blank" rel="noopener" style={{ marginRight: 10 }}>{l.name}</a>)}</p>}<div className="form-row"><select className="select" aria-label="Verdetto" value={note.verdict} onChange={(ev) => setNote({ ...note, verdict: ev.target.value })}><option value="originale">Originale, verificata</option><option value="riciclata">Riciclata (altra data o luogo)</option><option value="manipolata">Manipolata</option><option value="dubbia">Dubbia, non pubblicare</option></select><input className="input" placeholder="Nota" aria-label="Nota" value={note.note} onChange={(ev) => setNote({ ...note, note: ev.target.value })} /><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(() => imageCheckNoteAction(r.hash!, note.verdict, note.note))}>Registra</button></div></div>}</div>;
}
