'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import type { AccessSettings } from '@/lib/models';
import { deleteStageAction, saveAccessSettingsAction, saveStageAction } from '@/lib/actions-school';

export function StageManager({ list }: { list: { id: string; student: string; school: string; week: string; text: string; articleId: string }[] }) {
  const empty = { student: '', school: '', week: '', text: '', articleId: '' }; const [s, setS] = useState(empty); const [id, setId] = useState(''); const [pending, start] = useTransition(); const router = useRouter();
  const run = (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } });
  return <div className="panel"><div className="panel-title">Stage di una settimana <a className="help" href="/stage" target="_blank">apri</a></div>{list.map((x) => <p key={x.id}><a href="#" onClick={(e) => { e.preventDefault(); setId(x.id); setS(x); }}>{x.student}</a> <span className="help">· {x.school} · {x.week}</span> <button type="button" className="icon-btn danger" aria-label={`Elimina ${x.student}`} onClick={() => run(() => deleteStageAction(x.id))}>✕</button></p>)}
    <div className="form-row"><input className="input" placeholder="Studente" aria-label="Studente" value={s.student} onChange={(e) => setS({ ...s, student: e.target.value })} /><input className="input" placeholder="Scuola" aria-label="Scuola" value={s.school} onChange={(e) => setS({ ...s, school: e.target.value })} /></div><div className="form-row" style={{ marginTop: 6 }}><input className="input" type="date" aria-label="Settimana (lunedì)" value={s.week} onChange={(e) => setS({ ...s, week: e.target.value })} /><input className="input" placeholder="Id dell'articolo firmato" aria-label="Articolo" value={s.articleId} onChange={(e) => setS({ ...s, articleId: e.target.value })} /></div><textarea className="textarea" style={{ minHeight: 56, marginTop: 6 }} placeholder="Cosa ha fatto in redazione" aria-label="Racconto" value={s.text} onChange={(e) => setS({ ...s, text: e.target.value })} /><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 6 }} disabled={pending} onClick={() => run(() => saveStageAction({ ...s, id: id || undefined }), () => { setS(empty); setId(''); })}>{id ? 'Aggiorna' : 'Aggiungi'}</button></div>;
}
export function AccessForm({ initial, users }: { initial: AccessSettings; users: { id: string; name: string }[] }) {
  const [a, setA] = useState<AccessSettings>({ phone: '', tutorUserId: '', schoolIntro: '', ...initial }); const [pending, start] = useTransition();
  return <div className="panel"><div className="panel-title">Telefono, tutor, scuole</div><div className="field"><label htmlFor="ac-phone">Numero del notiziario telefonico</label><input id="ac-phone" className="input" placeholder="es. 06 1234 5678" value={a.phone} onChange={(e) => setA({ ...a, phone: e.target.value })} /><span className="help">Il servizio vocale (Twilio o simile) va puntato a <code>/api/voce</code>; il numero compare in /ascolta-al-telefono.</span></div><div className="field"><label htmlFor="ac-tutor">Tutor delle redazioni scolastiche</label><select id="ac-tutor" className="select" value={a.tutorUserId} onChange={(e) => setA({ ...a, tutorUserId: e.target.value })}><option value="">—</option>{users.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</select></div><div className="field"><label htmlFor="ac-intro">Presentazione dei giornali delle scuole</label><textarea id="ac-intro" className="textarea" style={{ minHeight: 56 }} value={a.schoolIntro} onChange={(e) => setA({ ...a, schoolIntro: e.target.value })} /></div><button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => start(async () => { const r = await saveAccessSettingsAction(a); (r.ok ? toast.success : toast.error)(r.message ?? ''); })}>Salva</button></div>;
}
