'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import { answerQuestionAction, deleteDeadlineAction, saveDeadlineAction } from '@/lib/actions-service';
import type { Deadline } from '@/lib/service';

const useRun = () => { const [pending, start] = useTransition(); const router = useRouter(); return { pending, run: (fn: () => Promise<{ ok: boolean; message?: string }>, after?: () => void) => start(async () => { const r = await fn(); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) { after?.(); router.refresh(); } }) }; };
export function QuestionsQueue({ list }: { list: { id: string; name: string; text: string; createdAt: string }[] }) {
  const [a, setA] = useState<Record<string, string>>({}); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Domande alla redazione ({list.length})</div>{list.length === 0 && <p className="help">Nessuna domanda in attesa.</p>}{list.map((q) => <div key={q.id} className="reply-item"><p><b>{q.name}</b> <span className="help">· {new Date(q.createdAt).toLocaleDateString('it-IT')}</span></p><blockquote>{q.text}</blockquote><textarea className="textarea" style={{ minHeight: 60 }} aria-label="Risposta" placeholder="La risposta" value={a[q.id] ?? ''} onChange={(e) => setA({ ...a, [q.id]: e.target.value })} /><div style={{ display: 'flex', gap: 6, marginTop: 6 }}><button type="button" className="btn btn-primary btn-sm" disabled={pending} onClick={() => run(() => answerQuestionAction(q.id, a[q.id] ?? '', true))}>Rispondi e pubblica</button><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => run(() => answerQuestionAction(q.id, a[q.id] ?? '', false))}>Rispondi solo in privato</button></div></div>)}</div>;
}
export function Deadlines({ list, subscribers }: { list: Deadline[]; subscribers: number }) {
  const empty: Deadline = { id: '', title: '', date: '', yearly: true, text: '', url: '' }; const [d, setD] = useState(empty); const { pending, run } = useRun();
  return <div className="panel"><div className="panel-title">Promemoria civici <span className="help">· {subscribers} iscritti</span></div><table className="table"><tbody>{list.map((x) => <tr key={x.id}><td>{x.date.slice(x.yearly ? 5 : 0)}{x.yearly ? ' (ogni anno)' : ''}</td><td className="t-title"><a href="#" onClick={(e) => { e.preventDefault(); setD(x); }}>{x.title}</a></td><td style={{ textAlign: 'right' }}><button type="button" className="icon-btn danger" aria-label="Elimina" onClick={() => run(() => deleteDeadlineAction(x.id))}>✕</button></td></tr>)}</tbody></table><div className="form-row" style={{ marginTop: 8 }}><input className="input" placeholder="Titolo (es. TARI, prima rata)" aria-label="Titolo" value={d.title} onChange={(e) => setD({ ...d, title: e.target.value })} /><input className="input" type="date" aria-label="Data" value={d.date} onChange={(e) => setD({ ...d, date: e.target.value })} /><label className="switch"><input type="checkbox" checked={d.yearly} onChange={(e) => setD({ ...d, yearly: e.target.checked })} /> ogni anno</label></div><input className="input" style={{ marginTop: 6 }} placeholder="Cosa fare, in una riga" aria-label="Testo" value={d.text} onChange={(e) => setD({ ...d, text: e.target.value })} /><input className="input" style={{ marginTop: 6 }} placeholder="Link (dove si fa)" aria-label="Link" value={d.url} onChange={(e) => setD({ ...d, url: e.target.value })} /><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 6 }} disabled={pending} onClick={() => run(() => saveDeadlineAction(d), () => setD(empty))}>Salva</button><p className="help">Tre giorni prima parte l&apos;email a tutti gli iscritti, una volta sola per scadenza.</p></div>;
}
