'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import { shiftDeleteAction, shiftSaveAction } from '@/lib/actions-method';

export function Shifts({ users, shifts, canEdit }: { users: { id: string; name: string }[]; shifts: { id: string; date: string; userId: string; kind: string; note: string }[]; canEdit: boolean }) {
  const [f, setF] = useState({ date: new Date().toISOString().slice(0, 10), userId: users[0]?.id ?? '', kind: 'reperibile' as 'turno' | 'reperibile', note: '' }); const [pending, start] = useTransition(); const router = useRouter(); const days = Array.from({ length: 14 }, (_, i) => new Date(Date.now() + i * 86_400_000).toISOString().slice(0, 10)); const name = (id: string) => users.find((u) => u.id === id)?.name ?? id;
  return <><div className="panel"><div className="panel-title">Prossimi 14 giorni</div><table className="table"><thead><tr><th>Giorno</th><th>In turno</th><th>Reperibile</th></tr></thead><tbody>{days.map((d) => { const t = shifts.filter((s) => s.date === d && s.kind === 'turno'), r = shifts.filter((s) => s.date === d && s.kind === 'reperibile'); return <tr key={d} className={d === new Date().toISOString().slice(0, 10) ? 'load-pieno' : ''}><td>{new Date(d).toLocaleDateString('it-IT', { weekday: 'short', day: 'numeric', month: 'short' })}</td><td>{t.map((s) => <span key={s.id} className="chip">{name(s.userId)}{canEdit && <button type="button" className="icon-btn" aria-label="Togli" onClick={() => start(async () => { await shiftDeleteAction(s.id); router.refresh(); })}>✕</button>}</span>)}</td><td>{r.map((s) => <span key={s.id} className="chip" style={{ background: '#fdeeee' }}>🚨 {name(s.userId)}{s.note ? ` · ${s.note}` : ''}{canEdit && <button type="button" className="icon-btn" aria-label="Togli" onClick={() => start(async () => { await shiftDeleteAction(s.id); router.refresh(); })}>✕</button>}</span>)}{r.length === 0 && <span className="help">nessuno</span>}</td></tr>; })}</tbody></table></div>{canEdit && <div className="panel"><div className="panel-title">Aggiungi</div><div className="form-row"><input className="input" type="date" aria-label="Giorno" value={f.date} onChange={(e) => setF({ ...f, date: e.target.value })} /><select className="select" aria-label="Persona" value={f.userId} onChange={(e) => setF({ ...f, userId: e.target.value })}>{users.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</select><select className="select" aria-label="Tipo" value={f.kind} onChange={(e) => setF({ ...f, kind: e.target.value as typeof f.kind })}><option value="turno">In turno</option><option value="reperibile">Reperibile</option></select></div><input className="input" style={{ marginTop: 6 }} placeholder="Nota (es. 20-8, telefono)" aria-label="Nota" value={f.note} onChange={(e) => setF({ ...f, note: e.target.value })} /><button type="button" className="btn btn-outline btn-sm" style={{ marginTop: 6 }} disabled={pending} onClick={() => start(async () => { const r = await shiftSaveAction(f.date, f.userId, f.kind, f.note); (r.ok ? toast.success : toast.error)(r.message ?? ''); router.refresh(); })}>Salva</button><p className="help">Negli orari di quiete le notifiche non arrivano; un&apos;emergenza dichiarata arriva a tutti e segna chi è di reperibilità.</p></div>}</>;
}
