'use client';
import { useState, useTransition } from 'react';
import { toast } from '@/components/ui/toaster';
import type { Article, ArticleKindLabel, VerificationState } from '@/lib/models';
import { KIND_LABELS, VERIFY_LABELS } from '@/lib/trust';
import { addCommitmentAction } from '@/lib/actions-trust';
import { altVersionAction } from '@/lib/actions-reading';
import { classroomAction } from '@/lib/actions-school';
import { cardsListAction } from '@/lib/actions-civic';
import { useEffect } from 'react';

type Extra = NonNullable<Article['extra']>;
/** Pannello «Fiducia» dell'editor: etichetta dell'articolo, stato di verifica, domande aperte, conflitti, promesse e previsioni. */
export function ReaderEditor({ title, content, extra, setExtra }: { title: string; content: string; extra: Extra; setExtra: (p: Partial<Extra>) => void }) {
  const [busy, setBusy] = useState(''); const [, start] = useTransition(); const [schools, setSchools] = useState<{ id: string; title: string }[]>([]); useEffect(() => { cardsListAction().then((l) => setSchools(l.filter((c) => c.kind === 'scuola'))).catch(() => {}); }, []);
  const gen = (kind: 'kids' | 'easy') => { setBusy(kind); start(async () => { const r = await altVersionAction(kind, title, content); setBusy(''); if (r.ok && r.data) { setExtra({ versions: { ...(extra.versions ?? {}), [kind]: r.data } }); toast.success('Versione pronta: rileggila prima di pubblicare.'); } else toast.error(r.message ?? 'Errore'); }); };
  return (
    <div className="panel"><div className="panel-title">Per chi legge</div>
      <div className="field"><label htmlFor="rd-mind">«Ho cambiato idea»: la domanda a cui il lettore risponde prima e dopo</label><input id="rd-mind" className="input" placeholder="es. La tangenziale va costruita?" value={extra.mindQuestion ?? ''} onChange={(e) => setExtra({ mindQuestion: e.target.value || undefined })} /></div>
      <label className="switch"><input type="checkbox" checked={!!extra.sealed} onChange={(e) => setExtra({ sealed: e.target.checked || undefined })} /> Lettera al futuro: se è programmata, il titolo compare sigillato in «Lettere al futuro» fino al giorno dell&apos;uscita</label>
      <label className="switch" style={{ margin: '6px 0 10px' }}><input type="checkbox" checked={!!extra.notebook} onChange={(e) => setExtra({ notebook: e.target.checked || undefined })} /> Mostra questa bozza nel «Quaderno» pubblico (solo titolo, sommario e avanzamento)</label>
      {schools.length > 0 && <div className="field"><label htmlFor="rd-school">Giornale della scuola (articolo scritto dagli studenti)</label><select id="rd-school" className="select" value={extra.school ?? ''} onChange={(e) => setExtra({ school: e.target.value || undefined })}><option value="">No</option>{schools.map((s) => <option key={s.id} value={s.id}>{s.title}</option>)}</select></div>}
      <div className="field"><label>Articolo in classe <button type="button" className="btn btn-outline btn-sm" disabled={!!busy} onClick={() => { setBusy('cls'); start(async () => { const r = await classroomAction(title, content); setBusy(''); if (r.ok && r.data) { setExtra({ classroom: r.data }); toast.success(r.message ?? 'Domande e glossario pronti: rileggili.'); } else toast.error(r.message ?? 'Errore'); }); }}>{busy === 'cls' ? 'Preparo…' : extra.classroom ? 'Rigenera domande' : 'Prepara domande e glossario'}</button>{extra.classroom && <button type="button" className="btn btn-ghost btn-sm" onClick={() => setExtra({ classroom: undefined })}>Rimuovi</button>}</label>{extra.classroom && <><textarea className="textarea" style={{ minHeight: 90, fontSize: 13 }} aria-label="Domande per la classe" value={extra.classroom.questions.join('\n')} onChange={(e) => setExtra({ classroom: { ...extra.classroom!, questions: e.target.value.split('\n') } })} /><p className="help">Glossario: {extra.classroom.glossary.map((g) => g.term).join(', ') || '—'}. La versione da stampare è in /classe/[id].</p></>}</div>
      <div className="field"><label htmlFor="rd-amb">Suono d&apos;ambiente (URL di un mp3 registrato sul posto)</label><input id="rd-amb" className="input" placeholder="https://…/mercato.mp3" value={extra.ambientUrl ?? ''} onChange={(e) => setExtra({ ambientUrl: e.target.value || undefined })} /></div>
      <label className="switch" style={{ margin: '6px 0 10px' }}><input type="checkbox" checked={!!extra.share?.allowed} onChange={(e) => setExtra({ share: e.target.checked ? { allowed: true, license: 'CC BY 4.0' } : undefined })} /> Condivisibile con la rete delle testate (ripubblicabile con credito, licenza CC BY 4.0)</label>
      <div className="field"><label>Guida pratica con data di verifica <span className="help">(badge nell'articolo, promemoria all'autore quando scade)</span></label><div className="form-row"><label className="switch"><input type="checkbox" checked={!!extra.guide} onChange={(e) => setExtra({ guide: e.target.checked ? { verifiedAt: new Date().toISOString().slice(0, 10), everyDays: 90 } : undefined })} /> È una guida</label>{extra.guide && <><input className="input" type="date" aria-label="Verificata il" value={extra.guide.verifiedAt.slice(0, 10)} onChange={(e) => setExtra({ guide: { ...extra.guide!, verifiedAt: e.target.value } })} /><select className="select" aria-label="Ogni quanto" value={extra.guide.everyDays} onChange={(e) => setExtra({ guide: { ...extra.guide!, everyDays: Number(e.target.value) } })}><option value={30}>riverifica ogni mese</option><option value={90}>ogni tre mesi</option><option value={180}>ogni sei mesi</option><option value={365}>ogni anno</option></select><button type="button" className="btn btn-outline btn-sm" onClick={() => setExtra({ guide: { ...extra.guide!, verifiedAt: new Date().toISOString().slice(0, 10) } })}>Verificata oggi</button></>}</div></div>
      <div className="field"><label>Sondaggio deliberativo <span className="help">(voto prima, lettura delle ragioni, voto dopo: si misura chi cambia idea)</span></label><input className="input" placeholder="Domanda sì/no (es. Va chiusa al traffico piazza Grande?)" aria-label="Domanda" value={extra.deliberation?.question ?? ''} onChange={(e) => setExtra({ deliberation: e.target.value ? { question: e.target.value, pro: extra.deliberation?.pro ?? '', contro: extra.deliberation?.contro ?? '' } : undefined })} />{extra.deliberation && <div className="form-row" style={{ marginTop: 6 }}><textarea className="textarea" style={{ minHeight: 60 }} placeholder="Le ragioni del sì" aria-label="Ragioni del sì" value={extra.deliberation.pro} onChange={(e) => setExtra({ deliberation: { ...extra.deliberation!, pro: e.target.value } })} /><textarea className="textarea" style={{ minHeight: 60 }} placeholder="Le ragioni del no" aria-label="Ragioni del no" value={extra.deliberation.contro} onChange={(e) => setExtra({ deliberation: { ...extra.deliberation!, contro: e.target.value } })} /></div>}</div>
      {(['kids', 'easy'] as const).map((k) => { const v = extra.versions?.[k]; return <div className="field" key={k}><label htmlFor={`rd-${k}`}>{k === 'kids' ? 'Versione per bambini' : 'Versione in lingua facile'} <button type="button" className="btn btn-outline btn-sm" disabled={!!busy} onClick={() => gen(k)}>{busy === k ? 'Preparo…' : v ? 'Rigenera' : 'Prepara con l\'AI'}</button>{v && <button type="button" className="btn btn-ghost btn-sm" onClick={() => setExtra({ versions: { ...(extra.versions ?? {}), [k]: undefined } })}>Rimuovi</button>}</label>{v && <><textarea id={`rd-${k}`} className="textarea" style={{ minHeight: 120, fontSize: 13 }} value={v.html} onChange={(e) => setExtra({ versions: { ...(extra.versions ?? {}), [k]: { ...v, html: e.target.value } } })} /><p className="help">Glossario: {v.glossary.map((g) => g.term).join(', ') || 'nessuna parola'}. Rileggi e correggi: esce con la firma della redazione.</p></>}</div>; })}
    </div>
  );
}
export function CostEditor({ extra, setExtra }: { extra: Extra; setExtra: (p: Partial<Extra>) => void }) {
  const c = extra.cost ?? {}; const upd = (p: Partial<NonNullable<Extra['cost']>>) => { const next = { ...c, ...p }; setExtra({ cost: Object.values(next).some((v) => v !== undefined && v !== '' && v !== 0) ? next : undefined }); };
  return (
    <div className="panel"><div className="panel-title">Quanto è costato</div><p className="help">Solo per la redazione: serve a «Ritmi di lavoro» per il costo reale dei pezzi.</p>
      <div className="form-row"><div className="field"><label htmlFor="cs-h">Ore di lavoro</label><input id="cs-h" className="input" type="number" min={0} step={0.5} value={c.hours ?? ''} onChange={(e) => upd({ hours: e.target.value ? Number(e.target.value) : undefined })} /></div><div className="field"><label htmlFor="cs-e">Spese vive (€)</label><input id="cs-e" className="input" type="number" min={0} value={c.expenses ?? ''} onChange={(e) => upd({ expenses: e.target.value ? Number(e.target.value) : undefined })} /></div></div>
      <div className="form-row"><div className="field"><label htmlFor="cs-s">Nato dal contributo di (lettore o fonte della comunità)</label><input id="cs-s" className="input" value={c.sourceName ?? ''} onChange={(e) => upd({ sourceName: e.target.value || undefined })} /></div><div className="field"><label htmlFor="cs-p">Quota dei ricavi condivisa (%)</label><input id="cs-p" className="input" type="number" min={0} max={50} value={c.sourceShare ?? ''} onChange={(e) => upd({ sourceShare: e.target.value ? Math.min(50, Number(e.target.value)) : undefined })} /></div></div>
    </div>
  );
}
export function TrustEditor({ articleId, isNew, extra, setExtra }: { articleId: string; isNew: boolean; extra: Extra; setExtra: (p: Partial<Extra>) => void }) {
  const [c, setC] = useState({ kind: 'promise' as 'promise' | 'prediction', text: '', who: '', due: '' }); const [pending, start] = useTransition();
  return (
    <div className="panel"><div className="panel-title">Fiducia e trasparenza</div>
      <div className="form-row">
        <div className="field"><label htmlFor="tr-kind">Che cos&apos;è questo testo</label><select id="tr-kind" className="select" value={extra.label?.kind ?? ''} onChange={(e) => setExtra({ label: e.target.value ? { ...(extra.label ?? {}), kind: e.target.value as ArticleKindLabel } : undefined })}><option value="">Nessuna etichetta</option>{(Object.keys(KIND_LABELS) as ArticleKindLabel[]).map((k) => <option key={k} value={k}>{KIND_LABELS[k].name}</option>)}</select></div>
        <div className="field"><label htmlFor="tr-ver">Stato di verifica</label><select id="tr-ver" className="select" value={extra.verification?.state ?? ''} onChange={(e) => setExtra({ verification: e.target.value ? { state: e.target.value as VerificationState, note: extra.verification?.note, at: new Date().toISOString() } : undefined })}><option value="">Non mostrare</option>{(Object.keys(VERIFY_LABELS) as VerificationState[]).map((k) => <option key={k} value={k}>{VERIFY_LABELS[k].name}</option>)}</select></div>
      </div>
      {extra.label?.kind && <div className="form-row"><label className="switch"><input type="checkbox" checked={!!extra.label.onSite} onChange={(e) => setExtra({ label: { ...extra.label, onSite: e.target.checked } })} /> Eravamo sul posto</label><div className="field"><label htmlFor="tr-docs">Documenti letti</label><input id="tr-docs" className="input" type="number" min={0} value={extra.label.docs ?? 0} onChange={(e) => setExtra({ label: { ...extra.label, docs: Math.max(0, Number(e.target.value) || 0) } })} /></div></div>}
      {extra.label?.kind && <p className="help">L&apos;etichetta pubblica conta da sola fonti, versioni, giorni di lavoro, uso dell&apos;AI e correzioni.</p>}
      {extra.verification?.state && <div className="field"><label htmlFor="tr-vnote">Nota sullo stato (facoltativa)</label><input id="tr-vnote" className="input" value={extra.verification.note ?? ''} placeholder="es. in attesa della conferma della Questura" onChange={(e) => setExtra({ verification: { ...extra.verification!, note: e.target.value || undefined } })} /></div>}
      <div className="field"><label htmlFor="tr-open">Cosa non sappiamo ancora (una domanda per riga)</label><textarea id="tr-open" className="textarea" style={{ minHeight: 60 }} value={(extra.openQuestions ?? []).join('\n')} onChange={(e) => { const q = e.target.value.split('\n'); setExtra({ openQuestions: q.some((x) => x.trim()) ? q : undefined }); }} onBlur={() => setExtra({ openQuestions: (extra.openQuestions ?? []).map((x) => x.trim()).filter(Boolean).slice(0, 12) })} /></div>
      <div className="field"><label htmlFor="tr-conf">Conflitto di interessi da dichiarare su questo articolo</label><input id="tr-conf" className="input" value={extra.conflict ?? ''} placeholder="es. l'autore è socio dell'associazione citata" onChange={(e) => setExtra({ conflict: e.target.value || undefined })} /></div>
      <div className="field"><label>Promessa ai lettori o previsione da verificare</label>
        {isNew ? <p className="help">Salva l&apos;articolo per registrarne una.</p> : <>
          <div className="form-row"><select className="select" aria-label="Tipo" value={c.kind} onChange={(e) => setC({ ...c, kind: e.target.value as 'promise' | 'prediction' })}><option value="promise">Promessa nostra</option><option value="prediction">Previsione di qualcuno</option></select><input className="input" type="date" aria-label="Scadenza" value={c.due} onChange={(e) => setC({ ...c, due: e.target.value })} /></div>
          {c.kind === 'prediction' && <input className="input" style={{ marginTop: 6 }} placeholder="Chi la fa (es. l'assessore Rossi)" aria-label="Chi fa la previsione" value={c.who} onChange={(e) => setC({ ...c, who: e.target.value })} />}
          <div style={{ display: 'flex', gap: 6, marginTop: 6 }}><input className="input" placeholder={c.kind === 'promise' ? 'es. Aggiorneremo l\'articolo quando esce la sentenza' : 'es. Il cantiere chiuderà entro giugno'} aria-label="Testo" value={c.text} onChange={(e) => setC({ ...c, text: e.target.value })} /><button type="button" className="btn btn-outline btn-sm" disabled={pending || !c.text.trim() || !c.due} onClick={() => start(async () => { const r = await addCommitmentAction(c.kind, articleId, c.text, c.due, c.who); (r.ok ? toast.success : toast.error)(r.message ?? ''); if (r.ok) setC({ ...c, text: '', who: '' }); })}>Registra</button></div>
          <p className="help">Alla scadenza compare in «Fiducia» e ti arriva una notifica. L&apos;esito resta visibile ai lettori.</p></>}
      </div>
    </div>
  );
}
