'use client';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from '@/components/ui/toaster';
import type { TrustSettings } from '@/lib/models';
import { saveTrustSettingsAction, settleCommitmentAction } from '@/lib/actions-trust';

export function SettleForm({ id, kind }: { id: string; kind: 'promise' | 'prediction' }) {
  const [note, setNote] = useState(''); const [pending, start] = useTransition(); const router = useRouter();
  const go = (o: 'kept' | 'missed' | 'right' | 'partial' | 'wrong') => start(async () => { const r = await settleCommitmentAction(id, o, note); (r.ok ? toast.success : toast.error)(r.message ?? ''); router.refresh(); });
  return <div className="settle"><input className="input" placeholder="Nota sull'esito (facoltativa, pubblica)" aria-label="Nota sull'esito" value={note} onChange={(e) => setNote(e.target.value)} />{kind === 'promise' ? <><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => go('kept')}>✔ Mantenuta</button><button type="button" className="btn btn-ghost btn-sm" disabled={pending} onClick={() => go('missed')}>✕ Non mantenuta</button></> : <><button type="button" className="btn btn-outline btn-sm" disabled={pending} onClick={() => go('right')}>✔ Avverata</button><button type="button" className="btn btn-ghost btn-sm" disabled={pending} onClick={() => go('partial')}>≈ In parte</button><button type="button" className="btn btn-ghost btn-sm" disabled={pending} onClick={() => go('wrong')}>✕ No</button></>}</div>;
}
export function TrustSettingsForm({ initial, users }: { initial: TrustSettings; users: { id: string; name: string }[] }) {
  const [t, setT] = useState<TrustSettings>({ funding: [], commitments: [], disclosures: {}, replyEnabled: true, ...initial }); const [pending, start] = useTransition(); const sum = (t.funding ?? []).reduce((n, f) => n + (Number(f.percent) || 0), 0);
  return (
    <div className="panel"><div className="panel-title">Pagina «Trasparenza»</div>
      <div className="field"><label htmlFor="ts-year">Chi ci paga · periodo di riferimento</label><input id="ts-year" className="input" placeholder="es. 2026" value={t.fundingYear ?? ''} onChange={(e) => setT({ ...t, fundingYear: e.target.value })} /></div>
      {(t.funding ?? []).map((f, i) => <div key={i} className="source-row"><input className="input" placeholder="Voce (es. Abbonamenti)" aria-label="Voce" value={f.label} onChange={(e) => setT({ ...t, funding: t.funding!.map((x, j) => (j === i ? { ...x, label: e.target.value } : x)) })} /><input className="input" type="number" min={0} max={100} style={{ maxWidth: 80 }} aria-label="Percentuale" value={f.percent} onChange={(e) => setT({ ...t, funding: t.funding!.map((x, j) => (j === i ? { ...x, percent: Number(e.target.value) } : x)) })} /><input className="input" placeholder="Nota (es. i tre inserzionisti principali)" aria-label="Nota" value={f.note ?? ''} onChange={(e) => setT({ ...t, funding: t.funding!.map((x, j) => (j === i ? { ...x, note: e.target.value } : x)) })} /><button type="button" className="icon-btn danger" aria-label="Rimuovi" onClick={() => setT({ ...t, funding: t.funding!.filter((_, j) => j !== i) })}>✕</button></div>)}
      <button type="button" className="btn btn-outline btn-sm" onClick={() => setT({ ...t, funding: [...(t.funding ?? []), { label: '', percent: 0 }] })}>+ Voce di entrata</button> <span className="help">Totale: {sum}%{sum !== 100 && (t.funding ?? []).length > 0 ? ' (dovrebbe fare 100)' : ''}</span>
      <div className="panel-title" style={{ marginTop: 18 }}>Impegni editoriali pubblici</div>
      {(t.commitments ?? []).map((c, i) => <div key={i} className="source-row"><input className="input" placeholder="es. Correggiamo entro 24 ore ogni errore segnalato" aria-label="Impegno" value={c.text} onChange={(e) => setT({ ...t, commitments: t.commitments!.map((x, j) => (j === i ? { ...x, text: e.target.value } : x)) })} /><select className="select" style={{ maxWidth: 150 }} aria-label="Stato" value={c.state} onChange={(e) => setT({ ...t, commitments: t.commitments!.map((x, j) => (j === i ? { ...x, state: e.target.value as 'kept' | 'progress' | 'missed' } : x)) })}><option value="kept">Rispettato</option><option value="progress">In corso</option><option value="missed">Non rispettato</option></select><input className="input" placeholder="Nota" aria-label="Nota" value={c.note ?? ''} onChange={(e) => setT({ ...t, commitments: t.commitments!.map((x, j) => (j === i ? { ...x, note: e.target.value } : x)) })} /><button type="button" className="icon-btn danger" aria-label="Rimuovi" onClick={() => setT({ ...t, commitments: t.commitments!.filter((_, j) => j !== i) })}>✕</button></div>)}
      <button type="button" className="btn btn-outline btn-sm" onClick={() => setT({ ...t, commitments: [...(t.commitments ?? []), { text: '', state: 'progress' }] })}>+ Impegno</button>
      <div className="panel-title" style={{ marginTop: 18 }}>Interessi dichiarati da chi scrive</div><p className="help">Compaiono in automatico sotto ogni articolo firmato da quella persona.</p>
      {users.map((u) => <div className="field" key={u.id}><label htmlFor={`ds-${u.id}`}>{u.name}</label><input id={`ds-${u.id}`} className="input" placeholder="es. consigliere dell'associazione X; possiede quote di Y" value={t.disclosures?.[u.id] ?? ''} onChange={(e) => setT({ ...t, disclosures: { ...(t.disclosures ?? {}), [u.id]: e.target.value } })} /></div>)}
      <label className="switch" style={{ margin: '12px 0' }}><input type="checkbox" checked={t.replyEnabled !== false} onChange={(e) => setT({ ...t, replyEnabled: e.target.checked })} /> Mostra sotto gli articoli «Chiedi il diritto di replica»</label>
      <button type="button" className="btn btn-primary" disabled={pending} onClick={() => start(async () => { const r = await saveTrustSettingsAction(t); (r.ok ? toast.success : toast.error)(r.message ?? ''); })}>{pending ? 'Salvo…' : 'Salva'}</button>
    </div>
  );
}
