import type { Metadata } from 'next';
import Link from 'next/link';
import { getSettings } from '@/lib/queries';
import { listCards, listSeries, approvedContrib } from '@/lib/civic-data';
import { basket, budgetTree, delayDays, delayStats, seriesStats } from '@/lib/civic';
import { BudgetTree } from '@/components/site/budget-tree';
import { ContributionForm } from '@/components/site/contribution-form';

export const metadata: Metadata = { title: 'La città in numeri', description: 'Cruscotto dei dati civici, cantieri con i ritardi contati, bilancio navigabile, bandi, prezzi della spesa, rumore, trasporti, alberi e scuole.' };
export const dynamic = 'force-dynamic';
export default async function CityPage({ searchParams }: PageProps<'/citta'>) {
  const sp = await searchParams; const [s, series, cantieri, bandi, ztl, scuole, prices, noise, delays, trees] = await Promise.all([getSettings(), listSeries(), listCards('cantiere'), listCards('bando'), listCards('ztl'), listCards('scuola'), approvedContrib('paniere'), approvedContrib('rumore'), approvedContrib('ritardo'), approvedContrib('albero')]);
  const now = Date.now(); const day = (iso?: string) => (iso ? new Date(iso).toLocaleDateString('it-IT', { day: 'numeric', month: 'short', year: 'numeric' }) : ''); const money = (v?: string) => (v ? Number(v).toLocaleString('it-IT', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }) : '');
  const stats = series.map((x) => ({ s: x, st: seriesStats(x.points) })).filter((x) => x.st.last); const b = budgetTree(s.civic?.budget ?? '', String(sp.anno ?? '')); const prev = b.years.includes(String(Number(b.year) - 1)) ? budgetTree(s.civic?.budget ?? '', String(Number(b.year) - 1)).tree : undefined;
  const wk = (() => { const t = new Date(); const d = (t.getUTCDay() + 6) % 7; t.setUTCDate(t.getUTCDate() - d); return t.toISOString().slice(0, 10); })(); const bk = basket(prices.map((p) => ({ product: p.data.product, price: Number(p.data.price), date: p.data.date })), wk);
  const ds = delayStats(delays.map((d) => ({ line: d.data.line, time: d.data.time, kind: d.data.kind, minutes: Number(d.data.minutes) || 0 }))); const noiseByPlace = Object.entries(noise.reduce<Record<string, typeof noise>>((m, n) => { const k = n.data.where; (m[k] ??= []).push(n); return m; }, {})).sort((a, b) => b[1].length - a[1].length);
  const openBandi = bandi.filter((x) => !x.fields.vincitore).sort((a, c) => (a.fields.scadenza ?? '').localeCompare(c.fields.scadenza ?? '')); const closedBandi = bandi.filter((x) => x.fields.vincitore);
  return (
    <div className="account" style={{ maxWidth: 960 }}><div className="account-card trust-page city-page"><h1>La città in numeri</h1><p className="lead">Dati aperti, cantieri, bilancio, prezzi, rumore, trasporti: quello che la città fa, misurato e aggiornato anche dai lettori.</p>
      <h2>Cruscotto</h2>{stats.length === 0 ? <p className="help">Nessuna serie di dati pubblicata.</p> : <ul className="dash">{stats.map(({ s: x, st }) => <li key={x.key} className={st.anomaly ? 'anomaly' : ''}><b>{st.last!.v.toLocaleString('it-IT')}{x.unit ? ` ${x.unit}` : ''}</b><span>{x.label}</span><small>{day(st.last!.d)} · {st.trend === 'su' ? '↑' : st.trend === 'giù' ? '↓' : '→'} media {st.mean.toLocaleString('it-IT')}{st.anomaly ? ' · fuori norma' : ''}{x.source ? ` · ${x.source}` : ''}</small></li>)}</ul>}
      <h2>Cantieri e opere pubbliche</h2>{cantieri.length === 0 ? <p className="help">Nessun cantiere schedato.</p> : <ul className="trust-list">{cantieri.map((c) => { const d = delayDays(c.fields.fine_prevista, c.fields.fine_effettiva, now); return <li key={c.id}><div><Link href={`/schede/cantiere/${c.slug}`}>{c.title}</Link><p>{[c.fields.via, c.fields.stato, c.fields.importo ? money(c.fields.importo) : ''].filter(Boolean).join(' · ')}</p><p className="help">{c.fields.fine_prevista ? `fine promessa ${day(c.fields.fine_prevista)}` : ''}{d !== null && !c.fields.fine_effettiva ? (d > 0 ? <b style={{ color: 'var(--red)' }}> · {d} giorni di ritardo</b> : ` · mancano ${-d} giorni`) : ''}{c.fields.fine_effettiva ? ` · concluso il ${day(c.fields.fine_effettiva)}` : ''}</p></div></li>; })}</ul>}
      <h2>Bilancio comunale</h2>{b.tree.length === 0 ? <p className="help">La redazione non ha ancora caricato il bilancio.</p> : <BudgetTree tree={b.tree} prev={prev} years={b.years} year={b.year} />}
      <h2>Bandi e gare</h2>{bandi.length === 0 ? <p className="help">Nessun bando schedato.</p> : <><ul className="trust-list">{openBandi.map((x) => <li key={x.id}><time dateTime={x.fields.scadenza}>{day(x.fields.scadenza)}</time><div><Link href={`/schede/bando/${x.slug}`}>{x.title}</Link><p>{x.fields.ente}{x.fields.base ? ` · base d'asta ${money(x.fields.base)}` : ''}</p></div></li>)}</ul>{closedBandi.length > 0 && <details><summary>Aggiudicati ({closedBandi.length})</summary><ul className="trust-list">{closedBandi.map((x) => <li key={x.id}><div><Link href={`/schede/bando/${x.slug}`}>{x.title}</Link><p>vinto da {x.fields.vincitore}{x.fields.ribasso ? ` con ribasso del ${x.fields.ribasso}%` : ''}</p></div></li>)}</ul></details>}</>}
      <h2>Il prezzo della spesa</h2><p className="help">Paniere rilevato dai lettori nei negozi della zona, settimana dal {day(wk)}.{s.civic?.basketItems ? ` Prodotti del paniere: ${s.civic.basketItems}.` : ''}</p>{bk.length === 0 ? <p className="help">Nessun prezzo questa settimana.</p> : <table className="data-table"><thead><tr><th>Prodotto</th><th>Prezzo mediano</th><th>Settimana prima</th><th>Rilevazioni</th></tr></thead><tbody>{bk.map((p) => <tr key={p.product}><td>{p.product}</td><td>{p.median.toFixed(2)} €</td><td>{p.prevMedian === null ? '–' : `${p.prevMedian.toFixed(2)} € (${p.delta! > 0 ? '+' : ''}${p.delta}%)`}</td><td>{p.samples}</td></tr>)}</tbody></table>}<ContributionForm kind="paniere" />
      <h2>Rumore e odori</h2>{noiseByPlace.length === 0 ? <p className="help">Nessuna segnalazione pubblicata.</p> : <ul className="trust-list">{noiseByPlace.slice(0, 30).map(([place, list]) => <li key={place}><div><b>{place}</b> <span className="help">· {list.length} {list.length === 1 ? 'segnalazione' : 'segnalazioni'}</span><p>{[...new Set(list.map((n) => n.data.what))].join(', ')} · orari: {[...new Set(list.map((n) => n.data.when))].sort().join(', ')}</p></div></li>)}</ul>}<ContributionForm kind="rumore" />
      <h2>Parcheggi e ZTL</h2>{ztl.length === 0 ? <p className="help">Nessuna zona schedata.</p> : <ul className="trust-list">{ztl.map((z) => <li key={z.id}><div><Link href={`/schede/ztl/${z.slug}`}>{z.title}</Link><p>{z.fields.orari}{z.fields.costo ? ` · ${z.fields.costo}` : ''}</p>{z.fields.modifiche && <p className="riguarda"><b>In arrivo:</b> {z.fields.modifiche}{z.fields.dal ? ` (dal ${day(z.fields.dal)})` : ''}</p>}</div></li>)}</ul>}
      <h2>Trasporto pubblico: ritardi veri</h2>{ds.length === 0 ? <p className="help">Nessuna segnalazione dai lettori.</p> : <table className="data-table"><thead><tr><th>Linea</th><th>Segnalazioni</th><th>Corse saltate</th><th>Ritardo medio</th><th>Ora peggiore</th></tr></thead><tbody>{ds.map((d) => <tr key={d.line}><td>{d.line}</td><td>{d.reports}</td><td>{d.skipped}</td><td>{d.avgDelay} min</td><td>{d.worstHour}</td></tr>)}</tbody></table>}<ContributionForm kind="ritardo" />
      <h2>Alberi e verde</h2>{trees.length === 0 ? <p className="help">Il censimento aspetta il primo albero.</p> : <div className="photo-grid">{trees.slice(0, 40).map((t) => <figure key={t.id}><img src={t.data.image} alt={t.data.species || 'Albero'} loading="lazy" /><figcaption><b>{t.data.species || 'Specie da identificare'}</b><span>{t.data.where} · {t.data.state}</span></figcaption></figure>)}</div>}<ContributionForm kind="albero" />
      <h2>Scuole a confronto</h2>{scuole.length === 0 ? <p className="help">Nessuna scuola schedata.</p> : <div className="table-scroll"><table className="data-table"><thead><tr><th>Scuola</th><th>Tipo</th><th>Iscritti</th><th>Classi</th><th>Tempo pieno</th><th>Mensa</th></tr></thead><tbody>{scuole.map((x) => <tr key={x.id}><td><Link href={`/schede/scuola/${x.slug}`}>{x.title}</Link></td><td>{x.fields.tipo}</td><td>{x.fields.iscritti}</td><td>{x.fields.classi}</td><td>{x.fields.tempo_pieno}</td><td>{x.fields.mensa}</td></tr>)}</tbody></table></div>}
    </div></div>
  );
}
