'use client';

import { useState, useTransition } from 'react';
import { redeemGiftAction, startPlanCheckoutAction } from '@/lib/actions-community';
import { startTeamCheckoutAction } from '@/lib/actions-revenue';
import type { PaywallPlan } from '@/lib/models';
import { toast } from '@/components/ui/toaster';

/** Piani di abbonamento (base, sostenitore, annuale…), abbonamento regalo e riscatto codice. */
export function PlansBox({ plans, loggedIn, giftCode }: { plans: PaywallPlan[]; loggedIn: boolean; giftCode: string }) {
  const [gift, setGift] = useState<{ planId: string; email: string; message: string } | null>(null); const [team, setTeam] = useState<{ planId: string; seats: number; company: string; email: string } | null>(null); const [code, setCode] = useState(giftCode); const [pending, start] = useTransition();
  if (!plans.length && !giftCode) return null;
  return (
    <div className="account-card plans-box">
      {plans.length > 0 && <><h2>Scegli il tuo piano</h2>
        <div className="plans-grid">{plans.map((p) => <div key={p.id} className={`plan ${p.highlight ? 'hl' : ''}`}><b>{p.name}</b><div className="plan-price">{p.price.toFixed(2).replace('.', ',')} €<span>/{p.interval === 'year' ? 'anno' : p.interval === 'once' ? 'una tantum' : 'mese'}</span></div><p>{p.description}{p.trialDays ? ` · ${p.trialDays} giorni di prova gratuita` : ''}</p><button className="btn btn-primary btn-sm" disabled={pending} onClick={() => start(async () => { const r = await startPlanCheckoutAction(p.id); if (r.ok && r.url) location.href = r.url; else toast.error(r.message ?? ''); })}>{loggedIn ? 'Abbonati' : 'Accedi e abbonati'}</button><button className="btn btn-ghost btn-sm" onClick={() => setGift({ planId: p.id, email: '', message: '' })}>🎁 Regala</button></div>)}</div>
        <p className="help">Pagamento sicuro con carta, Apple Pay, Google Pay e gli altri metodi attivi. Disdici quando vuoi dal tuo account.</p></>}
      {gift && <div className="gift-form"><h3>Regala un abbonamento</h3><input className="input" type="email" placeholder="Email di chi lo riceve" value={gift.email} onChange={(e) => setGift({ ...gift, email: e.target.value })} /><textarea className="textarea" placeholder="Un messaggio (facoltativo)" value={gift.message} onChange={(e) => setGift({ ...gift, message: e.target.value })} /><div className="actions"><button className="btn btn-primary btn-sm" disabled={pending || !gift.email} onClick={() => start(async () => { const r = await startPlanCheckoutAction(gift.planId, { email: gift.email, message: gift.message }); if (r.ok && r.url) location.href = r.url; else toast.error(r.message ?? ''); })}>Paga il regalo</button><button className="btn btn-ghost btn-sm" onClick={() => setGift(null)}>Annulla</button></div></div>}
      {plans.length > 0 && !team && <p className="help"><button type="button" className="link-like" onClick={() => setTeam({ planId: plans[0].id, seats: 5, company: '', email: '' })}>🏢 Abbonamento aziendale: più accessi con una sola fattura</button></p>}
      {team && <div className="gift-form"><h3>Abbonamento aziendale</h3><div className="actions"><select className="select" value={team.planId} onChange={(e) => setTeam({ ...team, planId: e.target.value })}>{plans.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="input" type="number" min={2} max={500} value={team.seats} onChange={(e) => setTeam({ ...team, seats: Number(e.target.value) })} /> <span className="help">accessi (−10% da 5, −20% da 20)</span></div><input className="input" style={{ marginTop: 8 }} placeholder="Ragione sociale" value={team.company} onChange={(e) => setTeam({ ...team, company: e.target.value })} /><input className="input" style={{ marginTop: 8 }} type="email" placeholder="Email per fattura e codici" value={team.email} onChange={(e) => setTeam({ ...team, email: e.target.value })} /><div className="actions"><button className="btn btn-primary btn-sm" disabled={pending || !team.email} onClick={() => start(async () => { const r = await startTeamCheckoutAction(team.planId, team); if (r.ok && r.url) location.href = r.url; else toast.error(r.message ?? ''); })}>Procedi al pagamento</button><button className="btn btn-ghost btn-sm" onClick={() => setTeam(null)}>Annulla</button></div></div>}
      <div className="gift-redeem"><h3>Hai un codice regalo?</h3><div className="actions"><input className="input" placeholder="DONO-XXXXXXXX" value={code} onChange={(e) => setCode(e.target.value)} /><button className="btn btn-outline btn-sm" disabled={pending || !code} onClick={() => start(async () => { const r = await redeemGiftAction(code); (r.ok ? toast.success : toast.error)(r.message ?? ''); })}>Attiva</button></div>{!loggedIn && <p className="help">Accedi o registrati prima di attivare il codice.</p>}</div>
    </div>
  );
}
